### ISSUE TITLE
showRemoveLink not showing on manuallyAddFile

### ISSUE THREAD

**Issue by RaiserWeb** [rowanwins/vue-dropzone#104]
:showRemoveLink="true" is set

When adding files via
this.$refs.theZone.manuallyAddFile(mockFile, this.internalValue.url )

The remove link is not showing

**Comment by rowanwins** [comment]
This is the same as issue #94 , some more information can be seen in #74 , unfortunantly I have not had tie to fix it yet.

**Comment by RaiserWeb** [comment]
Hi @rowanwins thanks for the info - will do the roll back. Good job on the module, it has really helped me out.

**Comment by vrajroham** [comment]
@RaiserWeb this is now resolved in latest release 2.2.8

**Comment by vrajroham** [comment]
@RaiserWeb In latest release 2.2.8 `showRemoveLink` is to `true` by default. If you want you can set it `false`as below.

I'll suggest use 

`:show-remove-link="false"` (avoid `camelCasing` of props)

By the time I'm closing this issue. Please give a shot to this config and if issue persist then re-open the issue.

**Comment by wilsonwg** [comment]
I am experiencing the same issue:
this.$refs.myUniqueId.manuallyAddFile(mockFile, url )

I get: Error in mounted hook: "TypeError: Cannot read property 'filename' of undefined"

The line above didn't work with 2.3.3. But if I rollback to 2.2.8, the code works again.
