### ISSUE TITLE
Up for adoption - looking for a new owner

### ISSUE THREAD

**Issue by rowanwins** [rowanwins/vue-dropzone#105]
This little module started life as something to play around with has amassed a fair bit of interest. Unfortunately I do not have the time required to maintain this module due to a number of other open source interests, therefor I'm putting this module up for adoption. 

If anyone would like to take ownership and responsibility for it let me know and I'll transfer the repo and npm package accordingly.  I'm happy to provide whatever useful background that I can as well as the occasional bits of support.

**Comment by vrajroham** [comment]
Hey @rowanwins, Right now I am the collaborator in a module as added by you also have worked closely with you on module. If you think I would be relevant for this then you can think.

**Comment by rowanwins** [comment]
Thanks so much @vrajroham and sorry for the slow reply (hence why this is up for adoption!). I'll touch base with you and give you as much useful info for you to take this over as possible!
