### ISSUE TITLE
url prop

### ISSUE THREAD

**Issue by grimpa** [rowanwins/vue-dropzone#106]
Hi,
I have a doubt about the URL PROP.

Question:
- Can I set the URL Prop to send post/file to a Vue method before I send it to API endpoint? I'm using StrongLoop Loopback for the API.

For example, that is I need:
```
<dropzone ref="file" id="file" url="VueMethod()" v-on:vdropzone-success="showSuccess">
        <input type="hidden" name="token1" value="xxx">
</dropzone>
```

Anybody can help?

**Comment by vrajroham** [comment]
@grimpa Right now you can't pass method to `url` prop. Because behind the scenes `url` prop is used as action for form.

**Comment by rowanwins** [comment]
Hi @grimpa 

You should be able to use the `setOption` method

something like 
````
<template>
    <div>    
      <dropzone id="myVueDropzone" url="https://httpbin.org/post" v-on:vdropzone-sending="sendingEvent"></dropzone>
  </div>
</template>

<script>
  import Dropzone from 'vue2-dropzone'

  export default {
    name: 'MainApp',
    components: {
      Dropzone
    },
    methods: {
      'sendingEvent': function (file, xhr, formData) {
        vm.$refs.file.setOption('url', 'http://somethingorother')
      }
    }
  }
</script>
````

Alternatively you might be able to hijack the xhr object...

I haven't tested either approach but one of them should work I think.

**Comment by grimpa** [comment]
Works.

In my case (using loopback for backend), I created a custom remote method in my API to receive the file, and then, in this method I manipulated everything that I needed. And then I called the upload method.

It solved my problem perfectly.
