### ISSUE TITLE
how can I use external css, which not overriding by this component?

### ISSUE THREAD

**Issue by rafi1978** [rowanwins/vue-dropzone#108]
how can I use external css, which not overriding by this component?

**Comment by vrajroham** [comment]
For this you can create your own preview template and pass as `prop`. Stay tuned for next release, which will be released soon with solution to your issue with example. I'll post here for you! :+1:

**Comment by vrajroham** [comment]
Hey @rafi1978 you can refer [this demo file](https://github.com/rowanwins/vue-dropzone/blob/bb159959e48648160bf491e4b18b97e98f597229/demo/custom-dropzone-preview.vue) .
