### ISSUE TITLE
Revamp github pages of vue-dropzone

### ISSUE THREAD

**Issue by vrajroham** [rowanwins/vue-dropzone#110]
Right now the [demo page](https://rowanwins.github.io/vue-dropzone/dist/index.html) we are looking is developed in `Vue1.0`. I'm going to revamp it using `Vue2 Component`. **:champagne: Cheers to @rowanwins for great component.**

My idea is to create a page which will list all the `props`, `methods`, `events` on same page. User can toggle any props, events on page and accordingly component will be changed. 

I have created [project](https://github.com/rowanwins/vue-dropzone/projects/1) in same repo where progress can be tracked. 

Any ideas, suggestions and contributions :heart:  are welcome!

**Comment by vrajroham** [comment]
Scaffolding ready

https://github.com/rowanwins/vue-dropzone/projects/1#card-3308665

**Comment by rowanwins** [comment]
This would be awesome @vrajroham , I'll compile some thoughts and get back to you but I think it it makes great sense!

**Comment by rowanwins** [comment]
A few thoughts
- one of the bad parts of the docs has always been the confusion of the props and the camel-casing required by vue, if the docs can make that clearer that would be great.

- The vuikit components have a really nice way of showing which events have been triggered, check out [their demo pages](https://vuikit.js.org/#/tabs) and flick to the `events` tab

**Comment by iamgoodbytes** [comment]
It's true that the props and camel-casing is confusing, so I'd second that. 

Also, it might be useful to document the properties and events in just one (up to date) place. I'm not sure if you're planning on moving the documentation to your new page or keep it here in the readme. Linking to just one place might avoid confusion.

Great work on the component!

**Comment by vrajroham** [comment]
@iamgoodbytes I'm working on it whenever I get time. Documentation will be moved to `gh-pages` branch, currently it's on my account. Have a look @ https://vrajroham.github.io/vue-dropzone-page (yet incomplete). 
I'll be happy if you have any suggestions/feedback :smile:

**Comment by vrajroham** [comment]
Hey @rowanwins, I implemented events nearly like you suggested in [comment](https://github.com/rowanwins/vue-dropzone/issues/110#issuecomment-307750263) from referring  [demo](https://vuikit.js.org/#/tabs). Please have a look [here](http://vrajroham.me/vue-dropzone-page/#/examples). Please let me know if any suggestions!
Thank you

**Comment by rowanwins** [comment]
[Docs revamped ](https://rowanwins.github.io/vue-dropzone/docs/dist/#/installation)and looking awesome!
