### ISSUE TITLE
suggestion: about font robotto

### ISSUE THREAD

**Issue by martinandersen3d** [rowanwins/vue-dropzone#111]
Hi rowanwins.. i can see in my Chrome developers tab, the request for the robotto font is made.

I hope i'm doing it right in vue, included your nice component. But i would like to suggest that you remove the line of the robotto font, and let it up to the designer to decide. 

Get me right, i like the Robotto, but I'm already having another request higher up, for a robotto variation, which means it get called twice (unnecessary). Most users does probably have a theme dictating the font, lets get it from there instead ;-)

So for the sake of maintaining code & dependencies, it would be ideal if the robotto line was deleted or and option? :)

**Comment by vrajroham** [comment]
Hey @martinandersen3d, Really great suggestion. I think you were testing [demo page](https://rowanwins.github.io/vue-dropzone/dist/index.html). Please correct me if I am wrong! If so then you was seeing demo from old component which was developed early when library was supporting vue < 2.0 . Now we are not using any font or css (except [default css](https://github.com/enyo/dropzone/blob/master/dist/dropzone.css) of dropzone library :frowning_face: and `previewTemplate` :smile: ) in current component.

We are starting work on new demo page right now, which will use all `props, events etc.`. You can refer #110, [track](https://github.com/rowanwins/vue-dropzone/projects/1),  and give more suggestions like **Roboto font..** :smiley: 

Thanks for suggestion @martinandersen3d
