### ISSUE TITLE
Update to latest dropzone 5.0.1 version for client image resizing

### ISSUE THREAD

**Issue by ellipticaldoor** [rowanwins/vue-dropzone#112]
The lates version of dropzone has client image resizing, can this be updated?

**Comment by vrajroham** [comment]
@ellipticaldoor We were actually waiting for release of 5.* . It is released yesterday so we will require some time to analyse and start work. BTW thanks for reminding.

**Comment by vrajroham** [comment]
@ellipticaldoor Component base dropzone library updated to 5.0.1, now component supports image resizing before upload to the server. For more information please check updated docs or [latest release](https://github.com/rowanwins/vue-dropzone/releases/tag/v2.3.1). 

Happy coding 😃

**Comment by ellipticaldoor** [comment]
Awesome!! 💃
