### ISSUE TITLE
Modyfying file name after upload

### ISSUE THREAD

**Issue by mendiomon** [rowanwins/vue-dropzone#118]
Can i modify fule name after upload? Lets assume that server somehow modifies file name, so i want it uploaded on frontend too. 

Can i do this without modyfying DOM, just using data model?

Currently i just edit div containing file name.

**Comment by iamgoodbytes** [comment]
Can you be a bit more clear about what you want to accomplish?
Do you want to rename the filename in order to store it on your server? What language or framework are you using?

In Laravel for example, all you need to do is something like:

```
$directory = 'uploads/icons';
$path = $file->store($directory, 'public');
```

The framework will rename and store the file.

**Comment by rowanwins** [comment]
Gday @mendiomon 

As I understand it, when your user uploads a file it will got the server, and the server might adjust it for some reason, you then want the adjusted name to be displayed in the browser.

Unfortunately there is nothing else you can hook into with the data model. I took a quick look at the `success` event and it provides read-only access to the filename, it does not let you set it.
