### ISSUE TITLE
:dropzone-options (add CSS) don't work

### ISSUE THREAD

**Issue by iamgoodbytes** [rowanwins/vue-dropzone#120]
My dropzone component works, but it has some defects. My component is loaded as follows:

```vue
<dropzone 
    ref="dropzone" 
    id="dropzone" 
    v-on:vdropzone-sending="dropzoneSending" 
    v-on:vdropzone-file-added="fileAdded" 
    name="icon" :max-number-of-files=1 
    :use-custom-dropzone-options=true 
    :dropzone-options="dzOptions" 
    url="/domains/seticon" 
    v-on:vdropzone-success="showSuccess" 
    v-on:vdropzone-error="showError" 
    v-on:vdropzone-removed-file="fileRemoved"
    ></dropzone>
```

My dzOptions object looks like this

```
dzOptions: {
       acceptedFiles: '.jpg,.jpeg,.png',
       paramName: "icon",
       headers: {'X-CSRF-TOKEN': Laravel.csrfToken},
       maxFiles: 1,
       addRemoveLinks: true,
       useFontAwesome: true
}
```

Also, when I uploaded a file, there is no nice CSS effect, it just show the word "DONE" instead of the animated checkmark.

The upload shows this when finished
![screen shot 2017-06-24 at 13 10 04](https://user-images.githubusercontent.com/3899360/27508091-92516618-58de-11e7-98c7-557951a0e83c.png)

 instead of this (screenshot from the demo)
![screen shot 2017-06-24 at 13 08 19](https://user-images.githubusercontent.com/3899360/27508094-9a28f784-58de-11e7-87dc-8f830a53bf77.png)

**Comment by vrajroham** [comment]
Hey @iamgoodbytes  sorry for the inconvenience. At night I'll have a look on it and post here.

To change  `dictDefaultMessage` you can do following.

```
dzOptions: {
    language : {
           dictDefaultMessage: '<i class="fa fa-cloud-upload" aria-hidden="true"></i><br>Drop your default domain icon here (at least 192x192px)'
        },
    acceptedFiles: '.jpg,.jpeg,.png',
    paramName: "icon",
    headers: {'X-CSRF-TOKEN': Laravel.csrfToken},
    maxFiles: 1,
    addRemoveLinks: true,
    useFontAwesome: true
}
```

**Comment by iamgoodbytes** [comment]
Thanks @vrajroham that one is solved and I had removed it from my issue here. Seems like that syntax had changed a bit and I overlooked it. 

Also, I am able to make the image work instead of the text "done" by setting the use-font-awesome option on the component itself. 

Thanks for your help
