### ISSUE TITLE
.removeFile() throws error

### ISSUE THREAD

**Issue by iamgoodbytes** [rowanwins/vue-dropzone#121]
Hi! The following code worked before I upgraded to the latest version of vue-dropzone:
`this.$refs.dropzone.removeFile(file);`

Right now, it throws the following error:

```
Uncaught TypeError: Cannot read property 'removeChild' of null
    at t.removedfile (vue2-dropzone.js?2164:1)
    at t.e.emit (vue2-dropzone.js?2164:1)
    at t.removeFile (vue2-dropzone.js?2164:2)
    at VueComponent.removeFile (vue2-dropzone.js?2164:1)
```

The reference works because `this.$refs.dropzone.manuallyAddFile(file, url);` works fine

**Comment by vrajroham** [comment]
@iamgoodbytes It's strange! May be it is base library issue. I'll give a shot and let you know soon.

**Comment by rowanwins** [comment]
Gday @iamgoodbytes 

Can you provide us more context as to how you're calling this method. I've tested and it works for me. What file are you passing it?

**Comment by iamgoodbytes** [comment]
@vrajroham @rowanwins sorry for logging this as an issue. I've traced it back to my server which was returning a wrong response, due to another issue I had after upgrading. This issue is resolved.

**Comment by vrajroham** [comment]
@iamgoodbytes Good to hear! :tada:
