### ISSUE TITLE
Error shows incorrect max files count

### ISSUE THREAD

**Issue by iamgoodbytes** [rowanwins/vue-dropzone#123]
I've set `:max-number-of-files=1` and that seems to work

However, the error that's shown display an incorrect number: "max: 0" which is confusing for a user. This might be an issue with the base library. 

![screen shot 2017-06-25 at 15 42 39](https://user-images.githubusercontent.com/3899360/27516580-fe1229b2-59bc-11e7-8ea9-95712c64ad59.png)

**Comment by vrajroham** [comment]
@iamgoodbytes thanks for pointing this. Will look into it shortly and verify it.

**Comment by vrajroham** [comment]
@iamgoodbytes It seems that `max` count in error message is depend on base library. You can see [here](src/index.vue#L182).

```
...
dictMaxFilesExceeded        : 'You can not upload any more files. (max: {{maxFiles}})',
...
```
`maxFiles` is base library option.

**Comment by vrajroham** [comment]
I have logged detailed issue on base library [#1574](https://github.com/enyo/dropzone/issues/1574). 
We will stay tuned there and update accordingly.

Thank you
