### ISSUE TITLE
Not all DropzoneJS configuration is supported.

### ISSUE THREAD

**Issue by yhosun** [rowanwins/vue-dropzone#125]
It looks like not all dropzone  configuration (options) are passed to DropzoneJS.

```:dropzone-options="dz_option" :use-custom-dropzone-options="true"```

I do not see `previewsContainer`, `createImageThumbnails`... in [code](https://github.com/rowanwins/vue-dropzone/blob/vue2/src/index.vue#L232-L259) which exists in [DropzoneJS document](http://www.dropzonejs.com/#configuration) .

I believe the DropzoneJS options used to be passed as it is when `useCustomDropzoneOptions` is `true`, and it might change.  It caused another issue https://github.com/rowanwins/vue-dropzone/pull/124.

**Comment by vrajroham** [comment]
@yhosun You are right. Unfortunately the options provided now are added long time ago by owner. Later on some were added by contributors. Right now maintainers are busy with other priority work on component development. Surely other options will be added soon when we get time. Thanks for letting us know. 

Mean while keep this issue open so progress can be tracked.

Thanks

**Comment by yhosun** [comment]
@vrajroham Thanks for letting me know!

For those who may face a similar issue, as an workaround, I am using the version 2.3.1 which passes `dropzoneOptions` to DropzoneJS as it is when `useCustomDropzoneOptions` is `true`.   The name of option should follow the  [DropzoneJS document](http://www.dropzonejs.com/#configuration) for the version.

**Comment by rowanwins** [comment]
Resolved in v3

**Comment by SteffanPerry** [comment]
Just a PSA: this is working correctly in 2.3.1 but not in 2.3.6, if you need this feature downgrade until version 3 is realeased.

**Comment by rowanwins** [comment]
Hi @yhosun 

v3 is alive, check out the [all new docs ](https://rowanwins.github.io/vue-dropzone/docs/dist/#/installation) which includes this functionality.
