### ISSUE TITLE
Error message positioned incorrectly

### ISSUE THREAD

**Issue by oldskool73** [rowanwins/vue-dropzone#127]
Because the default thumbnail width/height = 200px, while the original DZ ones are 120px, and the css for the error message hasn't been change, the error message is positioned incorrectly.

![screen shot 2017-06-29 at 5 48 32 pm](https://user-images.githubusercontent.com/967801/27676938-39d7c5cc-5cf3-11e7-9cae-a3998901c1d1.png)

To fix...

```
.dropzone .dz-preview .dz-error-message {
...
    top: 210px;
    left: 30px;
...
}
```

...or could even use something like...

```
.dropzone .dz-preview .dz-error-message {
...
    top: calc(100% + 10px);
    left: calc(50% - 70px);
...
}

```

... to allow for the thumbnail sizes to change dynamically?

**Comment by vrajroham** [comment]
@oldskool73 it's really annoying. Thanks for suggestion. Will try it soon

**Comment by vrajroham** [comment]
@oldskool73 Thanks.
