### ISSUE TITLE
rename file option required

### ISSUE THREAD

**Issue by rifaideen** [rowanwins/vue-dropzone#128]
we need a way to rename the file before sending it to the server. If user upload same file name then we should rename it before uploading to server

**Comment by neilcarpenter1** [comment]
I think should be done server-side by generating a unique file name before performing the actual upload

**Comment by rifaideen** [comment]
but in my scenario, If user has to choose multi files and after
successfully added pushing it on array and create hidden field to store
file name. in this case I need to check for optional duplicate name check.

Thanks & Regards,
- Rifaudeen

**Comment by rifaideen** [comment]
server side also doing it but we need this check on front end also
configurable using duplicateCheck key and I've added such feature created
pull request.

Thanks & Regards,
- Rifaudeen
