### ISSUE TITLE
duplicate check requried

### ISSUE THREAD

**Issue by rifaideen** [rowanwins/vue-dropzone#129]
we need a way to check find the duplicate file and should be configurable like other options., and If the user don't want to allow uploading duplicates our component should handle this situation.

**Comment by vrajroham** [comment]
Hey @rifaideen seems true and can be added as feature. Thanks for PR too! :heart:

**Comment by rifaideen** [comment]
Yes, because I also need this that's why I checked for the possibility and finally I've added.

**Comment by yogithesymbian** [comment]
not work. 
its just run remove file then run add file , did u know ???
its work remove file but after remove , its run add file function ??

**Comment by yogithesymbian** [comment]
> not work. its just run remove file then run add file , did u know ??? its work remove file but after remove , its run add file function ??

```
  <v-dropzone
          id="files"
          ref="files"
          :style="{ cursor: 'pointer' }"
          :options="{
            url: uri,
            method: `post`,
            maxFilesize: 3,
            maxFiles: maxFiles,
            chunking: true,
            acceptedFiles: acceptFile,
            autoProcessQueue: false,
            thumbnailWidth: 200,
            addRemoveLinks: true,
            addDownloadLinks: true,
            dictDefaultMessage: `${info}`,
            dictRemoveFile: 'Hapus'
          }"
          duplicate-check
          add-remove-links
          @vdropzone-removed-file="removeFile"
          @vdropzone-file-added="addFile"
          @vdropzone-complete="afterComplete"
        >
        </v-dropzone>
```
