### ISSUE TITLE
index.vue contains a non-specific i-tag styling

### ISSUE THREAD

**Issue by timenengwerda** [rowanwins/vue-dropzone#13]
When adding this component to my vue app in combination with webpack this changes my styling of all i tags that are not specifically styled whenever I browse to the page with dropzone on it.

I'd like to see the i tag be made a little more specific.

Relates to index.vue line 129

**Comment by rowanwins** [comment]
Thanks for the report @timenengwerda , I'll try and get an update out in the next week or so. Although of course Im open to a pull request :)

**Comment by timenengwerda** [comment]
Thanks a million! Do you think you can update the NPM package aswell? I can't get it to work using the git repo as a dependency :(

**Comment by MysticEarth** [comment]
+1 same here

**Comment by rowanwins** [comment]
Gu @timenengwerda & @MysticEarth 

I've updated the package on npm, it should now be available as 2.0.2

Cheers
R
