### ISSUE TITLE
Unable to click remove link

### ISSUE THREAD

**Issue by wilsonwg** [rowanwins/vue-dropzone#131]
Hi:

When the file size exceeds the upload size limit, the error message dialog shows up. However, the position of the error dialog prevents me from removing the file. Is there anyway to fix this issue? Thx!

![dialog](https://user-images.githubusercontent.com/10696151/27716887-017116ee-5d74-11e7-9c24-c5b2449f90f8.png)

**Comment by vrajroham** [comment]
@wilsonwg Agree with you. Really it's bit annoying, surely will look into it. Needs to redesign  the preview template.

**Comment by rowanwins** [comment]
Resolved in v3

**Comment by wilsonwg** [comment]
Great, thank you!
