### ISSUE TITLE
Parallel Uploads do not work.

### ISSUE THREAD

**Issue by ChadTaljaardt** [rowanwins/vue-dropzone#139]
Hello, 

I want to upload multiple files but only 1 at a time and i have tried setting the option for it and it does not work. 

Can anyone else test this to see if its a error with my setup or a bug?

Thanks!

**Comment by vrajroham** [comment]
@ChadTaljaardt We apologize for inconvenience. This problem has been resolved, soon will be referenced in new release. stay tuned! Mean while you can see cd95fec988ee686e7d8927983367fc2bdfdac18c commit resolving issue.

**Comment by ChadTaljaardt** [comment]
Do you know when the release to npm will be done?

Ill close this issue in the mean time. 

Thanks a lot.

**Comment by vrajroham** [comment]
@ChadTaljaardt [v2.3.5](https://github.com/rowanwins/vue-dropzone/tree/v2.3.5) has been released. Let us know if issue persists.

**Comment by ChadTaljaardt** [comment]
@vrajroham I'm still getting 2.3.4 using NPM?

**Comment by vrajroham** [comment]
@ChadTaljaardt Check  [v2.3.5](https://www.npmjs.com/package/vue2-dropzone)
