### ISSUE TITLE
How to trigger event?

### ISSUE THREAD

**Issue by smakman** [rowanwins/vue-dropzone#14]
How can you trigger an event? I'm trying to process the queue like so:

```js
...
methods: {
  uploadFiles() {
    this.$emit('processQueue')
  }
}
...
```

**Comment by rowanwins** [comment]
Gday @smakman 

Unfortnantly there were some changes in how events were handled between parent-child components in Vue1 & 2.

In Vue 2 perhaps the simplest way is to do something like 
````
        var arrayOfComponents= this.$children.filter(function(item){
          return item.id === "myVueDropzone";
        });
        arrayOfComponents[0].processQueue()
````
Im not sure this is 100% the best way, Im still getting my head around how the parent child communication works in Vue2 but something like this should work (although I've had to update the npm package for this component so you'll need to grab that too).
