### ISSUE TITLE
bug in manuallyAddFile preview PDF File

### ISSUE THREAD

**Issue by Eder87rh** [rowanwins/vue-dropzone#140]
How avoid this bug?

![image](https://user-images.githubusercontent.com/17674672/27970620-1e567ec4-6315-11e7-8713-f0fcd47606bd.png)

This is my code 

![image](https://user-images.githubusercontent.com/17674672/27970656-4601eaf8-6315-11e7-906d-a23f35fe13bc.png)

**Comment by vrajroham** [comment]
@Eder87rh check whether your file URL is accessible. Even though it will not cause any error. I have attached the snapshot with output which was completely reproduced with your given steps. What version you are using?

![screenshot from 2017-07-08 10 35 20](https://user-images.githubusercontent.com/12662173/27982804-d38969b8-63ca-11e7-81d8-eba68c7635dd.png)

**Comment by Eder87rh** [comment]
The URL is perfectly accessible, I tried with vue-dropzone last version without success. Any ideas? I returned to 2.2.6 version

**Comment by Eder87rh** [comment]
dropzone inserts this:

![image](https://user-images.githubusercontent.com/17674672/28026870-eb4eaaac-655c-11e7-9197-842baedbd960.png)

**Comment by rowanwins** [comment]
I think this is to do with the pdf file format, I dont think it is possible to generate a thumbnail from a pdf. If you had a png or a jpg that you could use as a thumbnail then that might be a different story...

Im going to close this issue but please reopen if you dont think it's resolved.

**Comment by Eder87rh** [comment]
@rowanwins this happens with any type of PDF, I can try with your mozilla.pdf

**Comment by hhertogh** [comment]
I have the same issue. When you add manually a pdf file, the preview is broken. How can we have the default blue thumbnail?

**Comment by kwame101** [comment]
@rowanwins Any fix for this yet? At the moment i check if its pdf or any other type of file extension (excerpt images) and set it to default image url
