### ISSUE TITLE
Max post size in a single post.

### ISSUE THREAD

**Issue by ChadTaljaardt** [rowanwins/vue-dropzone#141]
Hello, 

So when enabling multiple uploads and parallel uploads at the same time, the files get nested in a  single post which is set to the multiple files value. I want to know how this is handled when the files are very large as i'm trying to avoid any possible issues. 

So if i have 10x1GB files and my multiple uploads is true and parallel uploads is set to 10, would all 10 files be nested in a single post. Could this cause any issues?

**Comment by rowanwins** [comment]
Hi @ChadTaljaardt 

If you have `:parallel-uploads=10` then all 10 images will get sent at once. If you want to send them individually set `:parallel-uploads=1`. 

If you're dealing with large files then I'd suggest going the second option as debugging errors will potentially be easier.

Feel free to reopen the issue if you need to clarify anything
