### ISSUE TITLE
Send additional params with the images?

### ISSUE THREAD

**Issue by KsCorrales** [rowanwins/vue-dropzone#142]
i try to send inputs hidden As specified in documentation, but not arrives to the request.

**Comment by vrajroham** [comment]
@KsCorrales could you post your code snippet?

**Comment by KsCorrales** [comment]
`<dropzone>                        
    <input type="hidden" name="slotID" value="xx">
    <input type="hidden" name="imgType" value="xx">                          
</dropzone>`
i use hidden inputs to send optional params as specified in documentation, the photos was send succesfull but the params not arrives.

**Comment by KsCorrales** [comment]
also i try as specified dropzone documentation.

`
customOptionsDropzone: {
       acceptedFileTypes: 'image/*',
       useCustomDropzoneOptions: true,
       dropzoneOptions: {
            url: 'xxx',
            autoProcessQueue: false,
            params: {
            slotID:5,
            imgTipo: 4
        }
    }
 }
`

**Comment by vrajroham** [comment]
@KsCorrales What version of vue2-dropzone you are using? Check if it **not less than V2.2.5**

**Comment by rowanwins** [comment]
Hi @KsCorrales 

The best way to send parameters with a file is to do something in the `vdropzone-sending` event

eg 
````
'sendingEvent': function (file, xhr, formData) {
  formData.append('productid', this.someId);
} 

````

**Comment by sebnet** [comment]
It doesn't work either the param-name nor the hidden inputs.

**Comment by rowanwins** [comment]
What doesnt work, you need to provide more details @sebnet

**Comment by sebnet** [comment]
I just cant send additional parameters to the post. I tried:
1) hidden inputs
2) param-name
3) triggering the "sending" event.
My setup is just copy/paste from the docs.

`<dropzone id="myVueDropzone" v-on:vdropzone-sending="fileAdded"  url="http://localhost:51274/uploadasync">`

**Comment by vrajroham** [comment]
@sebnet Right now we can't reproduce the issue occurring in your case. I would suggest you upgrade the `dropzone` component and try again.

**Comment by sebnet** [comment]
That fixes it. I had the idea that I had installed the latest version with the installation instructions.
Thank you.

**Comment by vrajroham** [comment]
@sebnet Great you fixed it!

Happy coding!

**Comment by tomothumb** [comment]
It worked additional parameters with [hidden inputs] .
if i use [triggering the "sending" event].  formData is empty. 
```
'sendingEvent': function (file, xhr, formData) {
  console.log(formData); // -> {}
  formData.append('productid', this.someId);
  console.log(formData); // -> {}
} 
```

**Comment by SamBarnsby** [comment]
> It worked additional parameters with [hidden inputs] .
> if i use [triggering the "sending" event]. formData is empty.
> 
> ```
> 'sendingEvent': function (file, xhr, formData) {
>   console.log(formData); // -> {}
>   formData.append('productid', this.someId);
>   console.log(formData); // -> {}
> } 
> ```

I have the same issue

**Comment by iamsajidjaved** [comment]
Please watch this video: https://youtu.be/y8ykRE1pChI
This channel has very good content related to this vue component. This issue is covered in this video
