### ISSUE TITLE
Uncaught TypeError: Cannot read property 'status' of undefined at XMLHttpRequest.

### ISSUE THREAD

**Issue by vlahde** [rowanwins/vue-dropzone#145]
Hi, I am getting this error on my production server (https) when running dropzone upload:

> Uncaught TypeError: Cannot read property 'status' of undefined at XMLHttpRequest.

However on my local production server it works fine.

Here is how I instantiate dropbox:

```vue2
<dropzone 
    id="myVueDropzone" 
    url="/editor/tempPicture" v-on:vdropzone-success="showSuccess"
    :use-custom-dropzone-options=true
    :dropzone-options='{maxFileSizeInMB: 10, 
    acceptedFiles: "image/jpeg", 
    dictDefaultMessage: "@lang('pages.dropzone default')"}'>
</dropzone>
```

While I get the error the file is transfered but the error interrupts the execution of the code. 
Any ideas?

**Comment by vrajroham** [comment]
Can you post the code of `showsuccess` method?

**Comment by vlahde** [comment]
Here it is

`            'showSuccess': function (response) {
                console.log('A file was successfully uploaded')
                console.log(response.xhr.response)
                var res = JSON.parse(response.xhr.response);
                this.picture.filename = res.filename;
              },`

**Comment by vrajroham** [comment]
@vlahde Can't figure out the issue. :frowning_man: . Could you help with some steps to reproduce the same issue?

**Comment by vlahde** [comment]
Ofcourse. What do you need? This error occurs before showSuccess action is emitted

**Comment by rowanwins** [comment]
If you expand out the error in the console do you see anything useful @vlahde ? It might be a bit hard for us to debug this without access to your API but we'll do our best...

**Comment by vlahde** [comment]
Here is the full version of the error:

`Uncaught TypeError: Cannot read property 'status' of undefined
    at XMLHttpRequest.<anonymous> (release.js:2)
(anonymous) @ release.js:2`

and release.js looks like this (I don't think that the problem is here):
`/*
 Vue script & components for releases page
 */

Vue.component('cover', require('./components/Cover.vue'));
Vue.component('editor', require('./components/Editor.vue'));

//modal component
Vue.component('modal', {
    template: '#modal-template'
})

new Vue({
    el: '#app',
    data(){
        return{
            vars: vars,
            modalOn: false, //is modal on or not
            modalData: [], //additional modal data
            showAddDialog: false,
            coverPicture: 0,
            galleryPicture: 0,
        }
    },
    computed: {
    },
    methods: {
        showModal: function (data) {
            console.log("showModal")
            this.modalOn = data.modal;
            if(data) this.modalData = data;
        },
        modalClose: function (){
            this.modalOn = false
            bus.$emit("modalClose", this.modalData)
        },
        add: function(){
            console.log();
            if(this.showAddDialog) this.showAddDialog = false
            else{
                this.showAddDialog = true

            }
        },
        switchGalleryPicture: function(val){

            console.log('galleryPicture'+ val)
            this.galleryPicture += val;
            if(this.galleryPicture < 0) this.galleryPicture = this.vars.galleryPictures;
            if(this.galleryPicture > (this.vars.galleryPictures - 1)) this.galleryPicture = 0;
            console.log('this.galleryPicture'+ this.galleryPicture)

        },
        switchCoverPicture: function(val){

            this.coverPicture += val;
            if(this.coverPicture > (this.vars.galleryPictures - 1)) this.coverPicture = 0;
            setTimeout(function(){ this.switchCoverPicture(1) }.bind(this), 5000)
        }

    },
    created() {
        console.log("release.js")
        setTimeout(function(){ this.switchCoverPicture(1) }.bind(this), 5000)

    },
    components: {

    },
});
`

**Comment by vlahde** [comment]
If you want to take a look my app I can give the url to you personally. I rather not share it here because it is not yet in production :)

**Comment by rowanwins** [comment]
No worries @vlahde - send me a msg via twitter `@ rowanwinsemius`

**Comment by rowanwins** [comment]
Hi @vlahde 

I've taken a look but it's a bit hard to diagnose things with the minified code. From what I can tell the upload is successful. Can you try and remove the `vdropzone-success` event listener and see if that makes any difference?

**Comment by vlahde** [comment]
Well this is pretty strange. As I unminified the code, it now works! Take a look. What in minification could break the code?

**Comment by rowanwins** [comment]
hmm yeah minificiation has resulted in a few issues for people? See this comment [here](https://github.com/rowanwins/vue-dropzone/issues/119#issuecomment-314621019) for a possible fix

**Comment by vlahde** [comment]
Yes. That helped. Thank you so much for your help and thanks for the great component too!

**Comment by farrance** [comment]
Never would have worked this out myself. Thanks!

**Comment by Laurent77** [comment]
Uncaught (in promise) TypeError: Cannot read properties of undefined (reading '_c') vue2dropzone

**Comment by maksakoviliya** [comment]
> Uncaught (in promise) TypeError: Cannot read properties of undefined (reading '_c') vue2dropzone

Found how to fix?
