### ISSUE TITLE
import statement did not as shown in readme

### ISSUE THREAD

**Issue by scottgrayson** [rowanwins/vue-dropzone#15]
npm could not find this
```
  import Dropzone from 'vue-dropzone/lib/Dropzone'
```
This worked (found here: https://github.com/rowanwins/vue-dropzone/issues/5#issuecomment-260012879)
```
  import Dropzone from 'vue2-dropzone'
```

I don't have much knowledge of how `import` works. Not sure if the line in readme should be replaced or maybe another section added if you are using vue2-dropzone

**Comment by rowanwins** [comment]
Thanks for the report @scottgrayson , it's now been resolved
