### ISSUE TITLE
Custom data-dz-*

### ISSUE THREAD

**Issue by emmanesguerra** [rowanwins/vue-dropzone#150]
Hi there,

Sorry for disturbing, this is actually not an issue I'm just out of solution, wondering someone can help

I wanted to add additional button in the preview template to make the selected image as the owner

`<a class="dz-remove" href="javascript:undefined;" data-dz-owner style="bottom: 46px;">Set As Owner</a>
`
The anchor has been added to the template, but I can't call the method or function for this addons

> init: function () {
this.on("addOwnerLinks", function(file) { console.log(file); });
this.on("Owner", function(file) { console.log(file); });
this.on("owner", function(file) { console.log(file); });
}

The init above is inserted in dzOptions:

How to do this right? Or is this possible?

Many thanks!

**Comment by rowanwins** [comment]
Hi @emmanesguerra 

Can you show us your full component so we can better see what you're doing?

Thanks

**Comment by rowanwins** [comment]
CLosing due to lack of info
