### ISSUE TITLE
Request - Option to disable injected <style>

### ISSUE THREAD

**Issue by rebz** [rowanwins/vue-dropzone#151]
Could we get an option to disable the injected styles into the page.

A second request would be to override (remove) the classnames on the `<form>`.

**Comment by r4fx** [comment]
I looking for that too, i prefer to place styles in SCSS files, without needs to override defaults one

**Comment by rowanwins** [comment]
mmm that sounds like it could get fiddily, what are you trying to achieve? I'd prefer you just override the styles using whatever preprocessor you want. 

If page weight is your concern in regards to unused css t should be fairly simple to remove unused css, eg using [PurifyCss](https://github.com/webpack-contrib/purifycss-webpack) with webpack.

**Comment by r4fx** [comment]
there is too much dropzone styles, one from core dropzone, second from vue-dropzone,
and finally my own dropzone styles, there is too much unnecessary styles overriding, otherwise speaking too much mess...

![zrzut ekranu 2017-07-25 o 11 21 42](https://user-images.githubusercontent.com/4216415/28565292-15e8aeb8-712c-11e7-88ea-e9d58e7e2228.png)

**Comment by rowanwins** [comment]
Ok we'll see what we can do. We're always open to pull requests ;)

**Comment by rebz** [comment]
A few reasons as to why: declutter, minimize file sizes, have finer grain control over styling, and remove bloated specificity rules in CSS.

I am already using global styles that could easily take control of the component, but now I'm having to generate additional styles that are, at times, specific to each instance of this component.

Overall I am pleased with the work you've done, this would just make it all the more worth it.

**Comment by rowanwins** [comment]
v3 is alive, check out the [all new docs ](https://rowanwins.github.io/vue-dropzone/docs/dist/#/installation) which includes this functionality.
