### ISSUE TITLE
vue dropzone send json data format is trouble

### ISSUE THREAD

**Issue by niusmake** [rowanwins/vue-dropzone#152]
I use vdropzone-sending ,and use JSON.stringify, send to json data to php

but data become string, then php is can not load..

it is this string json

> ["[{"id":86,"tag":"bruce","tag_status":1},{"id":88,"tag":"gif","tag_status":1}]"]

```
                 <dropzone ref="addUpload" id="VueBanner" :url="url"
                    style="text-align:center"
                    v-on:vdropzone-error="showError"
                    v-on:vdropzone-sending="dropzoneSending"
                    v-on:vdropzone-success="showSuccess"
                    :auto-process-queue="false"
                    :max-number-of-files="1"
                    :thumbnail-width="300"
                    :maxFileSizeInMB="500"
                    >
                      <!-- csrf -->
                      <input type="hidden" name="_token":value="csrf">
                  </dropzone>
```

```
'dropzoneSending': function(file, xhr, formData){
         formData.append('data',JSON.stringify(this.value));
},
```

How can I do?  Please tell me. Thanks

**Comment by rowanwins** [comment]
Hi @niusmake 

So is the server receiving the data variable but you're just not sure what to do with it? If that's the case you probably need to decode your json string on the server using something like [php's json_decode function](http://php.net/manual/en/function.json-decode.php). 

If that's not it you might need to provide more information...

**Comment by niusmake** [comment]
Thank your reply~! @rowanwins 

I has try json_decode , but is error message..

> json_decode() expects parameter 1 to be string, array given

I think put json data into html form input is not work..
Is there any other way to pass from js?

like this 
```
                $.ajax({
                    url: url,
                    type: 'post',
                    data: this.value,
                })
```

**Comment by rowanwins** [comment]
I think the approach you are using in the browser is fine, I think you are just doing something wrong in your server php. Can you post a snippet from your php as to what you're doing?

**Comment by niusmake** [comment]
@rowanwins 
Hello, sorry late reply you
this is my php code 
```
$data = $request->data;
$value = json_decode($data);
```

**Comment by rowanwins** [comment]
so the error you were getting said json_decode expects an string but you passed an array, are you sure you passed in a string?

Perhaps trying something like a [gettype()](http://php.net/manual/en/function.gettype.php) to check what `$data` is
````
$data = $request->data;
echo gettype($data)
````
It may be that you need to do something like 
````
$data = $request->data;
$value = json_decode($data[0]);
````

**Comment by niusmake** [comment]
@rowanwins 
oh! this is work!  
you're so helpful . thanks a lot!!!
