### ISSUE TITLE
Setting acceptedFileTypes defers the open file dialog showing up

### ISSUE THREAD

**Issue by zhangzhen** [rowanwins/vue-dropzone#153]
Vue-dropzone is used to upload and remove files in my application. The backend is based upon Flask.
Adding the following line makes the open file dialog show up after a few seconds. After removing this line, the open file dialog shows up immediately.
`acceptedFileTypes= ".txt,.fastq.gz" `
Could one help me to solve this issue?

Thanks,
Zhen Zhang

**Comment by rowanwins** [comment]
Gday @zhangzhen 

The only thing that strikes me as weird form your snippet is whether you're missing a comma eg
````
acceptedFileTypes= ".txt, .fastq, .gz"
````
Could you try just adding a single filetype at a time and see if that makes any difference eg start with
````
acceptedFileTypes= ".txt"
````
and then another type and see if that makes any difference....

**Comment by rowanwins** [comment]
CLosing due to lack of information
