### ISSUE TITLE
Tyring to install via npm not working

### ISSUE THREAD

**Issue by kyoukhana** [rowanwins/vue-dropzone#154]
I am trying to install vue-dropzone via npm but it isn't working. 

```
npm install vue2-dropzone@^2.0.0  -save
```

**Comment by rowanwins** [comment]
What does the error say?

**Comment by kyoukhana** [comment]
I get the following error after running npm install vue2-dropzone@^2.0.0

```
zsh: no matches found: vue2-dropzone@^2.0.0
```

**Comment by rowanwins** [comment]
It's working perfectly fine for me 
`npm install vue2-dropzone@^2.0.0` 
What OS? Anything special about your setup?
