### ISSUE TITLE
Using dropzoneOptions & setting option to null

### ISSUE THREAD

**Issue by silverbackdan** [rowanwins/vue-dropzone#155]
- Vue2-dropzone Version: 2.3.5 (`npm list --depth=0`)
- Node Version (`node -v`): 8.0.0
- NPM Version (`npm -v`): 5.3.0
- OS: MacOS Sierra 10.12.5

### Description:
Using dropzoneOptions and useCustomDropzoneOptions I cannot set `thumbnailHeight` to null - it's probably to do with the check on the options. I have to define this as a property to make it take effect. This is so I can just set the width of an image with the same ratio.

### Steps To Reproduce:
This works:
```html
<dropzone class="dropzone"
            id="myVueDropzone"
            url="https://httpbin.org/put"
            :useFontAwesome="true"
            v-on:vdropzone-success="showSuccess"
            v-bind:preview-template="template"
            :useCustomDropzoneOptions="true"
            :dropzoneOptions="dropzoneOps"
            :thumbnailHeight="null"
  >
  </dropzone>
```

This does not:
```html
<dropzone class="dropzone"
            id="myVueDropzone"
            url="https://httpbin.org/put"
            :useFontAwesome="true"
            v-on:vdropzone-success="showSuccess"
            v-bind:preview-template="template"
            :useCustomDropzoneOptions="true"
            :dropzoneOptions="dropzoneOps"
  >
  </dropzone>
```
```js
data () {
      return {
        dropzoneOps: {
          dictDefaultMessage: 'Click or drop new header image',
          thumbnailMethod: 'contain',
          maxThumbnailFilesize: 5,
          thumbnailWidth: 2140,
          resizeWidth: 2140,
          method: 'PUT',
          thumbnailHeight: null
        }
      }
    }
```
^^ only difference in the data above is adding the `thumbnailHeight`

**Comment by silverbackdan** [comment]
The culprit:
https://github.com/rowanwins/vue-dropzone/blob/vue2/src/index.vue#L185

Does it need to check for anything other than `undefined`?

**Comment by vrajroham** [comment]
@silverbackdan Thanks for pointing this. We will look into it.

**Comment by rowanwins** [comment]
Hi @silverbackdan 

We've had a complete overhaul of this component so this should now be resolved. Check out the [new docs](https://rowanwins.github.io/vue-dropzone/docs/dist/#/installation)
