### ISSUE TITLE
resizeWidth and resizeHeight is not work

### ISSUE THREAD

**Issue by niusmake** [rowanwins/vue-dropzone#157]
excuse me,I use resizeWidth and resizeHeight is not work..

what happen?

```
<dropzone ref="myUniqueID" id="VueBanner" :url="url" 
              v-on:vdropzone-error="showError"
              v-on:vdropzone-success="showSuccess"
              :resize-height="500"
              :resize-width="500"
              :auto-process-queue="false"
              :max-number-of-files="1"
              :thumbnail-width="300"
              :maxFileSizeInMB="500"
              >
                <!-- Optional parameters if any! -->
                <input type="hidden" name="_token":value="csrf">
</dropzone>
```

**Comment by rowanwins** [comment]
What do you mean it doesn't work? Do you get an error?

**Comment by niusmake** [comment]
@rowanwins 
sorry, is not any error message

**Comment by vrajroham** [comment]
@niusmake Everything is working fine. I reproduced the same as you described, with different height and width. Se the output below.

I'd suggest please check the `vue2-dropzone` version you are using. It should be **2.3.1** or **greater**, as image resize feature was introduced in **2.3.1** [track here](https://github.com/rowanwins/vue-dropzone/releases/tag/v2.3.1)

-----
**Image Height : 50, Width: 50**

![image](https://user-images.githubusercontent.com/12662173/29615074-34b216a8-882a-11e7-8e2a-0ef28d141c04.png)
----
**Image Height : 200, Width: 200**

![image](https://user-images.githubusercontent.com/12662173/29615138-5ce85d26-882a-11e7-88be-a0b714c5d1ea.png)
