### ISSUE TITLE
manuallyAddFile() Cannot read property 'dontSubstractMaxFiles' of undefined

### ISSUE THREAD

**Issue by DavHanna** [rowanwins/vue-dropzone#158]
- Vue2-dropzone Version: 2.3.5
- Node Version: 6.11.0 
- NPM Version: 3.10.10 
- OS: Windows 8

### Description:
When I use manuallyAddFile() inside a forEach() to add multiple files, the first one is displayed successfully but the rest are not. And I get this error in the console:
"Uncaught (in promise) TypeError: Cannot read property 'dontSubstractMaxFiles' of undefined"

### Steps To Reproduce:
That's my vue method. It's called when the component is mounted.
```
populate: function () {
          var vue = this;
          axios.get('/get-images')
                .then(function (response) {
                  response.data.forEach(function(image, index) {
                    console.log(image);
                    vue.$refs.myVueDropzone.manuallyAddFile({name: 'filename', size: 2222}, image['tmpPath']);
                  });
                });
        },
```

**Comment by rowanwins** [comment]
HI @DavHanna 

Unfortunately this code has got a bit unweildly and poorly documented sorry
````
   vue.$refs.myVueDropzone.manuallyAddFile({
         name: 'filename', size: 2222
     },
     image['tmpPath'],
     null,
     null,
    {
     dontSubstractMaxFiles: false,
     addToFiles: true
 }
);

````

**Comment by DavHanna** [comment]
That fixed it.
Thank you @rowanwins

**Comment by lomholdt** [comment]
Thanks @rowanwins. I bumped into this very issue and your example fixed it 🎉
