### ISSUE TITLE
Default thumbnail is broken for file (not image) uploads

### ISSUE THREAD

**Issue by kmaxat** [rowanwins/vue-dropzone#159]
- Vue2-dropzone Version: vue2-dropzone@2.3.5
- Node Version (`node -v`):  v6.11.1
- NPM Version (`npm -v`): 5.3.0
- OS: Ubuntu 16.04.2 LTS

### Description:
Adding file manually brakes default (blue) thumbnail. I'm uploading a pdf file, so I don't generate the preview.
![forms angel investors](https://user-images.githubusercontent.com/2459821/28754093-b7ed3e6c-7560-11e7-987b-3ccd83fff23e.png)

### Steps To Reproduce:

1. Use code from demo
2. Change showSuccess function to this

```
showSuccess: function (file, response) {
    this.$refs.uniqueID.manuallyAddFile(
        { name: response.filename, size: response.size },
        null,
        null,
        null,
        {
            dontSubstractMaxFiles: true,
            addToFiles: true
        })

    console.log('A file was successfully uploaded')
}
```

**Comment by rowanwins** [comment]
Thanks for the report @kmaxat , I'll take a look into it and see what I can find.

**Comment by vrajroham** [comment]
@kmaxat It's really weird, see following image, which I reproduced from your given step. Completely fine! 

![image](https://user-images.githubusercontent.com/12662173/29614391-9f2461d8-8827-11e7-9c6d-8988c480bfa0.png)

**Comment by vrajroham** [comment]
Hi folks,

Version 3 is now released.[ Check out the new docs](https://rowanwins.github.io/vue-dropzone/docs/dist/#/installation) for more info.

**Comment by hhertogh** [comment]
I have the same issue. When you add manually a pdf file, the preview is broken. How can we have the default blue thumbnail?

**Comment by kishanmadhesiya** [comment]
This PR is the solution for this error.
If you are getting error on preview for non image then you can use the above PR.

https://github.com/rowanwins/vue-dropzone/pull/343

**Comment by vrajroham** [comment]
This issue has been fixed in the recent release. Check [V3.3.0](https://github.com/rowanwins/vue-dropzone/releases/tag/v3.3.0)
