### ISSUE TITLE
What is the syntax for executing methods

### ISSUE THREAD

**Issue by scottgrayson** [rowanwins/vue-dropzone#16]
```
<script>
import Dropzone from 'vue2-dropzone'

export default {
    components: {
        Dropzone
    },
    props: ['url'],
    created() {
        bus.$on('video-created', function () {
            this.upload()
        })
    },
    methods: {
        upload() {
            this.Dropzone.processQueue()
        },
    }
}
</script>
```

` this.Dropzone.processQueue() ` isn't right. what is the correct way?

**Comment by gborcherds** [comment]
The syntax is in his App.vue file. You have to get the child component and then call the processQueue() method from the component. Here is what I used to get it working.

`
var newArr = this.$children.filter(function(item){
                    return item.id === "myVueDropzone";
                });
                var component = newArr[0];
                component.processQueue()
`

**Comment by gborcherds** [comment]
I just played with this some more and the better way to do this would be to do the following

```html
<dropzone
                        ref="dropzoneEl"
                        id="fileUploads"
                        url="/url"
                >
                </dropzone>
```
On your component tag, add the ref tag so that you give your code something you can reference.

Then do this wherever you want to call the methods
```javascript
this.$refs.dropzoneEl.processQueue()
```

**Comment by rowanwins** [comment]
Thanks @gborcherds I knew of seen or done a better way but it's been a while since I've played with Vue much.

If you want to update the docs send me another pull request otherwise I'll get there 

Thanks

**Comment by rowanwins** [comment]
Updated docs thanks to @gborcherds  #20
