### ISSUE TITLE
How Can I Upload Files By Using Restful Api

### ISSUE THREAD

**Issue by huangche007** [rowanwins/vue-dropzone#161]
In my project，i wanna use this component to upload files. i see this component need a url ,but i wanna pass data to server,because server using restful api，how can i do this？

**Comment by rowanwins** [comment]
Hi @huangche007 

This currently isn't available, the only option is to pass a url, however v3 of this component is currently in the works and hopefully this functionality will be available.

**Comment by huangche007** [comment]
@rowanwins Thanks a lot , I try it

**Comment by vrajroham** [comment]
@huangche007 I'm using REST API for the same scenario you mentioned. Is there anything you tried, so I can help you to make it working?

**Comment by r4fx** [comment]
@vrajroham I have moved my post from #205 to here, to keep posts about topic in one place.

In my scenario i have an app with authorization, user needs to login to have access to application tools, my problem with vue-dropzone is that i can't (or i don't know how) to get response status during upload a file, i need to get for example 401 status to logout user if user session ended.
All my actions in app are using Axios (with Authorization inside interceptors), and there i can catch error with proper status, but not in case with vue-dropzpne where uploadUrl is a simple string url.

One option which do the job is add a hook to AJAX request (https://stackoverflow.com/a/5202999/1816520) but i'm looking for cleaner solution.

**Comment by r4fx** [comment]
ok it was trivial, `vdropzone-error` provides `xhr` parameter, which exactly do what i need.
I don't know why i did't seen it before, maybe documentation changed last time, anyway `vdropzone-error(xhr)` do the job.
