### ISSUE TITLE
Why my style does not work?

### ISSUE THREAD

**Issue by huangche007** [rowanwins/vue-dropzone#163]
I want to hide the error message box,but seems does not work,some code as follows:
` .vue-dropzone .dz-preview .dz-error-mark{
        display: none!important;
    }`
i do not know how make it works？

**Comment by huangche007** [comment]
I have solved this problem In this way:
` $(".datum-upload-layout .dropzone .dz-preview .dz-error-mark").hide();
                $(".datum-upload-layout .dropzone .dz-preview .dz-error-message").hide();`

but i really want to know why use style to hide these box not working？

**Comment by rowanwins** [comment]
`.dz-error-mark` will hide the cross icon, to hide the error message itself you'll need to do something like 
````
.vue-dropzone .dz-preview .dz-error-message {
   display:none;
}
