### ISSUE TITLE
Create tests in rails with capybara

### ISSUE THREAD

**Issue by Perafan18** [rowanwins/vue-dropzone#165]
Hello! i want create integration tests with capybara (2.4) and rails (4.2), when i try find the selector the test fail.
`page.should have_selector('#dropzone')`

` expected to find css "#dropzone" but there were no matches`.

I don't have experience in this tests.

**Comment by rowanwins** [comment]
Got no idea about rails or capybara sorry. My only thought would be that your test is running before the component has been mounted in to the DOM.
