### ISSUE TITLE
Existing files..

### ISSUE THREAD

**Issue by iahammed** [rowanwins/vue-dropzone#169]
Thanks for sharing such a nice package, I am new in VueJs,  Sometimes we'd want to use the Dropzone when editing something, not only creating a new item, 
I read existing data ( more than one ) form database I can read them from template how do I call  

manuallyAddFile(file, fileUrl, callback, crossOrigin)  

my code is as follow
```
data() {
      return {
        noOfFiles : 12,
        removeLink : true,
        fSize : .5,
        myFiles:[]
      }
    },
    
    // vdropzone-mounted() {
    //   console.log('Dropzone')
    // },

    created() {

      let self = this
        axios.get('/server-images')
          .then(function (response) {
              self.myFiles = response.data
              // self.options.files = response.data
          })
          .catch(function (error) {
              console.log(error);
          })
          console.log(self.myFiles)
    },

    methods: {

      'manuallyAddFile': function (file, fileUrl, callback, crossOrigin) {


      },
```

Your help will be appriciated

Thanks

**Comment by iahammed** [comment]
I found solution in your closed issue.

Thanks again for your nice project.

**Comment by vrajroham** [comment]
@iahammed Glad that you found the solution. Even I didn't got your issue completely! My bad :( 

I would suggest refer the solution(Issue) here which helped you, so future users with same issue can go there for the solution.

- [ ] Post your reference issue ID.

Happy Coding :man_technologist:
