### ISSUE TITLE
 Couldnt require from string: ReferenceError: window is not defined

### ISSUE THREAD

**Issue by fabianrios** [rowanwins/vue-dropzone#170]
- Vue2-dropzone Version: 2.3.5 (`npm list --depth=0`)
- Node Version (`node -v`): v7.10.0
- NPM Version (`npm -v`): v4.2.0
- OS: 

### Description:
when I use it with express-vue
https://www.npmjs.com/package/express-vue

### Steps To Reproduce:

basic express server with express-vue then try to install vue-dropzone when included 
import Dropzone from 'vue2-dropzone'; it automatically outputs the error
not sure it has to do with this:
DeprecationWarning: loaderUtils.parseQuery() received a non-string value which can be problematic, see https://github.com/webpack/loader-utils/issues/56
parseQuery() will be replaced with getOptions() in the next major version of loader-utils.

**Comment by vrajroham** [comment]
@fabianrios From your given **Steps** we can't confirm that issue raised due to `Dropzone Component`. Could you produce more stacktrace to know what exactly issue is?

**Comment by rowanwins** [comment]
I think this is outside our control.
