### ISSUE TITLE
Remove file from server..

### ISSUE THREAD

**Issue by iahammed** [rowanwins/vue-dropzone#172]
Hi I am new in JavaScript can i have an example of  axios call for removeFile 

```
<dropzone 
      ref="PlaceAds"
      id="myVueDropzone"
      url="/upload"
      method='POST'
      acceptedFileTypes='.jpg,.png'
      v-on:vdropzone-success="showSuccess"
      v-on:vdropzone-removed-file='removeThisFile'
      :preview-template="template" >
</dropzone>
<script>
methods: {
      removeThisFile (file, error, xhr) {
        this.$refs.PlaceAds.removeFile( 
                 ??????????
           )
      },

</script>
```

**Comment by rowanwins** [comment]
So you want to delete the file from the server using axios? It's a bit hard to advise how to do that without knowing your specific details.

I'd suggest you'll need an API endpoint that accepts a filename, once you've got the filename you should be able to find it on the server and delete it.

**Comment by rosnaib11** [comment]
Here's a basic example. Get the filename `file.name` then pass it to server using my example, so you are able to locate where your filestore to delete.


removeThisFile (file, error, xhr) {
    const data = {
       filename:  file.name
    }

    axios({
          url: '', //endpoint
          method: 'POST',
          data : data,
          config: 'JSON'
    })
},

**Comment by adriandmitroca** [comment]
It's quite unsafe to depend just on the filename, what happens if user uploads two files with the same name?

**Comment by adriandmitroca** [comment]
As a really easy fix for this, I strongly recommend comparing md5 hashes of stored file on the server and base64 string sent by Dropzone like this:

```
md5($request->get('file')['dataURL']) === md5_file($media->getPath())
```

With that and comparing file names, we can be pretty much sure that we are not removing different file.
