### ISSUE TITLE
Dropzone options does not work 

### ISSUE THREAD

**Issue by krsrk** [rowanwins/vue-dropzone#173]
![bug](https://user-images.githubusercontent.com/5818377/29570522-4f19bc44-871c-11e7-82e1-0c89bdcedc6b.PNG)

- Vue2-dropzone Version: 2.3.5 
- Node Version (`node -v`): 6.10.0
- NPM Version (`npm -v`): 3.10.10
- OS: Windows 10

### Description:
Dropzone Options doesnt work.

### Steps To Reproduce:

1.- Install latest release or vue dropzone
2.- Import to my component: import Dropzone from 'vue2-dropzone';
3.- Attach to the component(in export default):
components:{
            'dropzone': Dropzone,
        }, 
3.- Attach vue dropzone to the template of the component: 
<dropzone ref="myUniqueID"
                      id="myVueDropzone"
                      :url="urlUpload"
                      :use-custom-dropzone-options="true"
                      :dropzone-options="dzOptions">
            </dropzone>
4.- Define dzOptions to the data component:
dzOptions: {
                    paramName: "files",
                    uploadMultiple: true,
                    dictDefaultMessage: "Arrastra tus archivos aquí. O click aquí",
                    dictRemoveFile: "Quitar Archivo",
                    maxFiles: 2,
                    params: {_token: 1, pass_cer:'1'},
                    acceptedFiles: ".cer,.key",
                    addRemoveLinks: true,
                },
5.- Run npm run dev.
6.- It compiles with the default options, like if there is no dropzone-options define. Like the images attached. By the way im using Laravel and Homestead. But in Php Storm i execute the npm commands in Terminal. In the image there is the options in the vue dropzone component.

**Comment by rowanwins** [comment]
To use the `dropzoneOptions` prop you need to set the `useCustomDropzoneOptions` prop to true

**Comment by krsrk** [comment]
```
<dropzone ref="myUniqueID"
                      id="myVueDropzone"
                      :url="urlUpload"
                      :use-custom-dropzone-options="true"
                      :dropzone-options="dzOptions">
            </dropzone>
```
I've already attach useCustomDropzoneOptions to true, and it doesnt work. Same version 2.3.5
