### ISSUE TITLE
Getting 422 error from Laravel on upload

### ISSUE THREAD

**Issue by adavie1** [rowanwins/vue-dropzone#176]
- Vue2-dropzone Version: **2.3.5**
- Node Version (`node -v`): **6.11.0**
- NPM Version (`npm -v`):  **3.10.10**
- OS: Linux 16.04 - Chrome

### Description:
The component on the client side, but I'm getting a 422 error saying: "you did not send the required json in the body"

### Steps To Reproduce:
Configured as follows:
**Vue code**
```
    <dropzone :id="thisRef" :use-font-awesome="true"
    :url="url" v-on:vdropzone-success="showSuccess">
        <!-- Optional parameters if any! -->
        <input type="hidden" name="token" value="xxx123">
    </dropzone>
```
**Script code:**
```
<script>
import Dropzone from 'vue2-dropzone'

export default {
  components: {
    Dropzone
  },

  props: {
    id: {
      type: [String, Number],
      required: true
    },
    type: {
      type: String,
      required: true
    }
  },

  computed: {
    url: function () {
      return this.getEndpoint('/upload/' + this.type.toLowerCase().trim() + '/' + this.id)
    }
  },

  methods: {
    showSuccess: function (file) {
      console.log('A file was successfully uploaded', file)
    },
    onError: function (file) {
      console.log('A file was NOT uploaded', file)
    }
  },

  data () {
    return {
      thisRef: this.type.toLowerCase() + '-uploader',
      localType: this.type.toLowerCase().trim(),
      headerInfo: {   // Not used
        'Access-Control-Allow-Origin': this.url,
        'Access-Control-Allow-Methods': 'GET, POST, OPTIONS, PUT, DELETE',
        'Access-Control-Allow-Headers': 'Origin, X-Requested-With, Content-Type, Accept, X-File-Name, X-File-Size, X-File-Type'
      },
      fileData: {
        type: this.type,
        id: this.id,
        caption: null
      }
    }
  }
}
</script>
```
On error output:
![image](https://user-images.githubusercontent.com/3030402/29699553-46e2af6a-8990-11e7-92b5-30221cc737ea.png)

On uploading any file, I get a 422 response, yet the file gets to the server, but is rejected, since I can see that in the error response. I'm assuming I've not configured something correctly?

**Comment by rowanwins** [comment]
Gday @adavie1 

Nothing sticks out as immediately obvious. Perhaps try removing the additional input from the html?
````
<dropzone :id="thisRef" :use-font-awesome="true"
    :url="url" v-on:vdropzone-success="showSuccess">
</dropzone>
````

Also doing some googling this issue also appears with Laravel occassionally when you have validation on the server-side, so perhaps check if you have any validation occurring in your laravel code and if that is failing for some reason....

Hope that helps

**Comment by adavie1** [comment]
Thanks @rowanwins in the end, I hacked the JsonApiMiddleware on Laravel. Got it all working. Brilliant component BTW.
