### ISSUE TITLE
Small advice, need to provide several parameters

### ISSUE THREAD

**Issue by 531431988** [rowanwins/vue-dropzone#177]
- Vue2-dropzone Version: #.#.# (`npm list --depth=0`)
- Node Version (`node -v`): 
- NPM Version (`npm -v`): 
- OS: 

### Description:
1、组件中使用的图标可自定义，
2、上传成功后文件名可修改

**Comment by rowanwins** [comment]
Please write the issue on English

**Comment by vrajroham** [comment]
@531431988 Your first and second issue are understandable. Can you explain bit more about **Language configuration is imperfect, such as "complete", "wrong" and so on**
