### ISSUE TITLE
How send Auth Credentials with manuallyAddFile()

### ISSUE THREAD

**Issue by Maj0rrush** [rowanwins/vue-dropzone#178]
### Description:
Im getting my Images trough a restful api.

I need to pass the auth header with manuallyAddFile() but there is no option ... is it planned to integrate ?

**Comment by rowanwins** [comment]
I think i you set headers as part of the regular options they will get applied to files uploaded using the `manuallyAddFiles` method. let me know if that doesnt work.

**Comment by vrajroham** [comment]
@Maj0rrush You can take reference of @rowanwins 's comment on simillar issue.
https://github.com/rowanwins/vue-dropzone/issues/11#issuecomment-263522381
