### ISSUE TITLE
dropzoneOptions 

### ISSUE THREAD

**Issue by 531431988** [rowanwins/vue-dropzone#179]
- Vue2-dropzone Version: #.#.# (`npm list --depth=0`)
- Node Version (`node -v`): 
- NPM Version (`npm -v`): 
- OS: 

### Description:
```
<dropzone 
                        id="myVueDropzone" 
                        url="https://httpbin.org/post" 
                        :useFontAwesome="true"
                        :useCustomDropzoneOptions="true"
                        :dropzoneOptions="dropzoneOpt"
                        :preview-template="template">
                        <input type="hidden" name="token" value="xxx">
                    </dropzone>

dropzoneOpt:{
                dictDefaultMessage: 'Click or drop new header image111',
                thumbnailMethod: 'contain',
                maxThumbnailFilesize: 5,
                thumbnailWidth: 2140,
                resizeWidth: 2140,
                method: 'PUT',
                thumbnailHeight: null
            },
```
### Steps To Reproduce:
![image](https://user-images.githubusercontent.com/8703951/29955001-7988fb6c-8f0e-11e7-82dd-1ddfa7030066.png)

**Comment by 531431988** [comment]
No effect set

**Comment by vrajroham** [comment]
## Use as below


dropzoneOpt:{
                language: {
                    dictDefaultMessage: 'Click or drop new header image111'
                },
                thumbnailMethod: 'contain',
                maxThumbnailFilesize: 5,
                thumbnailWidth: 2140,
                resizeWidth: 2140,
                method: 'PUT',
                thumbnailHeight: null
            },
