### ISSUE TITLE
Console warning when setting clickable property to CSS selector

### ISSUE THREAD

**Issue by ijdickinson** [rowanwins/vue-dropzone#184]
- Vue2-dropzone Version: #.#.# (`npm list --depth=0`) vue2-dropzone@2.3.5
- Node Version (`node -v`): v8.4.0
- NPM Version (`npm -v`): 5.3.0
- OS: Ubuntu 17.04
- Vue version: vue@2.4.2

### Description:

I have a Vue-Dropzone component and a separate `upload` button for initiating the upload. According to the documentation, the `clickable` property takes either a string or a Boolean argument:

> Whether the dropzone area is clickable, if false then users can only drag items 
> on to the area. Can also accept a CSS selector of an element that will open the 
> file dialog when clicked.

My component has:

    <dropzone
        id='dropzone'
        :url='url'
        :headers='headers'
        :accepted-file-types='".doc,.docx"'
        :auto-process-queue='true'
        :use-font-awesome='true'
        :max-number-of-files='1'
        :clickable='"#upload-button"'
      </dropzone>

However, while this does work I get a warning on the browser console:

    [Vue warn]: Invalid prop: type check failed for prop "clickable". Expected Boolean, 
    got String. Found in
    ---> <Dropzone>
       <ElCol>
         <ElRow>
           <LoadSourceDocument> at app/javascript/packs/components/load-source-document.vue
             <App> at app/javascript/packs/App.vue
               <Root>

### Steps To Reproduce:

Create a Dropzone component as above.

**Comment by SergioReis97** [comment]
Same problem, also get these

> [Vue warn]: Error in mounted hook: "Error: Invalid `clickable` option provided. Please provide a CSS selector, a plain HTML element or a list of those."

> Error: Invalid `clickable` option provided. Please provide a CSS selector, a plain HTML element or a list of those.

**Comment by vrajroham** [comment]
@ijdickinson @SergioReis97 Thanks for pointing. I'll look into it!

**Comment by vrajroham** [comment]
@ijdickinson @SergioReis97 Everything is working as expected in my case. 

Specifically for @SergioReis97, Verify whether your html element exist with provided selector. The error occurred in your case is due to not getting the element with specified `html selector`

**Comment by SergioReis97** [comment]
I've tried placing the selector on the navbar and it does trigger the file upload action but still got the errors on console

**Comment by vrajroham** [comment]
Is your selector is outside of the component in which `dropzone` is imported?

**Comment by SergioReis97** [comment]
The navbar yes, but the button is above it directly, like this

```
<button class="btn btn-primary btn-clickme">Click me to browse Files </button>
<dropzone clickable='".btn-clickme"'....></dropzone>
```

**Comment by vrajroham** [comment]
@SergioReis97 Really weird! Even though making change like yours it works for me!

**Comment by SergioReis97** [comment]
I even tried putting the button in the index.html file that to make sure the button exists when dropzone tries to query it but no efect. Maybe a possible solution could be using slots for some of those props.

For example
```
<template slot="clickable" >
   <button class="btn btn-primary">Click me to browse Files </button>
</template>
```
And even for the language props this slotting could be usefull in case someone wants a more complex message.

**Comment by vrajroham** [comment]
@SergioReis97 Check this [example](https://github.com/rowanwins/vue-dropzone/blob/vue2/src/App.vue#L6-L16) which works perfectly for me.

**Comment by SergioReis97** [comment]
Same problem, also tryed with ok as false and then on mounted function making ok true and still same errors.

**Comment by vrajroham** [comment]
Hi folks,

Version 3 is now released.[ Check out the new docs](https://rowanwins.github.io/vue-dropzone/docs/dist/#/installation) for more info.

**Comment by bjensen** [comment]
We still get this error when unittesting using jest. The clickable element is in a different component. Any idea how we can fix this?
