### ISSUE TITLE
overwritten function accept doesn't get called

### ISSUE THREAD

**Issue by Onestay** [rowanwins/vue-dropzone#186]
- Vue2-dropzone Version: 2.3.5 (`npm list --depth=0`)
- Node Version (`node -v`): v8.4.0
- NPM Version (`npm -v`): 5.3.0
- OS: Windows 10 (64bit)

### Description:
I've set the useCustomDropzoneOptions to true and passed the dropzoneOptions object into the dropzone but the accept function doesn't get called. From what I understand it should get called whenever a new file is added to the dropzone.

### Steps To Reproduce:
Create the dropzone
```
<h-dropzone :url="url" :id="id" @vdropzone-sending="sending" :useCustomDropzoneOptions="true" :dropzoneOptions="dropzoneOptions"></h-dropzone>
```
and then set this as your data property
```
	data() {
		return {
			url: 'placeholder',
			id: 'dropzone',
			isLoading: true,
			dropzoneOptions: {
				accept(file, done) {
					console.log(file);
					done();
				},
			},
		};
	},
```
and the accept function won't get called

Onestay

**Comment by vrajroham** [comment]
@Onestay 
What I understand is you want to call `function`(accept) when any file is added. For this purpose there's `event` available called `vdropzone-file-added(file)` you can listen to this event and call the `function`.

Here's little snippet which can help you.

```vue
<!-- your component -->
<h-dropzone 
    :url="url" 
    :id="id" 
    @vdropzone-sending="sending" 
    @vdropzone-file-added="fileAdded" 
    :useCustomDropzoneOptions="true" 
    :dropzoneOptions="dropzoneOptions">
</h-dropzone>
```

```javascript
data() {
	return {
		url: 'placeholder',
		id: 'dropzone',
		isLoading: true,
		dropzoneOptions: {				
		},
	};
},
methods:{
    fileAdded(file){
        //your awesome code
    }
}
```

Hope it helps you!

**Comment by Onestay** [comment]
Well I know this exists but I need to do a async task (fetching some data
from a server) before uploading. Therefore the done callback would be great
for that. If there's any way to do this in this event I could use that

**Comment by rowanwins** [comment]
Ah ok I understand @Onestay , I'm thinking we should be able to tackle this more easily in v3. Thanks for the report, I've never noticed those functions.

**Comment by rowanwins** [comment]
Hi @Onestay 

v3 is alive, check out the [all new docs ](https://rowanwins.github.io/vue-dropzone/docs/dist/#/installation) which includes this functionality.
