### ISSUE TITLE
Setting custom dropzone message

### ISSUE THREAD

**Issue by ijdickinson** [rowanwins/vue-dropzone#187]
- Vue2-dropzone Version: #.#.# (`npm list --depth=0`) 2.3.5
- Node Version (`node -v`): 8.4.0
- NPM Version (`npm -v`): 5.3.0
- OS: Ubuntu 17.04

### Description:

I'm having a similar problem to #173 - I can't get the custom Dropzone options to work. In particular, I'm trying to override the default "Drop files here to upload" message. My setup is below

### Steps To Reproduce:

Template:

        <dropzone
          id='media-dropzone'
          ref='mediaDropzone'
          :url='this.url'
          :accepted-file-types='".pdf"'
          :headers='headers'
          :auto-process-queue='true'
          :use-font-awesome='true'
          :max-number-of-files='1'
          :use-custom-dropzone-options='true'
          :dropzone-options='dropzoneOptions'
          v-on:vdropzone-success='onSuccess'
          v-on:vdropzone-error='onError'
          v-on:vdropzone-file-added='onFileAdded'>
        </dropzone>

Script:

    export default {
      data() {
        return {
          dropzoneOptions: {
            dictDefaultMessage: 'Drop a PDF file here, or click to select a file to upload.',
          },
        };
      },
      ....

**Comment by vrajroham** [comment]
@ijdickinson 
Please go through https://github.com/rowanwins/vue-dropzone/issues/166#issuecomment-324314857 this link. Basically you need to set message in `language` object.

**Comment by vrajroham** [comment]
Try as below

```javascript
dropzoneOptions: {
     language : {
        dictDefaultMessage: 'Drop a PDF file here, or click to select a file to upload.',
       }
    },
```

Hope it helps you..

**Comment by ijdickinson** [comment]
Thanks @vrajroham, that worked perfectly!

I'm glad I asked though: needing the `language` object wrapper is not very obvious in the docs. If I have time, I'll try to work up a PR for the readme that can try to make that a bit clearer.

**Comment by dbuhonov** [comment]
dictDefaultMessage: 'Drop a PDF file here, or click to select a file to upload.'

In options, for vue2
