### ISSUE TITLE
useFontAwesome parameter don't work in the options object

### ISSUE THREAD

**Issue by FrancescoMussi** [rowanwins/vue-dropzone#188]
- Vue2-dropzone Version: 2.3.5 (`npm list --depth=0`)
- Node Version (`node -v`): 8.4.0
- NPM Version (`npm -v`): 5.4.1
- OS: Sierra 10.12.6

### Description:
`
useFontAwesome` doesn't work if it is passed as a property of the options object.
It only works if passed in the component itself as `:use-font-awesome="true"`

### Steps To Reproduce:

Here is the code without `:use-font-awesome="true"` in the component:

```
<dropzone id="some-dropzone" url="https://httpbin.org/post" :use-custom-dropzone-options="true" :dropzone-options="dzOptions" v-on:vdropzone-success="showSuccess">
  <input type="hidden" name="token" value="xxx">
</dropzone>
```

```
import Dropzone from 'vue2-dropzone';

components: { Dropzone },

dzOptions: {
 paramName: "pics",
 uploadMultiple: true,
 acceptedFiles: ".jpg,.png",
 useFontAwesome: true,
 language : {
    dictDefaultMessage: 'Drop the images here, or click to select a file to upload.',
  }
},
```

**Comment by vrajroham** [comment]
@FrancescoMussi Thanks for pointing it! I'll look into it and post here.

**Comment by rowanwins** [comment]
Have you added the fontawesome css somewhere @FrancescoMussi ?

eg `<link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet">`

**Comment by FrancescoMussi** [comment]
Yes fontAwesome is properly included. As a matter of fact it does work properly using `:use-font-awesome="true"`. 

But it doesn't work when useFontAwesome: true is set as the property of the options object.

**Comment by rowanwins** [comment]
Ah interesting, thanks for that clarification @FrancescoMussi

**Comment by pisty** [comment]
Same here

**Comment by rowanwins** [comment]
Hi @FrancescoMussi & @pisty ,

This is now superseded by v3, check out the d[ocs for info on adding custom icons](https://rowanwins.github.io/vue-dropzone/docs/dist/#/installation).
