### ISSUE TITLE
How to override css style?

### ISSUE THREAD

**Issue by FrancescoMussi** [rowanwins/vue-dropzone#189]
- Vue2-dropzone Version: 2.3.5 (`npm list --depth=0`)
- Node Version (`node -v`): 8.4.0
- NPM Version (`npm -v`): 5.4.1
- OS: Sierra 10.12.6

### Description:

I am having troubles trying to override the style of the component. 
Is still this the way to go:

https://github.com/rowanwins/vue-dropzone/issues/42

### Steps To Reproduce:

This is how I have tried, but doesn't work:

```
<dropzone id="imagesDropzone" url="https://httpbin.org/post" :use-custom-dropzone-options="true" :dropzone-options="dzOptions" :use-font-awesome="true" v-on:vdropzone-success="showSuccess">
  <input type="hidden" name="token" value="xxx">
</dropzone>
```

```
<style>
  
#imagesDropzone > .dz-success-mark i {
  color: red!important;
  text-align: center;
}

</style>
```

**Comment by vrajroham** [comment]
> Is still this the way to go:
Yes! currently #42 is only the option to override the css of component. We have addressed this issue in V3.
