### ISSUE TITLE
Can't get manuallyAddFile to work.

### ISSUE THREAD

**Issue by AndersBrohus** [rowanwins/vue-dropzone#191]
- Vue2-dropzone Version: 2.3.5
- Node Version (`node -v`): v8.2.1
- NPM Version (`npm -v`): 5.3.0
- OS: Windows 10

### Description:
I got a modal where the dropzone is inside, and i would like the dropzone to contain the files already are uploaded to it, when it get's reopened.

So i'll have to watch when the modal is getting opened.

So i have created an watch, with this code.
````
if (this.value.visible) {
                    var i = 0;
                    var dropzoneRef= this.type + "Dropzone";
                    console.log(this.value.files.length);
                    while (i < this.value.files.length) {
                        var file = this.value.files[i];
                        var mockFile = { name: file.file_name, size: file.file_size };
                        this.$refs[dropzoneRef].manuallyAddFile(mockFile);
                        console.log("File added:");
                        console.log(mockFile);
                        i++;
                    }
                }
````
But when i hit the 

`                        this.$refs[dropzoneRef].manuallyAddFile(mockFile);
`

It just stops, and does not print out the console logs, and does not add the file to the dropzone.

The "mockFile" looks like this,

`{name: "Anonym-mand-300x450.jpg", size: 5240}` when it get printed.

It does not give any errors i just stops.

**Comment by AlexanderYW** [comment]
I had a issue with `manuallyAddFile` too, but i got it working sorta

First make sure you're not using the minified version of Vue since that can be some errors preventing your code from running and they're not showing when your running the production version of Vue

Then make sure you add the needed parameters for the `manuallyAddFile` function and not only the info about the file it self your adding

Here is a sample of my working code
```
this.$refs.yourCustomRefsName.manuallyAddFile({
                            name: '{filename}', size: {file size}
                        },
                        '{URL TO YOUR FILE}, // I'm using this for images, not sure if you should make it null if its not an image
                        null,
                        null,
                        {
                            dontSubstractMaxFiles: false,
                            addToFiles: true //<-- If you get an error with 'removeChild' turn this false
                        }
                    );
```

For more info about the `manuallyAddFile` function look at the source, since the documentation is not up to date
https://github.com/rowanwins/vue-dropzone/blob/c459af69840a1cf6a4eb6d7db9b26683cfe03977/src/index.vue#L145

Let me know if that helped you

**Comment by AndersBrohus** [comment]
Hi @AlexanderYW :)

Thanks for your help, but i can't get it to work with your code either :/

I got the following code, i have set the "URL TO FILE" as null since i don't want a thumbnail of it :)

`watch: {
            "value.visible": function () {
                if (this.v.visible) {
                    var i = 0;
                    var dropzoneRef = this.type + "Dropzone";
                    console.log(this.value.files.length);
                    while (i < this.value.files.length) {
                        var file = this.value.files[i];
                        this.$refs[dropzoneRef.toString()].manuallyAddFile({name: file.file_name, size: file.file_size}, null, null, null, {
                            dontSubstractMaxFiles: false,
                            addToFiles: true
                        });
                        i++;
                    }
                }
            },
        },`

**Comment by AlexanderYW** [comment]
Does it print a new error in the console with the updated code?

I thought you wanted the thumbnail since you worked with images :), but yes just set it to `null` then

**Comment by AndersBrohus** [comment]
Nope no error, but i after many times i figured out what i did wrong, i did not use the 

vdropzone-mounted() but was running the code in a watch instead.. :)

After i switched to the mounted it worked right away.. :)
