### ISSUE TITLE
previewsContainer Not working with version 2.3.5

### ISSUE THREAD

**Issue by dineshs27** [rowanwins/vue-dropzone#193]
Trying to use previewsContainer(Working with version 2.0.0).  But not working with latest version. Is there any configuration change.

**Comment by vrajroham** [comment]
@dineshs27 Could you provide you code snippet about what you tried and what was the error etc.

**Comment by dineshs27** [comment]
Hello Viabhav,

Thanks for your reply. I just need your help for some customization part. I
have have tried customization , but not able to get final product.

I have attached my requirement as requirment.jpg


I have tried with vue2-dropzone version 4.3.0 and almost done with my
requirements.  Please see acheived.jpg.


And this was on my local server. Yesterday i had deployed the code on
server and installed vue2-dropzone but it was with updated version.
vue2-dropzone@2.3.5 and dropzone 5.1.1.

So my customization was not working like dictDefaultMessage.

Today i have again tried by updating my local machine vue2-dropzone@2.3.5.
And used following script

<div>
            <dropzone
                ref="myVueDropzone"
                id='dropzone-upload'
                url="https://httpbin.org/post"
                v-on:vdropzone-success="showSuccess"
                useFontAwesome="true"
                :previews-container='previews'
                :previewTemplate="template"
                :useCustomDropzoneOptions="true"
                :dropzoneOptions="{
                    autoProcessQueue:true,
                    addRemoveLinks:true,
                    clickable: '.attach-files',
                    previewsContainer:'#previews',
                    language: {
                        dictDefaultMessage: '<i class=\'fa
fa-picture-o\'></i><br/>You can drag and drop images <br/> into this window
to upload<br/><input type=\'button\' class=\'btn btn-default attach-files\'
value=\'Browse for images\' />'
                    },
                    acceptedFileTypes: 'image/*'
                }"
                :maxFileSizeInMB="10"
                :createImageThumbnails="false"
            >
            </dropzone>
            <p id="previews">&nbsp;</p>
          </div>


dictDefaultMessage is working now but previewsContainer is not working for
me and also i have to display upload progress as %age. You can see that in
requirement.jpg.


I have also opened issue here

https://github.com/rowanwins/vue-dropzone/issues/193

**Comment by rowanwins** [comment]
Hi @dineshs27 

the `previewsContainer` is provided directly by dropzone.js, we don't actually do anything to that setting so it may be that the change in dropzone version dependency is what has changed things rather than us...

Perhaps just looking at [their config doco ](http://www.dropzonejs.com/#config-previewsContainer)make sure you have added the `dropzone-previews` class to your element.

Or perhaps try something like 
````
<p ref="previews">&nbsp;</p>
 \\ and do something like 
:dropzoneOptions:{
    previewsContainer: this.refs.previews
}
````

**Comment by vrajroham** [comment]
Hey @dineshs27 Did you managed to solve the issue?

**Comment by dineshs27** [comment]
@rowanwins thanks for your reply.
@vrajroham  yes i have managed to solve the issue , but for that i used default dropjone.js library. Using "vue-dropzone" i have not found any such option.

**Comment by vrajroham** [comment]
Closing issue #193 as related to core dropzone library.
