### ISSUE TITLE
vue-dropzone without a form wrapper

### ISSUE THREAD

**Issue by DaniG2k** [rowanwins/vue-dropzone#196]
Hello, I am wondering if it's possible to prevent vue-dropper from creating a form element wrapper?

I am trying to nest vue-dropper within a Rails form but it seems to generate a new form, which is effectively causing there to be nested forms on my page.

Thanks in advance!

**Comment by rowanwins** [comment]
Hi @DaniG2k , this will be possible with v3 which is currently being worked on

**Comment by rowanwins** [comment]
Hi @DaniG2k 

Version 3 is now released which doesn't use a form wrapper.  New docs [available here](https://rowanwins.github.io/vue-dropzone/docs/dist/#/installation)
