### ISSUE TITLE
Hacktoberfest 2017

### ISSUE THREAD

**Issue by vrajroham** [rowanwins/vue-dropzone#197]
Hacktoberfest by Digital Ocean will be running again this year through the month of October 2017. As already @rowanwins is trying hard to redesign the complete component in [Version3](https://github.com/rowanwins/vue-dropzone/tree/version3) considering the issues which are reported by users and hard to fix in Version2. If anyone sees any room for improvement to the codebase, has ideas, suggestions, bug-fixes, or whatever else, if you want to win a free Hacktoberfest t-shirt and some stickers, consider signing up for this year and sending some pull requests to this repository. :-)

For more details: https://hacktoberfest.digitalocean.com/#details

_Issue will remain open until the end of October._

----
You can pickup any issue from [here](https://github.com/rowanwins/vue-dropzone/issues) and make PR to [v3 branch](https://github.com/rowanwins/vue-dropzone/tree/version3) :tada:

**Comment by imcvampire** [comment]
@vrajroham Can I create MR to upgrade webpack to lastest version?

**Comment by AlexanderYW** [comment]
Perfect!, I got a lot of time to pass, maybe I will drop a few PR's on the project ;)

**Comment by AlexanderYW** [comment]
Also @vrajroham don't forget to add a `CONTRIBUTING.md` file :)

**Comment by rowanwins** [comment]
Hey @AlexanderYW 

Feel free to check out the v3 branch, you'll see it's pretty much a complete overhaul, although hopefully a much simpler code base now. If you have any questions feel free to drop them here.

**Comment by AlexanderYW** [comment]
@rowanwins cool!, should I just add the latest changes, I made for vue2 branch to v3 instead then?

**Comment by rowanwins** [comment]
i take it you're referring to [this pull request](https://github.com/rowanwins/vue-dropzone/pull/199), if so yep!

**Comment by AlexanderYW** [comment]
That is correct, you want me to cancel the current one a make a new one for the v3?

**Comment by rowanwins** [comment]
yes please :)

**Comment by rowanwins** [comment]
It's alive!
