### ISSUE TITLE
Any chances of a making two branches for this component

### ISSUE THREAD

**Issue by kyoukhana** [rowanwins/vue-dropzone#2]
One for Vue 1.x and one for Vue 2.x.

**Comment by rowanwins** [comment]
Hi @kyoukhana 

I've just started playing with Vue 2 over the past few days although not with this component in mind so I'll take a look and see what it should take to move it across, I think it should be fairly straight forward.

Cheers

**Comment by borger** [comment]
+1

**Comment by rowanwins** [comment]
Hi @kyoukhana @borger 

This is now up and running.  I've released the Vue 2 version on to npm with the name `vue2-dropzone`.

I might get myself organised and shuffle around my branches if I can work out how to do it without breaking everything :)

Cheers
Rowan

**Comment by rlambertsen** [comment]
This works perfectly! Please update the README so people can find this plugin for Vue2.0

**Comment by rowanwins** [comment]
Good thinking @rlambertsen , as mentioned above I'll hopefully get myself organised in a few weeks and shuffle the branches and update the doco etc to make it all a bit more user friendly.
