### ISSUE TITLE
Getting error when JS is compiled for production

### ISSUE THREAD

**Issue by demonmind** [rowanwins/vue-dropzone#200]
When Webpack compiles the assets in production mode I get this error in console:

```
vue.runtime.esm.js:562 Error: Invalid dropzone element.
    at new e (vue2-dropzone.js:1)
    at o.mounted (vue2-dropzone.js:1)
    at Ct (vue.runtime.esm.js:2661)
    at Object.insert (vue.runtime.esm.js:3522)
    at M (vue.runtime.esm.js:5465)
    at o.t.nodeOps [as __patch__] (vue.runtime.esm.js:5635)
    at o.t._update (vue.runtime.esm.js:2420)
    at o.r (vue.runtime.esm.js:2534)
    at ai.get (vue.runtime.esm.js:2877)
    at ai.run (vue.runtime.esm.js:2954)
```

In development mode works fine. How can I fix it?

**Comment by vrajroham** [comment]
Please provide some code snippet like how are you using dropzone in your project? which version you are using etc. 
**Try to use provided issue guidelines, so we can assist you better**

---



- Vue2-dropzone Version: #.#.# (`npm list --depth=0`)
- Node Version (`node -v`): 
- NPM Version (`npm -v`): 
- OS: 

### Description:


### Steps To Reproduce:

**Comment by demonmind** [comment]
- vue2-dropzone@2.3.5
- Node v8.6.0
- npm 5.3.0
- OS Ubuntu 16.04 LTS

Snippet:

```
          <dropzone
              id="flightCreateUploader"
              ref="flightCreateUploader"
              url="/flights/create_flights.json"
              v-on:vdropzone-success="showSuccess"
              :preview-template="template"
              :autoProcessQueue="false"
              :useFontAwesome="true"
              :maxFileSizeInMB="500">
          </dropzone>
```

JS:

```
......
import Dropzone from 'vue2-dropzone';
......
```

When i compile the assets `bundle exec rake asset:precompile` in production mode, Rails 5, Webpacker compiles the files into public js files in the js folder. That is when i get the error. I do not get any error in development mode.

**Comment by demonmind** [comment]
Also this line 

`@import url('~dropzone/dist/dropzone.css');` 

Throws an error if i try and import Dropzone from the index.vue path because that file does not exist.

**Comment by demonmind** [comment]
So i kind of fixed it by cloning your library, removing the css import because fails to find the file during import and using it via the index.vue import.

This worked for me. Not sure if this is a bug or something I am doing wrong.

**Comment by rowanwins** [comment]
Thanks for the report @demonmind . There have been one or two issues with people using various build tools. Unfortunately they are often a build hard to cater for due to variability to how people are using the component, that said we'll take a look at that import statement and see if we can improve that somehow.
