### ISSUE TITLE
How to properly add files manually?

### ISSUE THREAD

**Issue by FrancescoMussi** [rowanwins/vue-dropzone#203]
- Vue2-dropzone Version: 2.3.6
- Node Version (`node -v`): v8.4.0
- NPM Version (`npm -v`): 5.4.2
- OS: macOs Sierra 10.12.6

### Description:

For a simple CRUD, I am doing the edit page where I need to preload in the dropzone the previously uploaded images from the server. But I am encountering some problems.

### Steps To Reproduce:

**1.** First of all. **Where is the proper place to manually add files?** In the `mounted` method? 
Because it doesn't work for me. It does only work if the code is place inside a 

```
setTimeout(() => {

}, 1000);
```

**2.** **Which is the correct way to manually add files?**

I have found this in the docs but doesn't work for me:

`this.$refs.dropZoneEdit.manuallyAddFile(mockFile, image.base64);`

In this way I get the following error:

`Uncaught TypeError: Cannot read property 'dontSubstractMaxFiles' of undefined`

So I found this code somewhere in a previous github issue:

```
this.$refs.dropZoneEdit.manuallyAddFile(
     mockFile,
     image.base64,
     null,
     null,
     {
      dontSubstractMaxFiles: false,
      addToFiles: true
     }
);
```
With this code the error disappear. 
But where is the documentation about this? Did I miss it?

**3.** **How to create the thumbnail?** The thumbnails automatically generated are big in scale and cropped. I find in the docs that I should use `createThumbnailFromUrl` to make my own. 
I have tried this code: 

`this.$refs.dropZoneEdit.createThumbnailFromUrl(mockFile, base64, this.createThumbnail, this.crossOrigin);
`
But it gives the following error:

`Uncaught TypeError: _this.$refs.dropZoneEdit.createThumbnailFromUrl is not a function`

Is that code wrong? How can I do it correctly?

Thanks!

**Comment by vrajroham** [comment]
@FrancescoMussi 

- Firstly you can also add files directly from `mounted()` but, some times component(dropzone) takes time to load and your `mounted()` code gets executed before initialization of component. Best way is to **listen to `vdropzone-mounted` event and then add your files**.

- We apologize for incomplete documentation. The second approach you found is valid way to add a file. (We missed it in docs, which will be updated soon)

- For manually added file you don't need to create thumbnail. It's created automatically. You can track [here](https://github.com/rowanwins/vue-dropzone/blob/vue2/src/index.vue#L156). But it's **known  issue** that sometimes it creates weird thumbnail.

Thanks

**Comment by FrancescoMussi** [comment]
Thank you very much for the quick response!

1. I test it with the timeout set to 100 ms and it works fine. So no problem!
2. Okay. I just wasn't sure of the proper approach. 
3. I actually express wrongly my point. Sorry. The thumbnails are generated. 
The problem, as you say, is that they are weird:

![screen shot 2017-10-04 at 11 39 56](https://user-images.githubusercontent.com/5312907/31166843-d052f430-a8f8-11e7-9347-af1e8306d076.png)

Somehow it is a cropped part of the image in a big scale.
There is something I can do to resize and adjust them?

**Comment by AlexanderYW** [comment]
To fix the issue you are experiencing either you should convert the default previewTemplate into adding the base64/url as an background on a div tag with `background-size:cover;` instead of img tag (I made this possible a few weeks ago)

or you should add `style['object-fit'] = 'contain'` to the img tag through one of the following events `vdropzone-thumbnail, vdropzone-file-added, vdropzone-success`

I'm sorry for your issues but that the default behaviors of dropzone as what I know

**Comment by FrancescoMussi** [comment]
@AlexanderYW thanks for replying. 
I didn't manage though.
Could you please give me an example?

This is my code:

Here is the loop where I manually add files to the dropzone:

```
for (var i = 0; i < this.property.images.length; i++) {

  let mockFile = {
    name: this.property.images[i].name,
    size: this.property.images[i].size,
    accepted: true,
    kind: 'image',
    upload: {
      filename: this.property.images[i].name,
    },
    dataURL: this.property.images[i].base64,
  };

  this.$refs.dropZoneEdit.manuallyAddFile(
       mockFile,
       image.base64,
       null,
       null,
       {
        dontSubstractMaxFiles: false,
        addToFiles: true
       }
  );
}
```

And this is my dropzone:

```
<dropzone ref="dropZoneEdit" id="dropzone-edit" url="https://httpbin.org/post" acceptedFileTypes='.jpg,.png,.jpeg' :use-custom-dropzone-options="true" :dropzone-options="dzOptions" :use-font-awesome="true" v-on:vdropzone-success="showSuccess" v-on:vdropzone-removed-file="imageRemoved">
    <input type="hidden" name="token" value="xxx">
</dropzone>
```

**Comment by AlexanderYW** [comment]
First add a custom template, in this case we just replaced the img tag with a div with a data attribute called `data-dz-thumbnail-bg`. add the template through this binding on the element `v-bind:preview-template="template"`
```
template: function (options) {
                return `<div class="dz-preview dz-file-preview">
                        <div class="dz-image">
                            <div data-dz-thumbnail-bg></div>
                        </div>
                        <div class="dz-details">
                            <div class="dz-size"><span data-dz-size></span></div>
                            <div class="dz-filename"><span data-dz-name></span></div>
                        </div>
                        <div class="dz-progress"><span class="dz-upload" data-dz-uploadprogress></span></div>
                        <div class="dz-error-message"><span data-dz-errormessage></span></div>
                        <div class="dz-success-mark">${options.doneIcon}</div>
                        <div class="dz-error-mark">${options.errorIcon}</div>
                    </div>
                `;
            },
```

Now you have your custom template, now we want to add the `dataUrl` to the data attribute. `dataUrl` can both be an base64 or an url, but in this case it dosen't matter. Add the thumbnail binding with `v-on:vdropzone-thumbnail="thumbnail"` on the element
```
thumbnail: function(file, dataUrl) {
                var j, len, ref, thumbnailElement;
                if (file.previewElement) {
                    file.previewElement.classList.remove("dz-file-preview");
                    ref = file.previewElement.querySelectorAll("[data-dz-thumbnail-bg]");
                    for (j = 0, len = ref.length; j < len; j++) {
                        thumbnailElement = ref[j];
                        thumbnailElement.alt = file.name;
                        thumbnailElement.style.backgroundImage = 'url("' + dataUrl + '")';
                    }
                    return setTimeout(((function(_this) {
                        return function() {
                            return file.previewElement.classList.add("dz-image-preview");
                        };
                    })(this)), 1);
                }
            },
```
You may edit this code for your needs and remove the unnecessary (I didn't write this, I only modified the original thumbnail function)

When those two things are added all you need to do is add some styling to the custom div with the background eg:
```
.vue-dropzone .dz-preview {
        width: calc(20% - 32px);
        padding-top: calc(20% - 32px);
        box-shadow: 0 4px 10px 0 rgba(0, 0, 0, 0.05);
    }
    .vue-dropzone .dz-preview .dz-image {
        border-radius: 1;
        position: absolute;
        top: 0;
        left: 0;
        width: 100%;
        height: auto;
        bottom: 0;
    }
    .vue-dropzone .dz-preview .dz-image > div {
        position: absolute;
        top: 0;
        left: 0;
        bottom: 0;
        width: 100%;
        background-size: cover;
        background-position: center;
    }
```

That should be it, let me know if it works or not

**Comment by FrancescoMussi** [comment]
@AlexanderYW  Thank you for all your efforts. But sorry I didn't manage. 

But would be possible to make this a general fix?

I understand that it is a known issue regarding the scale of the thumbnail image for manually added files. 
Maybe doing a general fix would benefit everybody.

Is that perhaps in the roadmap?

Thanks!

**Comment by AlexanderYW** [comment]
Hi @FrancescoMussi, this should not be a general fix, since vue2-dropzone should have the same behavior ad dropzone. but i Will add it to v3 as a demo file to help people do this

**Comment by FrancescoMussi** [comment]
@AlexanderYW thanks. Do you know more or less when v3 is about to be released?

Sorry to insist :)

But everybody using this component, will have troubles in the thumbnails when manually adding files. And each user will basically have to manually fix the component?

Couldn't be nice for the component to be easy to use - and don't have to do that?

**Comment by AlexanderYW** [comment]
@vrajroham @rowanwins: when do we expect to release?

They will not have any troubles if they provide dropzone with resized thumbnails that fits their styling :)

If you want this behavior changed I would suggest you make a issue on the original dropzone :)

**Comment by FrancescoMussi** [comment]
@AlexanderYW  I followed your suggestion I provided the resized thumbnail.

Now it is properly working. The generated thumbnail 200x200 is properly shown in the dropzone.

It required some extra work and change in the process.

- Before I was just storing the base64 in the database.
- Now I save the image on the server, from that image I create a thumbnail 200x200 with Laravel Intervention Image and save it on the server, save the path in the database and retrieve the path to load the thumbnail.

If in the future that could be done automatically in the dropzone by providing a base64 image could be awesome.

After all, when uploading an image - that image is properly resized into a thumbnail - so it is needed the same process for manually added files.

Anyway thanks for the help!

**Comment by rowanwins** [comment]
I'm going to close this due to a major release of v3, [check out the new docs](https://rowanwins.github.io/vue-dropzone/docs/dist/#/installation) which include a demo of manually adding a file

**Comment by iamsajidjaved** [comment]
Kindly watch this video if anybody is facing this issue. The video is short and to the point. https://www.youtube.com/watch?v=zoA5tizAa2w

**Comment by fahmiegerton** [comment]
> I'm going to close this due to a major release of v3, [check out the new docs](https://rowanwins.github.io/vue-dropzone/docs/dist/#/installation) which include a demo of manually adding a file

in my case, this doesn't work either. I have object data like this already 
`files: [
  {
      name: 'something.jpg',
      type: 'image/jpg',
      size: 97,
      url: 'http://example.com/file.jpg'
  },
  {
  .....
  }
]`

I'm new and maybe I miss something, please kindly let me know. thank you!

**Comment by snarcraft** [comment]
@andrewrusselrenner you might use this for each file
`
const reader = new FileReader();
     reader.addEventListener("load", () => {
     this.dropZoneEdit.manuallyAddFile(file, reader.result)
 }, false);
reader.readAsDataURL(file);
`

**Comment by unamdev0** [comment]
@andrewrusselrenner for me it worked after the project got build,try building the project once.
