### ISSUE TITLE
how do i pass a auth token when uploading a image

### ISSUE THREAD

**Issue by kyoukhana** [rowanwins/vue-dropzone#21]
I am trying with this

```
 <dropzone id="fileDropZone" url="api/track/upload"
                                  v-bind:dropzone-options="options"
                                  v-bind:use-custom-dropzone-options="true">
                        </dropzone>
```

```

        data: function () {
            return {
                options: {headers: {Authorization: 'bearer:'+this.$auth.token(),trackCategory:1}},
            }
        }
```

**Comment by rowanwins** [comment]
Didn't we tackle this in #11 @kyoukhana ?

**Comment by moeen-basra** [comment]
I just submitted a pull request after merging this we can pass the headers object as prop.

**Comment by rowanwins** [comment]
I've now added support for this headers option based on @moeen-basra pull request #26 

It is available from npm as version 2.1.4

**Comment by MariusWiik** [comment]
I cannot get this to work. Is is possible to bind headers and still use a custom options object? I need to add the headers later than the rest of the options (or have the possibility to add the options object at a later stage, in for example computed() ). 
Hesitant to open a new issue if its just me using it wrong.
Any ideas?

```javascript
 <dropzone ref="uploadZone" id="myVueDropzone" 
              url="/api/v1/room/xyzxyz/upload" 
              v-on:vdropzone-success="showSuccess"
              v-on:vdropzone-error="handleError"
              v-bind:headers="headers"
              acceptedFileTypes="image/*"
              useCustomDropzoneOptions
              :dropzoneOptions="dzoptions"
              >
              
    </dropzone>
data() {
        return {

            dzoptions: {
                clickable: true,
                uploadMultiple: false,
                addRemoveLinks: true,
                autoProcessQueue: false,         
                dictRemoveFile: "Delete",
                previewTemplate: '<div> Long template here </div>',

            }
        }
    },

 computed: {
        headers(){
            return {
                Authorization: "TokenHere" 
            }
        }
    },
```

**Comment by rowanwins** [comment]
Gday @MariusWiik 

The custom options settings override everything else so if you want to use custom options you need to pass through the headers into your dzoptions object eg
````
dzoptions: {
                clickable: true,
                uploadMultiple: false,
                addRemoveLinks: true,
                autoProcessQueue: false,         
                dictRemoveFile: "Delete",
                previewTemplate: '<div> Long template here </div>',
                headers: this.headers
            }
````

Hope that helps

**Comment by rowanwins** [comment]
hmmm @MariusWiik i see your problem.

I've just added a `setOption` method which you can call after the component has been initialised.

So you should be able to do something like once you have your token.
````
 this.$refs.myUniqueID.setOption('headers', {auth: 123})
````

I've updated npm to v2.2.2 so perhaps give that a go and see if you can get things working

**Comment by MariusWiik** [comment]
This worked like a charm. Good job! I'm sure others will also appreciate this change :) Thanks!
