### ISSUE TITLE
v-ref issue in side v-for

### ISSUE THREAD

**Issue by glowens** [rowanwins/vue-dropzone#210]
I am using Dropzone within a v-for and v-refs are not supported.  Can you indicate if there is a work around for this or can you call the Dropzone methods directly without $ref?

<div v-for="item in items"> 
.....
      <dropzone ref="myVueDropzone"  class="droparea" id="dropzone" :url="'url'" 
                                                v-on:vdropzone-success="showSuccess" 
                                                v-bind:dropzone-options="dropzoneOptions"  
                                                :use-custom-dropzone-options="true"
                                                :use-font-awesome="true" 
                                                :thumbnail-width="144"
                                                :thumbnail-height="144"
                                                >
                                                <input type="hidden" name="token" :value="xxx">
                                            </dropzone> 
.....
</div>

The following gives "can not give property of 'processQueue' of undefined
console.log(this.$refs.myVueDropzone.dropzone.processQueue() );

**Comment by rowanwins** [comment]
Hmmm interesting one @glowens , could you perhaps use `this.$children` ([doco](this.$refs.myVueDropzone.dropzone.processQueue() )) to find the component?

**Comment by glowens** [comment]
Thanks.  I was able to use this.$children and was able to get to the methods I needed.  I was hoping there could be an easier way.

**Comment by rowanwins** [comment]
Sorry @glowens nothing comes to mind. Closing as it's not really an issue with this component, more to do with Vue itself.
