### ISSUE TITLE
vdropzone-removed-file fires when you close a modal that has a dropzone

### ISSUE THREAD

**Issue by demonmind** [rowanwins/vue-dropzone#211]
- Vue2-dropzone Version: 5.2.0
- Node Version 8.6.0
- NPM Version 5.4.2
- OS: osX

### Description:

```
        <dropzone
          id="flightEditUploader"
          ref="flightFilesUpload"
          :url="asset_upload_url"
          :preview-template="template"
          :autoProcessQueue="true"
          :useFontAwesome="true"
          :maxFileSizeInMB="500"
          v-on:vdropzone-success="showSuccess"
          v-on:vdropzone-removed-file="removeAssetFromFlight">
        </dropzone>
```
This is on modal that when i hit `close` triggers something like `this.$modal.close('modal')`

Everytime i hit `close` i see `removeAssetFromFlight` triggering removing all assets from my object.

**Comment by AlexanderYW** [comment]
I think this is due to `this.$modal.close('modal')` triggers the destroy event of Vue on `vue2-dropzone`, which call the default event of dropzonejs that removes all files
```
beforeDestroy () {
    this.dropzone.destroy();
}
```

**Comment by rowanwins** [comment]
In version 3 I will include a prop that lets people set whether the dropzone will be destroyed or not when the component is removed.

**Comment by juanledesma** [comment]
good afternoon, is there a way to stop this event?

Thank you

**Comment by intergalactisch** [comment]
Any updates on this?

**Comment by DjeeBay** [comment]
Hi,

For those who are looking for this, you can add the prop destroyDropzone to avoid the call of destroy :
`
<vue-dropzone :destroy-dropzone="false" ...>
`

**Comment by someone83474** [comment]
It is actually "destroyDropzone" (w/o the dash), see: https://rowanwins.github.io/vue-dropzone/docs/dist/#/props

**Comment by DjeeBay** [comment]
> It is actually "destroyDropzone" (w/o the dash), see: https://rowanwins.github.io/vue-dropzone/docs/dist/#/props

Nope, by convention you declare your props with camelCase (JS convention) and use them in template with kebab-case (HTML convention)
