### ISSUE TITLE
Event for selecting Thumbnail

### ISSUE THREAD

**Issue by ripers** [rowanwins/vue-dropzone#216]
Hi, I have tried to find a select thumbnail event in vue-dropzone (which by the way is great); but haven't found it. Will it be added?

I.E: Would be nice if I could do something like this:

```
<dropzone .....
	v-on:vdropzone-thumbnail-select="selectThumbnail">
	<!-- Optional parameters if any! -->
	<input type="hidden" name="token" value="xxx">
</dropzone>

methods: {
	selectThumbnail(file) {
		// some logic
	}
}
```

Thanks.

EDIT: Fixed some typos.

**Comment by rowanwins** [comment]
Hi @ripers 
When you say 'select thumbnail' what exactly you mean?

Cheers

**Comment by ripers** [comment]
Hi rowanwins, first thanks for the reply.

What I mean is:
Dropzone has lots of nice events:
- vdropzone-file-added(file)
- vdropzone-success(file, response)
- vdropzone-removed-file(file, error, xhr)
- ... and so on.

What would be nice is to also have an event that is something like this:
- vdropzone-select-file(file) -> called when the user clicks on a thumbnail in the dropzone.

To elobarate what I'm trying to accomplish: When the user clicks a thumbnail in dropzone, I need to show some fields outside the Dropzone where the user can fill in some metadata about the selected uploaded picture (title, description, etc) and then click save. These metadata will then be stored in the database along with the image and will later be displayed in a seperate gallery.

Hope this makes things a bit clearer.

Thanks

ripers

**Comment by rowanwins** [comment]
Hey @ripers 

Yeah that makes more sense, thanks!

Unfortunantly doesnt have any native events to handle that but I think you should be able to do something like
````
<dropzone v-on:vdropzone-file-added="attachListener">

methods: {
    attachListener: function (file) {
        file.previewElement.addEventListener("click", function() {
             showSomething()
        })
   }
}
````
Does that make sense?

**Comment by ripers** [comment]
I will try that and let you know how it goes. Thanks @rowanwins !

**Comment by rowanwins** [comment]
Awesome, glad it worked @ripers !
