### ISSUE TITLE
Question: Drag and drop support for sorting?

### ISSUE THREAD

**Issue by ripers** [rowanwins/vue-dropzone#219]
Hi just have a small question: do you have any plans to add drag and drop support for dropzone? 

Regards ripers

**Comment by rowanwins** [comment]
Hi @ripers 

Unfortunately not any time soon, to be honest that functionality has never crossed my mind. 
Having said that we'd be open to contributions if anyone wanted to have a go implementing it :)

**Comment by rowanwins** [comment]
I'm going to close this issue because I have no intentions of pursuing it, as mentioned above if someone in the community would like to tackle it they are welcome
