### ISSUE TITLE
Can't handle vdropzone-sending

### ISSUE THREAD

**Issue by pwnz22** [rowanwins/vue-dropzone#22]
I'm trying to  use the `vdropzone-sending` event but it's not making sense. Or it's not working now?

**Comment by pwnz22** [comment]
Needed to bundle and then use.

**Comment by rowanwins** [comment]
Ah thanks for reporting this, yes the latest code base needs to be built and released to non

Cheers

**Comment by miloandco** [comment]
@rowanwins  Could you please release it to NPM? I need the sending event badly :-)

**Comment by rowanwins** [comment]
Hi @miloandco , I've just updated npm the new version is 2.1.3

**Comment by miloandco** [comment]
Awesome, thanks @rowanwins
