### ISSUE TITLE
Tooltip prevent Remove button to be clicked

### ISSUE THREAD

**Issue by FrancescoMussi** [rowanwins/vue-dropzone#221]
When I reached the file limit - the tooltip with the error message is displayed.

The problem is that its positioning prevent the `remove` button to be clicked.

![screen shot 2017-10-24 at 16 43 57](https://user-images.githubusercontent.com/5312907/31947079-31eeafb6-b8dc-11e7-8e1f-b143e276710a.png)

A workaround was to modify the top position of the `dz-error-message` class:

```
.dropzone .dz-preview .dz-error-message {
  top: 80px!important;
}
```

Only then I am able to click on the remove button:

![screen shot 2017-10-24 at 16 43 08](https://user-images.githubusercontent.com/5312907/31947190-66f8c912-b8dc-11e7-9e63-be65cd63269e.png)

It happened only to me?
What do you think about changing it in the repository?

**Comment by vrajroham** [comment]
@FrancescoMussi Current version has this issue. Version 3 of this library is almost completed and this issue is addressed and resolved there. Stay tuned or see PR https://github.com/rowanwins/vue-dropzone/pull/205 for release of major updated version.

**Comment by FrancescoMussi** [comment]
Great, thanks!
