### ISSUE TITLE
Keep getting a bunch of errors while compiling template

### ISSUE THREAD

**Issue by luke-hawk** [rowanwins/vue-dropzone#226]
I'm having troubles to get vue-dropzone up and running. I imported and registered the component exactly the way suggested and like I've done many times before in my application. However, I keep getting Errors, that I've never seen before: 

**First error** (found in the dropzone component): 
"[Vue warn]: You are using the runtime-only build of Vue where the template compiler is not available. Either pre-compile the templates into render functions, or use the compiler-included build"

**Second error** (also found in the dropzone component):
"[Vue warn]: Error in mounted hook: "Error: Invalid dropzone element.""

**Third error**
"Error: Invalid dropzone element."

It seems like the component is not compiled or registered properly, but I really don't know why. Like I said, I've registered the component just like any other Vue component, I've double checked everything and even removed and added the module again with yarn. 

Any ideas what the issue could be? 

I might need to add, that I'm using webpack

**Comment by vrajroham** [comment]
@luke-hawk It's really weird that you got this issue. Previously some users encountered same issue, please refer #200 #68 #32. Yet we didn't found the cause of it, till then you can go through previous issue workarounds.

**Comment by vrajroham** [comment]
@luke-hawk Glad it helped you. Yes styling issue may be caused due to workaround. We have completely re-written the newer version of this component. Soon new version will be launched and hope you don't get this issue there. Feel free to take look at #205 for new features, fixes and improvements.
