### ISSUE TITLE
language object is not reactive

### ISSUE THREAD

**Issue by Artem-Schander** [rowanwins/vue-dropzone#228]
I have a multi language app. So the user can switch the language, which updates the locale in the store.
Then the language object is getting redefined via computed.
```
computed: {
     dropzone() {
        return {
            language: {
                dictDefaultMessage: translate('company.logoDropzoneDefaultMessage'),
                dictFallbackMessage: translate('dropzone.fallbackMessage'),
                dictFallbackMessage: translate('dropzone.fallbackText'),
                dictFallbackMessage: translate('dropzone.fileTooBig'),
                dictFallbackMessage: translate('dropzone.invalidFileType'),
                dictFallbackMessage: translate('dropzone.responseError'),
                dictCancelUpload: "✕",
                dictFallbackMessage: translate('dropzone.cancelUploadConfirmation'),
                dictRemoveFile: "✕",
                dictFallbackMessage: translate('dropzone.maxFilesExceeded'),
            }
        }
    },
}
```

Expected behaviour:
The translated content shows up in the dropzone view

Actual behaviour:
In the Vue-Dev-Tools I can see the changes but the dropzone view is not getting rerendered.

**Comment by vrajroham** [comment]
@Artem-Schander I need some more details. Set `ref` attribute on your component to `myVueDropzone` or ignore if you already have. Print the language after mounting the component as  `console.log(this.$refs.myVueDropzone.options.language)`. Provide me output and verify your message is being translated.

**Comment by Artem-Schander** [comment]
there is no options in the `this.$refs.myVueDropzone` object ..

![dropzone-language-reactivity-bug](https://user-images.githubusercontent.com/1243826/32068139-af3b78f0-ba85-11e7-88c1-a51e73b01d1e.gif)

**Comment by vrajroham** [comment]
@Artem-Schander Thanks for detailed **gif**. It seems that message is not changing/rendering . We will look into it!

**Comment by rowanwins** [comment]
Hi @Artem-Schander 

Unfortunately you are correct the message is not reactive, this is an upstream issue with dropzone. I'd suggest using regular javascript to target the class `.dz-message` and changing it manually. I'm closing the issue but if you need further assistance with this let us know.

**Comment by Artem-Schander** [comment]
@Fusseldieb 
I have no idea which page you visited. The project you see in the gif is a Web-To-Print tool and it's only accessible for the staff. See https://wtp.polytex.gmbh/
