### ISSUE TITLE
Docs not working

### ISSUE THREAD

**Issue by vrajroham** [rowanwins/vue-dropzone#235]
Docs automatically stopped working unexpectedly. Nothing was updated on repo.

**Comment by vrajroham** [comment]
Initially it seems issue of github (maybe).
If link is provided without `index.html` then it wont work.

Not working -> https://rowanwins.github.io/vue-dropzone/docs/dist/
Working -> https://rowanwins.github.io/vue-dropzone/docs/dist/index.html

**Comment by vrajroham** [comment]
@rowanwins I don't have permission to change the repository description. There's a demo link, please update it if issue is not solved.

**Comment by vrajroham** [comment]
@rowanwins It's automatically working now! Strange 👻 !
Also I observed that github pages are loaded from `master` branch.

**Comment by rowanwins** [comment]
Bizarre!
