### ISSUE TITLE
Notification: Uploader implementation

### ISSUE THREAD

**Issue by alexsasharegan** [rowanwins/vue-dropzone#236]
I just wanted to share a TS/Vue port of Dropzone.js that I wrote over the last couple of months. The lib is not a wrapper to Dropzone, but a fork & full rewrite to Vue.js in Typescript/ES6. It currently runs in production at [ArtisanHD](https://artisanhd.com/secure/uploadconfigure) _(a site for consumers to upload photos and print on demand)_.

I share this mostly in the event you ever need tighter integration with Vue features or the bonus of typings. This might be advantageous for some of the nice addons you've built. Feel free to close this issue at your convenience.

**Vue Transmit:** [https://github.com/alexsasharegan/vue-transmit](https://github.com/alexsasharegan/vue-transmit)

**Comment by rowanwins** [comment]
Hi @alexsasharegan 

Thanks for sharing your work, that's really cool! When I initially started this project I was just going for a very light-weight integration, I never envisaged that this component would've been as popular as it has. It's great to see someone tackle it in a more holistic manner.
