### ISSUE TITLE
manuallyAddFile

### ISSUE THREAD

**Issue by satrong** [rowanwins/vue-dropzone#237]
https://github.com/rowanwins/vue-dropzone/blob/e01c5bc4aa32bf202631161647f277b0118b728e/src/components/vue-dropzone.vue#L62

I think it should like blow:
```js
fileUrl && this.dropzone.emit("thumbnail", file, fileUrl);
```
if the `file` is not an image file, after manually add file, the display will be incorrect.

**Comment by rowanwins** [comment]
Good pickup thanks @satrong . Feel free to send through a pull request otherwise I'll try to find time to incorporate it.
