### ISSUE TITLE
vue-dropzone CDN

### ISSUE THREAD

**Issue by nam-co** [rowanwins/vue-dropzone#24]
Hi, I was wondering how can I use it with out using npm to install, what files do I need to include and if theres a way to get them in a cdn?

Appreciate any help

regards

**Comment by rowanwins** [comment]
I think you can probably use something like rawgit to serve the dist file if you just want to include it via a script tag
eg https://cdn.rawgit.com/rowanwins/vue-dropzone/vue2/dist/vue2-dropzone.js
