### ISSUE TITLE
Images appear rotated

### ISSUE THREAD

**Issue by mrchimp** [rowanwins/vue-dropzone#245]
Due to EXIF data, uploaded images can appear rotated or flipped differently to how they appear on a user's device. This can be corrected server side quite easily but will look incorrect in the dropzone. Is there a way around this?

**Comment by rowanwins** [comment]
Hi @mrchimp 

You could probably hook into a third party library like [exif-js](https://github.com/exif-js/exif-js) and use an event like `vdropzone-file-added` to interrogate and adjust the image accordingly. It's probably beyond the scope of us doing it in the core of vue-dropzone but hopefully that gives you enough of an idea. 
Cheers

**Comment by tomoyuki28jp** [comment]
Anybody has accomplished this?

**Comment by biancaro** [comment]
I solved this by 

- installing exif.js 
- import it into my vue file
- create a global variable EXIF (accessible by all components as well as by vue-dropzone)

npm i exif-js

`import EXIF from 'exif-js/exif';
`window.EXIF = EXIF;`
