### ISSUE TITLE
maxFilesize is not respecting size of all files

### ISSUE THREAD

**Issue by Fohlen** [rowanwins/vue-dropzone#248]
In our setup maxFilesize is not respecting the size of all files but individually ones. Neither does it prevent from adding new files, when the limit exceeded.
Unfortanly, due to #247 it's pretty hard to present an out-of-the-box version on JSfiddle.
I tried to reproduce this with pure `dropzone`, and it didn't show this behavoir, so I suspect, `vue2-dropzone` is the issue here. Any clues?

**Comment by rowanwins** [comment]
I presume you're using version 3 of `vue-dropzone`? Version 3 should not differ at all the pure dropzone...

Having said that my understanding was `maxFilesize` related to an individual upload, eg a single file must be less than 1MB, this should be very easy for you to test.

If you wanted to control the size limit of all uploads I'd probably try and hook into one of the events
````
<vue-dropzone v-on:vdropzone-sending="sending">
    
data () {
   return {
      totalsize: 0
   }
},
methods: {
      sending(file, xhr) {
         this.totalsize = this.totalsize + file.size
         if (this.totalzize > someLimit) xhr.abort()
      }
    }
````
This is completely untested, but hopefully it gives you a few ideas.

**Comment by Fohlen** [comment]
@rowanwins thanks. apparently this really isn't a vue-dropzone error. Strange enough that this worked a before upgrading to the v3 branch. Maybe the dropzone behavoir changed here.
