### ISSUE TITLE
vdropzone-queue-complete not been fired

### ISSUE THREAD

**Issue by diegomengarda** [rowanwins/vue-dropzone#249]
Hello,
I am trying to use the vdropzone-queue-complete event to check when my list of files completes but is not firing the event.

```
<script>
  import vue2Dropzone from 'vue2-dropzone'

  export default {
    components: {
      vue2Dropzone: vue2Dropzone
    },
    methods: {
      onDropzoneSending (file, xhr, formData) {
        formData.append('owner_id', this.form.id)
        formData.append('owner_type', 'section')
      },
      onSendImages () {
        this.$refs.dropzone.processQueue()
      },
      onDropzoneUploadComplete (file, xhr, formData) {
        console.log('Complete queue')
      }
    }
  }
</script>

<template>
    <div>
        <vue-2-dropzone ref="dropzone"
                        id="dropzone"
                        :options="dropzoneOptions"
                        v-on:vdropzone-sending="onDropzoneSending"
                        v-on:vdropzone-queue-complete="onDropzoneUploadComplete"></vue-2-dropzone>
        <el-button type="primary"
                   @click="onSendImages">Send
        </el-button>
    </div>
</template>

```

Is there something wrong with my code?

Thanks.

**Comment by rowanwins** [comment]
Hi @diegomengarda 

`vdropzone-queue-complete` is only fired when you set the `autoProcessQueue` option to false and you manually trigger the `processQueue` method yourself.

The more relevant event for you is `v-dropzone-complete`, this fires when the upload is completed or errors

**Comment by diegomengarda** [comment]
But how can i check when all files has been uploaded ?
This event is fired to every file...

**Comment by rowanwins** [comment]
Hi @diegomengarda 

Sorry for the slow reply, can you show me your `options` object?

**Comment by vaniyokk** [comment]
Same issue. Note that in latest version event name is **vdropzone-queuecomplete**, and in docs there it is not mentioned. 

```
name:"vdropzone-queuecomplete"
type:"$emit"
source:"<Dropzone>"
payload:Array[0]
```

You need to listen  **vdropzone-queuecomplete** instead of **vdropzone-queuecomplete**
Please upgrade docs!

**Comment by vrajroham** [comment]
@vaniyokk Sorry for inconvenience caused. Actually it is `vdropzone-queue-complete` only. We had a  typo previously in event. But in latest release it's resolved now. It's **vdropzone-queue-complete** only.

**Comment by vrajroham** [comment]
@diegomengarda Try upgrading to latest version, hopefully it will be resolved and event ill be emitted.
