### ISSUE TITLE
seems we can't have more than one instance of the component

### ISSUE THREAD

**Issue by estrica2000** [rowanwins/vue-dropzone#25]
Uncaught Error: Dropzone already attached.
    at new t (eval at <anonymous> 

Is it possible to change this? 
Many thanks

**Comment by rowanwins** [comment]
I've just tested and having it twice is fine, just make sure each instance has a unique `id`

So for example 
````
    <dropzone id="myVueDropzone" url="https://httpbin.org/post"></dropzone>
    <dropzone id="myVueDropzone2" url="https://httpbin.org/post"></dropzone>
````

Reopen the issue if you continue to run in to problems

**Comment by estrica2000** [comment]
thank you!

**Comment by thijs95** [comment]
@rowanwins 
Hi,

This is exactly what I need, but I add the component after a button click event.

I have a parent component that has an array of a child component. That child component uses the dropzone.
In my parent I start with 0 child components, and I append the child component after the button click event.
When I add the first instance of the child component the dropzone is also added, but when I add the second instance the id obviously stays the same. At that moment i get this error: [Vue warn]: Error in mounted hook: "Error: Dropzone already attached."
Do you have any idea how I can change the id of the dropzone at the moment I add the child component?
I've seached for an answer but I can't find anything specific for my problem.

**Comment by rowanwins** [comment]
Hi @thijs95 

Can you post a snippet of your current setup. 

Thanks

**Comment by thijs95** [comment]
Here u go

Parent Template<template>
    <div>

        <div class="panel">

            <div class="panel-heading">
                <h1 class="panel-title">Textueel+</h1>
            </div>
            <div class="panel-body">

                <div class="form-group" id="app">
                    <div v-for="(n, idx) in textualplusitems">
                        <create-textualplusitem :index="idx" @textualChanged="onChange"></create-textualplusitem> 
                        <br>
                        <hr>
                    </div>
                </div>

                <button @click="add">Extra Textual+</button>
            </div>

        </div>

        <div class="form-group">
            <button @click="postSlideshowplus">Save</button>
        </div>
</template>
Parent script
<script>

    export default {

        data: function(){
            return {
                name: "",
                textualplusitems: [],
            }
        },

        methods:{
            add(){
                this.textualplusitems.push({}); // Here I add a new instance of the child component
            },

            postSlideshowplus(){
                this.$http.post('/api/slideshowplus', this.newSlideshow)
                    .then(function () {
                        this.$toasted.success('Item is aangemaakt', {
                            duration: 2000,
                            action: {
                                text: 'Oke',
                                onClick: (e, toast) => {
                                    toast.goAway(0);
                                }
                            }
                        });
                    });

            },

            onChange(data){
                this.textualplusitems[data.idx] = data.textual;
            },
        },
        mounted: function(){
            //
        },

        computed: {
            newSlideshow(){
                return {
                    name: this.name,
                    textualplusitems: this.textualplusitems,
                }
            }
        }
    }

</script>
Child Template
<template>
    <div>
        <div class="form-group">
            <label for="title">Title</label>
            <input id="title" v-model="title" name="title" class="form-control" autocomplete="off">
        </div>

        <div class="form-group">
            <label for="text">Text</label>
            <quill-editor id="text" :options="editorOption" v-model="text"></quill-editor>
        </div>

        <div class="form-group">
            <label for="imageUploader">Photo:</label><br>
            <dropzone id="imageUploader" url="/api/image" v-on:vdropzone-success="imageUploaded"></dropzone> 
        </div>
    </div>
</template>
Child Script
<script>

    import Dropzone from 'vue2-dropzone'

    export default {
        components: {
            Dropzone
        },

        props: {
            index: {
                type: Number,
                default: -1
            }
        },

        data: function(){
            return {
                title: "",
                text: "",
                image_url: null,
                editorOption: {
                    modules: {
                        toolbar: [
                            ['bold', 'italic', 'underline', 'strike'],
                            [{ 'list': 'ordered'}, { 'list': 'bullet' }],
                            [{ 'size': ['small', false, 'large', 'huge'] }]
                        ]
                    }
                }
            }
        },

        methods:{
            imageUploaded(file, response){
                this.image_url = response.url;
            }
        },

        mounted: function(){
            //
        },

        computed: {
            newTextual(){
                return {
                    title: this.title,
                    text: this.text,
                    photo_url: this.image_url,
                }
            }
        },

        watch: {
            newTextual(changedTextual){
                let data = {
                    idx: this.index,
                    textual: changedTextual
                }
                this.$emit('textualChanged', data)
            }
        }
    }

</script>

Thanks for the reply
