### ISSUE TITLE
'method'  not in the props, cannot configure it 

### ISSUE THREAD

**Issue by Hardcore0331** [rowanwins/vue-dropzone#251]
Cannot configure 'method',  i want to change the request method to 'put', but 'method' not in the props

Thank you.

**Comment by vrajroham** [comment]
Provide your component snippet how are you doing.

**Comment by rowanwins** [comment]
It should go in the `options` prop if I understand you correctly

**Comment by Hardcore0331** [comment]
It seems that it is not in the options?  (\node_modules\vue2-dropzone\src\index.vue)
![image](https://user-images.githubusercontent.com/6450216/32707374-608832f2-c85e-11e7-83ba-101ad7ca1762.png)

**Comment by rowanwins** [comment]
Ah you should update to the latest version of this component, version 3 is an entire rewrite and supports all props.

**Comment by Hardcore0331** [comment]
Thanks for your time.
