### ISSUE TITLE
vdropzone-queue-complete is actually vdropzone-queuecomplete

### ISSUE THREAD

**Issue by stoked74** [rowanwins/vue-dropzone#252]
The docs state that the queue complete event is vdropzone-queue-complete, but the event that's being fired is named vdropzone-queuecomplete

**Comment by vrajroham** [comment]
@stoked74 Thanks for pointing the issue. It seems that we had a typo on [this](https://github.com/rowanwins/vue-dropzone/blob/master/src/components/vue-dropzone.vue#L300) line. Soon it will be updated in next release.
