### ISSUE TITLE
Cannot append to formData using sendingEvent

### ISSUE THREAD

**Issue by hanxue** [rowanwins/vue-dropzone#255]
vue2-dropzone: 2.3.6
vue: 2.3.4

I have the following Vue HTML code

```html
<vue-dropzone ref="myVueDropzone" id="dropzone" :options="dropzoneOptions"
              v-on:vdropzone-file-added="fileAdded" v-on:vdropzone-sending="sendingEvent">
              </vue-dropzone>
```

and the Javascript

```javascript
export default {
  components: {
    vueDropzone: vue2Dropzone
  },
  data () {
    return {
      message: '',
      uploadFilename: '',
      dropzoneOptions: {
        url: 'http://' + this.$root.settings.get('Backend.host') + ':' + 
          this.$root.settings.get('Backend.port') +
          '/submit/shot_version',
        maxFilesize: 100,
        headers: {'Authorization': 'Bearer ' + localStorage.getItem('access_token')},
        dictDefaultMessage: '<h2><i class="md-icon md-theme-default material-icons">file_upload</i> Click here to add file</h2>'
      },
    }
  },
  methods: {
    fileAdded: function (file) {
      this.message = 'Added file ' + file
      this.$refs.snackbar.open()
    },
    sendingEvent: function (file, xhr, formData) {
      console.log('DEBUG: formData BEFORE ' + JSON.stringify(formData))
      formData.append('shot_id', this.$route.query.shot_id)
      formData.append('staff_id', this.$store.state.staff_id)
      formData.append('shot_status_id', this.$route.query.shot_status_id)
      formData.append('shot_stage_id', this.$route.query.shot_stage_id)
      formData.append('review_time', (new Date()).toISOString())
      formData.append('shot_version_review_path', 'O:\\check\\animation\\supervisor\\')
      formData.append('shot_version_name', 'File_whatever_V999.mov')
      console.log('DEBUG: POST-ing the following form data ' + JSON.stringify(formData))
      this.message = 'Sending files to = server'
      this.$refs.snackbar.open()
    } 
  },
}
```

When I select a file, I get the following browser console output:

```
DEBUG: formData BEFORE {}
DEBUG: POST-ing the following form data {}
```

Why is it that `formData` is empty even after I append to it? How can I append to the formData?

The receiving server confirm that the expected JSON parameters in the Request body did not exist.

**Comment by hanxue** [comment]
Even though the browser console shows empty result, I can somehow get the request parameters as `<form>` body. Is there a way to send those parameters as JSON?

**Comment by rowanwins** [comment]
Mmm i haven't seen anything documented anywhere for dropzone, there is a slightly limited ability to hook into those xhr events.

To view your form data contents try something like 
````
for (var pair of formData.entries()) {
    console.log(pair[0]+ ', ' + pair[1]); 
}
````
Taken from https://stackoverflow.com/questions/17066875/how-to-inspect-formdata
I just googled `view form data js `

Not sure I can help you much more sorry, I'd just be doing random googling like you.  If you come across anything feel free to drop a note here and we can update the docs.

**Comment by hanxue** [comment]
Thanks @rowanwins , the solution does work. So using `formData.entries()` instead of `JSON.stringify(formData)` 👍

**Comment by Timibadass** [comment]
Is there any way to group the data formData takes in?
something like 
`let data = {};
formData.append(data)`

**Comment by youngquarshie** [comment]
Just do this

you will be able to get all the input fields in an array

init: function() {
  this.on("sending", function(file, xhr, formData) { 

    //formData.append('task_name', jQuery('#task_name').val());

    $("form").find("input").each(function(){
      formData.append($(this).attr("name"), $(this).val());
  });
  
  });

}

**Comment by youngquarshie** [comment]
init: function() {
  this.on("sending", function(file, xhr, formData) { 

    //formData.append('task_name', jQuery('#task_name').val());

    $("form").find("input").each(function(){
      formData.append($(this).attr("name"), $(this).val());
  });
  
  });

}
