### ISSUE TITLE
Intercept request and responses

### ISSUE THREAD

**Issue by Al3xR0** [rowanwins/vue-dropzone#259]
I am using JWT token with a refreshing option, so this means that the used token will be blacklisted. In my app I'm using axios, and I can intercept all requests and responses and I can update the token with the latest.

How can I do the same for vue-dropzone, how can I intercept requests and responses? I saw that you removed the axios dependency.
Right now I am adding the JWT token into the `dropzoneOptions.headers`, but this needs to update on every request, and also need to retrieve the new token on every response.

**Comment by rowanwins** [comment]
Hi @Al3xR0 

I'd probably look at hooking into the sending event
````
<vue-dropzone v-on:vdropzone-sending="sendingEvent"> </vue-dropzone>

    methods: {
      sendingEvent (file, xhr, formData) {
        xhr.setRequestHeader('SomeHeader', someToken)
      }
    }
````

Hope that helps

**Comment by rowanwins** [comment]
Alternatively you could call the `.setOption` [method](https://rowanwins.github.io/vue-dropzone/docs/dist/#/methods) every time you get a new token.

**Comment by Al3xR0** [comment]
@rowanwins Thank you for the reply. I actually found that I can get the response on ```vdropzone-success``` and by using ```file.xhr.getResponseHeader('foo')```, so this is how I can update the token got from the response.

**Comment by rowanwins** [comment]
Hi @Al3xR0 

Does something like this work?
````
<vue-dropzone ref="myVueDropzone" v-on:vdropzone-success="successEvent"> </vue-dropzone>

    methods: {
      successEvent (file) {
        var newToken = file.xhr.getResponseHeader('foo')
        this.$refs.myVueDropzone.setOption('headers', {foo: newToken })
      }
    }
````
