### ISSUE TITLE
Upload progress calculating in chunk mode

### ISSUE THREAD

**Issue by de-soul** [rowanwins/vue-dropzone#262]
When i try to upload a big file in chunk mode, dropzone calculating upload progress not correct. My chunk size is 1048576 bytes and on every chunk complete upload progress is set to 100%. Example progress: 1% -> 2% -> 3% -> 100% -> 4% -> 5% ... This is a bug or did you found a solution?

**Comment by vrajroham** [comment]
Hi @de-soul ,

Actually this issue has nothing to do with this wrapper/component. This issue/behaviour is as per the base/core dropzone library only. For more information related to this see [this issue on base dropzone library](https://gitlab.com/meno/dropzone/issues/54)

---

Below link may help you, if you wish to implement custom progress bar enabling chunking.
http://www.dropzonejs.com/#event-totaluploadprogress
