### ISSUE TITLE
Changing thumbnail after event 'vdropzone-file-added'

### ISSUE THREAD

**Issue by PsySolix** [rowanwins/vue-dropzone#263]
Hi there! Loving the plugin but I'm having a bit of difficulty with changing the thumbnail on event 'vdropzone-file-added'.

So event triggers fine, then I try to change the thumbnail with : 
`this.$refs.hroVueDropzone.$emit('thumbnail', file, 'http://placehold.it/500x500');`

context: 
`<vue-dropzone
				ref="hroVueDropzone"
				id="dropzone"
				:options="dropzoneOptions"
				v-on:vdropzone-success='fileUploaded'
				v-on:vdropzone-file-added='changeThumbnail'></vue-dropzone>`

But nothing happens! Am I doing something wrong? 
If I use the emit. (without $) it says undefined method.. So I figured I needed to use the Vue $emit? 

Thanks in advance! :)

**Comment by rowanwins** [comment]
Hi @PsySolix

It looks like you are ring to emit an event down to the child component, is that correct? Unfortunatly you can't do that, only parent components can listen for event from children.

You should however be able to call the method directly using
`this.$refs.hroVueDropzone.methods.'thumbnail(file, 'http://placehold.it/500x500')`

Hopefully that helps

**Comment by PsySolix** [comment]
Hi rowan! 

Thanks I will try this :)

**Comment by PsySolix** [comment]
Hi Rowan, I tried this but **.methods** is undefined on the ref. 
I fixed it in a different way:
`file.previewElement.childNodes[1].children[0].setAttribute('src', this.bestandAfbeelding);`
