### ISSUE TITLE
how to change message after mounted?

### ISSUE THREAD

**Issue by chairman-nirvana** [rowanwins/vue-dropzone#264]
We're using vue-dropzone and vue-i18n, but found that it's difficult to change texts like dictDefaultMessage after events like user changes language. 

How to resolve that? Thanks

**Comment by rowanwins** [comment]
Hi @chairman-nirvana 

Unfortunately the language options are not reactive, this is an upstream issue with dropzone. I'd suggest using regular javascript to target the class .dz-message and changing it manually. The only other option I can think of would be destroy the component and remounting it with the new language settings which might be a bit painful.

I'm going to close this issue as there is not much we can do sorry.

**Comment by kalnode** [comment]
Has there been any update on this?
