### ISSUE TITLE
Custom headers for URL signing URL not working

### ISSUE THREAD

**Issue by gborcherds** [rowanwins/vue-dropzone#266]
Hi there,

I see that the prop awss3 has to properties, signingURL and headers. I see in your code that you are using the headers to add custom headers to the request, but it's not working. The headers aren't being added that I'm passing to that prop. I need this to work to add some CSRF tokens to the request. 

Any thoughts on why it's not working?

**Comment by rowanwins** [comment]
hi @gborcherds 

Are you uploading to S3 or just via a regular REST endpoint? What version of the component are you using? Can you show us your config?

Thanks

**Comment by gborcherds** [comment]
Version 3.

```javasciprt
dropzoneOptions: {
                    url: '/api/file/addFile',
                    thumbnailWidth: 200,
                    addRemoveLinks: true,
                    dictDefaultMessage: "<i class='fa fa-cloud-upload'></i>Drag and Drop to Upload",
                    autoProcessQueue : false,
                    headers : {
                        'X-XSRF-TOKEN': document.head.querySelector('[name="token"]').content
                    }
                },
awss3: {
          signingURL : '/api/file/signed-url',
headers : {
{
                        'X-XSRF-TOKEN': document.head.querySelector('[name="token"]').content
                    }
        }
```

I'm then passing in those values into the props. The header argument works great for the actual dropzone upload at the end to my server, but the header isn't passed on the signing request.

Something to keep in mind, it might be better to switch the upload of the S3 file to be handled by dropzone, then send one final request to your own server with an array of all the files. The frustration I had in trying to do the S3 upload was that many of the options available in dropzone are not available to me on the s3 upload because you are doing it all custom without a lot of the same hooks.

For example, I can't change the path of the upload on the S3. I don't want to load my files into the root of the bucket, but want to specify a path. Which is typically done by setting the key in the json request that you have, but I couldn't get that to set either, even when I passed a json object that had the key value set to the path I wanted.

Anyway, for the original issue, I need to be able to add the token to the request for security, but passing in the header object as shown above is not working. What is weird, is I clearly see the foreach loop through that object in your URL signer file, but when I look at the compiled code, it's not in there.

**Comment by rowanwins** [comment]
Hi @gborcherds 

Hmmm, looking at your snippet above are your headers nested too deeply?
````
awss3: {
          signingURL : '/api/file/signed-url',
          headers : {
             'X-XSRF-TOKEN': document.head.querySelector('[name="token"]').content
          }
}
````
@vrajroham may be able to provide more details as he wrote this bit of functionality, Im not very familiar with it.

**Comment by vrajroham** [comment]
@gborcherds Apologize for inconvenience!  
> What is weird, is I clearly see the foreach loop through that object in your URL signer file, but when I look at the compiled code, it's not in there.

This is because your downloaded version(3.0) dosen't contain implementation of headers functionality, because this contribution was added later to component and yet not released.

---

> The frustration I had in trying to do the S3 upload was that many of the options available in dropzone are not available to me on the s3 upload because you are doing it all custom without a lot of the same hooks.

We have implemented it custom because, dropzone itself doesn’t have feature to upload files directly to s3. This is add-on feature added to this `vue2-dropnzone` component.

---

> I can't change the path of the upload on the S3. I don't want to load my files into the root of the bucket, but want to specify a path. Which is typically done by setting the key in the json request that you have, but I couldn't get that to set either, even when I passed a json object that had the key value set to the path I wanted.

Actually this is the known issue. We shipped this feature in recent release of `3.0` and have some issues which needs to fixed. Everyone is full-time developers so, we get little time to work on it you know! :smiley: 

---

@gborcherds We apologize for this issue. Mean time I'm releasing updated version and hopefully your header related issue get's resolved. And we will try to to fix `key(s3 object location)` related issue ASAP.

I'll update here once new release is published.

**Comment by vrajroham** [comment]
@gborcherds I have published latest tag on npm. You can track changes in  [tag v3.0.1](https://github.com/rowanwins/vue-dropzone/releases/tag/v3.0.1). 

Let me know about your issue once update!

Thanks

**Comment by gborcherds** [comment]
Thanks @vrajroham everything is working as expected now. If I could suggest a feature improvement, it would be great if we could also add the ability to send parameters to the server with the url signing request. I can do a PR for this if you'd be willing to accept it. But the initial issue is resolved perfectly.

**Comment by vrajroham** [comment]
@gborcherds Glad you resolved the issue! 
Sure you can suggest the PR and why would we regret to accept it? Always welcome, this is how the component has grown!
