### ISSUE TITLE
dropzone dependency

### ISSUE THREAD

**Issue by nise** [rowanwins/vue-dropzone#269]
I am new to vue, but how can I use vue2dropzone in umd? I get this error:
```

[Vue warn]: Error in mounted hook: "Error: Module name "dropzone" has not been loaded yet for context: _. Use require([])
http://requirejs.org/docs/errors.html#notloaded"

found in

---> <VueDropzone>
       <Root>
```

**Comment by rowanwins** [comment]
Can you provide more context as to how you are using this component? Can you provide a fuller snippet of your setup?

**Comment by rowanwins** [comment]
Closing to to inactivity
