### ISSUE TITLE
dropzone not defined

### ISSUE THREAD

**Issue by packytagliaferro** [rowanwins/vue-dropzone#27]
I am using this via a cdn and on one page in my Laravel app but I get the error: `media:149 Uncaught ReferenceError: Dropzone is not defined` is this setup right? 

```
<div id="user-upload-media">

    <h2></h2>

    <dropzone id="myVueDropzone" url="https://httpbin.org/post" v-on:vdropzone-success="showSuccess"></dropzone>

  </div>

  <script type="text/javascript" src="https://cdn.rawgit.com/rowanwins/vue-dropzone/vue2/dist/vue2-dropzone.js"></script>
  <script type="text/javascript">
    
    jQuery(document).ready(function($) {

      var vm = new Vue({
        el: '#user-upload-media',
        data: function() {
        },
        components: {
          'Dropzone': Dropzone,
        },
        mounted: function(){
        },
        methods:{
          showSuccess: function (file) {
            console.log('A file was successfully uploaded')
          }
        }

      });


    });

  </script>
```

**Comment by rowanwins** [comment]
Hmmm @packytagliaferro unfortunantly the approach of just pulling it in via a CDN isn't really the best idea, for the purposes of testing you might be able to get away with the following

````
 <script type="text/javascript" src="https://cdn.rawgit.com/rowanwins/vue-dropzone/vue2/dist/vue2-dropzone.js"></script>
  <script type="text/javascript">
    
    jQuery(document).ready(function($) {

      var vm = new Vue({
        el: '#user-upload-media',
        components: {
          'Dropzone': vue2-dropzone,
        },
        methods:{
          showSuccess: function (file) {
            console.log('A file was successfully uploaded')
          }
        }
      });
    });
  </script>
````
By pulling it in via CDN `vue2-dropzone` is exposed as a global variable which you should be able to pull in.

To do things properly you're better off installing modules via npm and using an import statement as per the example, and then using some sort of bundler like webpack or browserify. It's a bit of a daunting process to get started with but I'd suggest looking at something like the Vue [browserify-simple template](https://github.com/vuejs-templates/browserify-simple) and getting a bit of a handle on how it can help manage various dependencies etc.

Good luck
