### ISSUE TITLE
Error in mounted hook: "Error: No URL provided."

### ISSUE THREAD

**Issue by adavie1** [rowanwins/vue-dropzone#274]
Hi, firstly thanks for creating a great Vue module!

Been using this with no issues until the recent upgrade to v**2.3.6**

My HTML code  looks like this:
```
          <dropzone
          :ref="thisRef + 'Ref'"
          :id="thisRef"
          :use-font-awesome="true"
          :url="outputUrl"
          :auto-process-queue="true"
          :maxFileSizeInMB="8"
          :headers="options.headers"
          @vdropzone-success="showSuccess"
          @vdropzone-error="onError"
          :options="options">
          <!-- Optional parameters if any! -->
          <input type="hidden" name="token" value="xxx123">
        </dropzone>
```
The parameter `outputUrl` is a computed value.

The script has the relevant values in the `data () {...}` section.

```
      options: {
        url: this.uploadUrl,
        thumbWidth: 150,
        headers: {
          'Access-Control-Allow-Origin': this.uploadUrl,
          'Access-Control-Allow-Methods': 'GET, POST, OPTIONS, PUT, DELETE',
          'Access-Control-Allow-Headers': 'Origin, X-Requested-With, Content-Type, Accept, X-File-Name, X-File-Size, X-File-Type'
        }
      },

```

Imports as follows: `import Dropzone from 'vue2-dropzone'`

I've tried with and without `:url="outputUrl"` in the component definition, but still no joy.

The docs don't mention the `:options` parameter as required, I only added it after the upgrade when the component stopped working due to errors in the browser console.

**Comment by vrajroham** [comment]
@adavie1 We apologize for inconvenience caused. 

Current component version (3.*)  is completely re-written from scratch to fix issues which were not possible without it. Along with that we added more features to library. Track PR #205 complete for track.  Answering to your question, we have moved all the props to single `:options=` property [see here](https://rowanwins.github.io/vue-dropzone/docs/dist/#/props).

Try setting all your properties in `:option` along with your `url`. 

For Documentation https://rowanwins.github.io/vue-dropzone/docs/dist

Thanks

**Comment by adavie1** [comment]
Thanks. It works now, but I've got issues with Laravel not detecting the file attribute in the request.

**Comment by rowanwins** [comment]
What sort of file attribute do you mean @adavie1 ?

**Comment by adavie1** [comment]
In the file request sent by the component to Laravel. The "file" attribute is not being passed through, so now I'm getting "You did not send to the correct JSON" message because this is a PUT request.

**Comment by vrajroham** [comment]
@adavie1 Have you solved your issue? Please feel free to close this issue if resolved.

**Comment by adavie1** [comment]
Yes, apologies for not closing the issue earlier.
