### ISSUE TITLE
'repository' field missing from package.json

### ISSUE THREAD

**Issue by ajmas** [rowanwins/vue-dropzone#275]
When I view the module on NPM there is no link back to the project. You should probably add the 'repository' field to the `package.json`. See:

https://stackoverflow.com/questions/16827858/npm-warn-package-json-no-repository-field

**Comment by rowanwins** [comment]
Gday @ajmas 

Yeah I noticed that was missing the other day, must've got lost in the v3 upgrade, will add it back in the next release.
