### ISSUE TITLE
Files > 200kb won't upload

### ISSUE THREAD

**Issue by FrancescoMussi** [rowanwins/vue-dropzone#279]
Can you please try to upload any image which size is more that 200kb in your demo:

https://rowanwins.github.io/vue-dropzone/docs/dist/index.html#/demo

(In this case there is a limit for images bigger that 500kb - so the image should be > 200kb and < 500kb )

The upload never really ends.
I have the same exact problem.
I have tried both on localhost, online and on several browsers.

The upload progress actually reach 100 - but somehow it doesn't really upload the image.

Do you have any clue why this is happening?

**Comment by rowanwins** [comment]
I wonder if it's a limit on what https://httpbin.org/ will accept given they provide a free endpoint?
Does seem a bit weird, doubt it's anything to do with this library.

**Comment by FrancescoMussi** [comment]
Yes I agree on all.
- It must be related with https://httpbin.org/.
- It's very weird.
- Shouldn't be related with the library.

Didn't find any warning about it on https://httpbin.org/.
Am I wrong or until few days ago there wasn't this limit...?
Before I could upload files of several MB without any problem.

I was using https://httpbin.org/post as endpoint and then upload the array of images, along with other info, to one single API. 

What can be a replacement for  https://httpbin.org/post ?
It's a simple API that return the file object?

**Comment by FrancescoMussi** [comment]
I checked today and everything works fine as before.
The guys from httpbin say that there was no limit from their side, but maybe something from their platform provider.

In any case I am closing this since it is no longer an issue.
