### ISSUE TITLE
Can't get setOption to do anything...

### ISSUE THREAD

**Issue by pdesmarais** [rowanwins/vue-dropzone#280]
Hi! I'm trying to set the url after the vue-dropzone component has been initialized (using an id that gets passed as a prop to my containing component).

I tried the other ways I saw mentioned in the issues but they don't seem to work for me.

I'm trying to use the .setOption method on the dropzone ref.

This  is the code I have right now (I switched to another option to see if only the URL was causing a problem) :
```
console.log('setting dropzone option')
console.log(this.$refs.myDropzoneInstance.options.maxFilesize)
this.$refs.myDropzoneInstance.setOption('maxFilesize', 10)
console.log('dropzone option set')
console.log(this.$refs.myDropzoneInstance.options.maxFilesize)
```

This is the output I get :
```
setting dropzone option
2
dropzone option set
2
```

My dropzoneOptions are initialized in my container component's data as
```
dropzoneOptions: {
          url: '#',
          thumbnailWidth: 150,
          maxFilesize: 2,
          method: 'put',
          acceptedFiles: 'image/*',
          paramName: 'coverPhoto'
}
```

As you can see, the value doesn't change after calling `setOption`. I've checked with the vue devtools, logged the `this.$refs.myDropzoneInstance` object, nothing has changed...

Am I doing anything wrong?

Thanks!

**Comment by rowanwins** [comment]
Hi @pdesmarais 

I dont think you'll see anything change in the options object, have you tried testing the actual functionality after the setOption operation?

**Comment by pdesmarais** [comment]
Hey @rowanwins !

Thanks for the answer! Yes, you're right. I see that the value is set on the dropzone but not in the options object.

The code functions properly. All's good! :)

Thanks!
