### ISSUE TITLE
How to get all the information of the uploaded file is the file stream

### ISSUE THREAD

**Issue by wa18335782240** [rowanwins/vue-dropzone#281]
It's very urgent. Thank you.

**Comment by wa18335782240** [comment]
I want to get the information of file uploading in PHP and complete the upload function of the file

**Comment by rowanwins** [comment]
Unfortunantly we can't help with that, this is a component for your front-end. If you are using Laravel there are some videos on youtube that might help you such as this https://www.youtube.com/watch?v=T_llnQ72TbE
