### ISSUE TITLE
There is no documentation about vdropzone-complete-multiple event

### ISSUE THREAD

**Issue by maxalmonte14** [rowanwins/vue-dropzone#282]
I'm working with simultaneous file upload, and using Vue devtools I found that an event called `vdropzone-complete-multiple` is fired when you're working with multiple uploads but there is no documentation about it.

By the way, the `vdropzone-complete` event description appears twice in the documentation.

Maybe you made a mistake when was working on the documentation, but it's okay, I think is easy to fix.

![image](https://user-images.githubusercontent.com/12385704/35184927-203aadc0-fdd2-11e7-9967-d098f5f63b6f.png)

**Comment by rowanwins** [comment]
THanks for reporting that @maxalmonte14 , we'll update it when we get a chance.

**Comment by vrajroham** [comment]
@maxalmonte14 Thanks for reporting that. I've added undocumented event `vdropzone-complete-multiple` to docs.
