### ISSUE TITLE
vdropzone-error-multiple is fired once time per file

### ISSUE THREAD

**Issue by maxalmonte14** [rowanwins/vue-dropzone#283]
When you're working with multiple file upload the expected behavior (I think) is to trigger one event when the upload was wrong, but actually the `vdropzone-error-multiple` is triggered once time per file, if you are uploading 10 images at a time, then the `vdropzone-error-multiple` would be triggered 10 times, so if you are catching this errors and showing it in the browser, the total errors would be `errors * image uploaded`, in this example `errors * 10`!

**Comment by rowanwins** [comment]
Hi @maxalmonte14 

Unfortunately that is the default behaviour provided by dropzone.js itself so there isn't much we can do until it is resolved in the parent library. If you'd like to raise an issue in dropzone feel free to do so.
