### ISSUE TITLE
Combine normal form with vue2-dropzone in Rails

### ISSUE THREAD

**Issue by DaniG2k** [rowanwins/vue-dropzone#288]
I'm trying to combine a normal form with vue2-dropzone for a Rails app I'm working on, but I'm slightly confused how to go about this.

Right now, I am creating a Rails form and passing in the data to populate it (if it has fields that are already stored) like this:

```
<%= form_for(listing, html: { id: 'listing_form', data: { listing: listing.to_json } }) do |f| %>
  <%= f.text_field(:name) %>
  <%= f.select(:property_type) %>
  ...
  <vue-dropzone ref="myVueDropzone" id="dropzone" :options="dropzoneOptions">
  </vue-dropzone>

  <%= f.submit 'v-on:click.prevent': 'submitListing' %>
<% end %>
```

As you can see, this form passes html data to pre-populate the form.
I am sending the data with the `submitListing` method which I call in a Vue method:

```
Vue.http.headers.common['X-CSRF-Token'] = document.querySelector('input[name="authenticity_token"]').getAttribute('value');
var listingForm = document.getElementById('listing_form');
var listing = JSON.parse(listingForm.dataset.listing);

const myForm = new Vue({
  el: '#listing-multistep',
  components: {
    vueDropzone: vue2Dropzone
  },
  data: function () {
    return {
      id: listing.id,
      propertyType: listing.property_type,
      // More properties defined here...
      dropzoneOptions: {
        url: '/add_listing',
        autoProcessQueue: false,
        parallelUploads: 15,
        maxFiles: 15,
        addRemoveLinks: true,
        thumbnailWidth: 150,
        maxFilesize: 5,
        dictDefaultMessage: "<i class='fa fa-cloud-upload'></i> Drop files here to upload",
        headers: { "My-Awesome-Header": "header value" }
      }
    }
  },
  methods: {
    // This method gets called when the form is submitted:
    submitListing: function() {
      // Do some data processing...
      if(this.id == null) {
        // POST if it's a new listing
        this.$http.post('/listings', {listing: listingObj}).then(
          response => {
            this.$refs.myVueDropzone.processQueue()
            window.location = `/listings/${response.body.id}`
        }, response => {
          console.log(response)
        })
      } else {
        // PUT if it's an existing listing
        this.$http.put(`/listings/${this.id}`, {listing: listingObj}).then(
          response => {
            this.$refs.myVueDropzone.processQueue()
            window.location = `/listings/${response.body.id}`
        }, response => {
          console.log(response)
        })
      }
    }
  }
```

It is my understanding that when Dropzone gets submitted, the entire form gets submitted as well, so I believe my current approach may be incorrect.

How would I write this form in such a way that I can upload both the Dropzone images AND the rest of the form?

And how would I do this preserving the data for the listing which I am doing in Rails with the line `form_for(listing, html: { id: 'listing_form', data: { listing: listing.to_json } })` (which I need in order to send the correct data via the POST or PUT requests) ?

Apologies for the long post, I hope it makes sense :) Thanks in advance!

**Comment by rowanwins** [comment]
Hi @DaniG2k

Sorry for the very slow response. Did you ever work this out? There are probably a few ways to skin this cat.

By calling `.processQueue()` you would be sending a request, but my understanding is that you rather add the information to a request from the broader form event. 

So I'd be looking at deleting the `.processQueue()` call and grabbing the info you need out of the files. You should be able to look at this.$refs.myVueDropzone.files to get the array of files, and then you can structure things.

Alternatively the [dropzone doco](https://github.com/enyo/dropzone/wiki/Combine-normal-form-with-Dropzone) does provide a dropzone-centric way of doing thing, that said I reckon your proposed is the track I'd take.

Let me know if you're still stuck.
