### ISSUE TITLE
vue2 dropzone url 404 not found???

### ISSUE THREAD

**Issue by P1yaph0n** [rowanwins/vue-dropzone#289]
What do I do wrong in coding?

> ### html
```
<vue-dropzone id="dropzone"
                    :options="dropzoneOptions"
                    :headers="dropzoneOptions.header"
                    :useCustomDropzoneOptions="true"
                    @vdropzone-error="DropZoneError"
                    @vdropzone-success="DropZoneSuccess"
                    @vdropzone-sending="DropZoneSending"
                    @vdropzone-file-added="DropZoneAddedFile">
                  </vue-dropzone>
```

>### vue.js
```
dropzoneOptions: {
        url: 'http://localhost:8080/ota/src/assets/uploads/',
        method: 'POST',
        thumbnailWidth: 180,
        thumbnailHeight: 180,
        addRemoveLinks: true,
        dictDefaultMessage: "<i class='fa fa-cloud-upload'></i> Room Type Picture",
        header: {
          'Access-Control-Allow-Origin': '*',
          'Access-Control-Allow-Methods': 'GET, POST, OPTIONS, PUT, DELETE',
          'Access-Control-Allow-Headers': 'Origin, X-Requested-With, Content-Type, Accept, X-File-Name, X-File-Size, X-File-Type',
          'Content-Type': 'application/x-www-form-urlencoded'
        },
        autoProcessQueue: true
      },
```

>### Methods
```
DropZoneAddedFile: function (file) {
      console.log(file)
      // console.log(file.name)
    },
    DropZoneSending: function (file, xhr, formData) {
      console.log(file)
    },
    DropZoneError: function (file) {
      console.log(file)
    },
    DropZoneSuccess: function (file, response) {
      console.log(file)
      // console.log(response)
    }
```

Thank you all..
Sorry I'm not good at English pls.

**Comment by P1yaph0n** [comment]
![1517909248472](https://user-images.githubusercontent.com/20749233/35851456-ac74f94a-0b5a-11e8-96ec-d160070eb0b3.jpg)

**Comment by vrajroham** [comment]
You are using old documentation for this. See official documentation here https://rowanwins.github.io/vue-dropzone/docs/dist/#/installation

**Comment by vrajroham** [comment]
Check your development server is running and you have provided valid route. It seems you have given url, where your files should be uploaded. Url should be endpoint which will be capable of accepting files and upload it to specified directory.

**Comment by P1yaph0n** [comment]
@vrajroham 

My server is runing and Route in valid

The url specified is the internal folder of the project.
I need to set a new folder or need to set something more

---
thank all pls

**Comment by rowanwins** [comment]
Hi @P1yaph0n 

You need more than a empty folder. You need to provide an endpoint that processes the incoming file and places it somewhere on the server. What language are you writing your server in?

**Comment by P1yaph0n** [comment]
@rowanwins 

Now I'm working on a local server.
The server is actually a windows server.

I use vue.js, javascript in project.

**Comment by rowanwins** [comment]
Hi @P1yaph0n 

You need to have some code on the server (eg some php, or if you're using Windows Server some .Net) that exposes an endpoint which accepts the post request.

**Comment by P1yaph0n** [comment]
@rowanwins 

I will try it. thank you sir

**Comment by rahulswimmer** [comment]
HTML:
     <vue-dropzone
          id="file"
          :options="dropzoneOptions"
          @vdropzone-file-added="fileAdded"
          class="fileDrop"
          name="file"
          :useCustomSlot="true"
        >
     <script>
     import vue2Dropzone from 'vue2-dropzone'
     export default {
       components: {
         vueDropzone: vue2Dropzone
       },
       data() {
         return {
           dropzoneOptions: {
              url: 'https://httpbin.org/post'
           }
         }
       }
     }
     </script>

Here I already have an endpoint to post the file, I don't need the dropzonOptions url anymore and yet due it being a required entity, I have to declare and initialise it. Now every-time I upload a file two POST requests are send, one where I hit to submit the file and other is https://httpbin.org/post i.e. url in dropzoneOptions.

How do I handle this ?
