### ISSUE TITLE
dz-progress when autoProcessQueue: false

### ISSUE THREAD

**Issue by mattdunndc** [rowanwins/vue-dropzone#296]
Hi,

How can I remove the horizontal line (dz-progress?) when autoProcessQueue is set to False?  Anyone, anyone, Bueller?

![image](https://user-images.githubusercontent.com/7073238/36341980-d46640e0-13c4-11e8-98b1-7797d52c10c9.png)

**Comment by mattdunndc** [comment]
Newbie question:  How do I listen for the vdropzone-queue-complete event?  Thanks!

**Comment by mattdunndc** [comment]
Help!  Trying to remove the white line above.  Thanks!

**Comment by rowanwins** [comment]
Hi @mattdunndc 

Depending on the end result desired
- the slightly trickier approach would involve passing in a custom template that removed the div entirely
- the easy approach would be to override the css by doing something like `dz-progress{display:none;}`

Does that help?

**Comment by mattdunndc** [comment]
thanks @rowanwins .  Can't seem to get the easy approach to work (dz-progress{display:none;}) so I guess I will live with it.

**Comment by rowanwins** [comment]
Hi @mattdunndc 

Do you know how to use the Chrome Dev Tools to check what css is being applied? If not I suggest taking a look at [this tutorial](https://developers.google.com/web/tools/chrome-devtools/inspect-styles/)

**Comment by mattdunndc** [comment]
Thanks @rowanwins .  I changed the opacity to .5 in Dev Tools and that's what I want.  I tried to add this to my site.css but it's not taking.  I must be doing something wrong.

.dropzone .dz-preview .dz-progress {
    opacity: .50;
}

**Comment by mattdunndc** [comment]
why is this getting crossed out?
![image](https://user-images.githubusercontent.com/7073238/36544728-27a0d2b8-17b5-11e8-9e9c-bef3ce9ce0ea.png)

**Comment by rowanwins** [comment]
So what is likely happening is that the dropzone css is being injected after your component css and so it is overriding your component css.

That being the case you should use the id of the dropzone component that you're setting because it is a more [specific css selector](https://designshack.net/articles/css/what-the-heck-is-css-specificity/)
````
#myDropzone .dz-preview .dz-progress {
    opacity: .50;
}
// Replace the #myDropzone with whatever you are setting as the id
````
Hope that helps

**Comment by mattdunndc** [comment]
@rowanwins Rowan!  Thanks for your help on this.  It worked **wonderfully** and I learned a few things.  Really appreciate all your contributions to the community.

**Comment by rowanwins** [comment]
Learning chrome dev tools is in my top 3 things for ppl new to web development to learn, will save you a lot of time and heartache if can learn quick and efficient debugging

**Comment by vrajroham** [comment]
@mattdunndc I agree! I too learnt about **specific css selector**, same issue wasted my lot of time earlier.

Thanks @rowanwins 🎉

**Comment by shogunfighter** [comment]
When you instantiate the Dropzone, you can set the `previewTemplate` property. You see i commented the `dz-progress` below. I think that will hide that element. You can also test if you can hide other elements that you don't want showing...

```
const DZ = new Dropzone("#image-loader-upload .dropzone", {
            acceptedFiles: 'image/*',
            previewTemplate: `\
                <div class="dz-preview dz-file-preview">
                  <div class="dz-image"><img data-dz-thumbnail /></div>
                  <div class="dz-details">
                    <div class="dz-size"><span data-dz-size></span></div>
                    <div class="dz-filename"><span data-dz-name></span></div>
                  </div>
                  <!------------------- <div class="dz-progress"><span class="dz-upload" data-dz-uploadprogress></span></div> --------------->
                  <div class="dz-error-message"><span data-dz-errormessage></span></div>
                  <div class="dz-success-mark">
                    <svg width="54px" height="54px" viewBox="0 0 54 54" version="1.1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" xmlns:sketch="http://www.bohemiancoding.com/sketch/ns">
                      <title>Check</title>
                      <defs></defs>
                      <g id="Page-1" stroke="none" stroke-width="1" fill="none" fill-rule="evenodd" sketch:type="MSPage">
                        <path d="M23.5,31.8431458 L17.5852419,25.9283877 C16.0248253,24.3679711 13.4910294,24.366835 11.9289322,25.9289322 C10.3700136,27.4878508 10.3665912,30.0234455 11.9283877,31.5852419 L20.4147581,40.0716123 C20.5133999,40.1702541 20.6159315,40.2626649 20.7218615,40.3488435 C22.2835669,41.8725651 24.794234,41.8626202 26.3461564,40.3106978 L43.3106978,23.3461564 C44.8771021,21.7797521 44.8758057,19.2483887 43.3137085,17.6862915 C41.7547899,16.1273729 39.2176035,16.1255422 37.6538436,17.6893022 L23.5,31.8431458 Z M27,53 C41.3594035,53 53,41.3594035 53,27 C53,12.6405965 41.3594035,1 27,1 C12.6405965,1 1,12.6405965 1,27 C1,41.3594035 12.6405965,53 27,53 Z" id="Oval-2" stroke-opacity="0.198794158" stroke="#747474" fill-opacity="0.816519475" fill="#FFFFFF" sketch:type="MSShapeGroup"></path>
                      </g>
                    </svg>
                  </div>
                  <div class="dz-error-mark">
                    <svg width="54px" height="54px" viewBox="0 0 54 54" version="1.1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" xmlns:sketch="http://www.bohemiancoding.com/sketch/ns">
                      <title>Error</title>
                      <defs></defs>
                      <g id="Page-1" stroke="none" stroke-width="1" fill="none" fill-rule="evenodd" sketch:type="MSPage">
                        <g id="Check-+-Oval-2" sketch:type="MSLayerGroup" stroke="#747474" stroke-opacity="0.198794158" fill="#FFFFFF" fill-opacity="0.816519475">
                          <path d="M32.6568542,29 L38.3106978,23.3461564 C39.8771021,21.7797521 39.8758057,19.2483887 38.3137085,17.6862915 C36.7547899,16.1273729 34.2176035,16.1255422 32.6538436,17.6893022 L27,23.3431458 L21.3461564,17.6893022 C19.7823965,16.1255422 17.2452101,16.1273729 15.6862915,17.6862915 C14.1241943,19.2483887 14.1228979,21.7797521 15.6893022,23.3461564 L21.3431458,29 L15.6893022,34.6538436 C14.1228979,36.2202479 14.1241943,38.7516113 15.6862915,40.3137085 C17.2452101,41.8726271 19.7823965,41.8744578 21.3461564,40.3106978 L27,34.6568542 L32.6538436,40.3106978 C34.2176035,41.8744578 36.7547899,41.8726271 38.3137085,40.3137085 C39.8758057,38.7516113 39.8771021,36.2202479 38.3106978,34.6538436 L32.6568542,29 Z M27,53 C41.3594035,53 53,41.3594035 53,27 C53,12.6405965 41.3594035,1 27,1 C12.6405965,1 1,12.6405965 1,27 C1,41.3594035 12.6405965,53 27,53 Z" id="Oval-2" sketch:type="MSShapeGroup"></path>
                        </g>
                      </g>
                    </svg>
                  </div>
                </div>\
            `,
        });
```

**Comment by AshwinIcfGithub** [comment]
@rowanwins Can I hide progress bar dynamically? I'm try to hide it after upload is done. I'm trying custom template to render preview.

**Comment by yakamuki** [comment]
i don't know if anyone found out a solution on this, but if not, you can do this without any css code. You just have to use the 'addedfile' option when initializing the Dropzone element, to hide the progress bar.
```
var coverDropzone = new Dropzone("#element",{
                init: function() {
                    this.on("addedfile", function(file) {
                        $("#cover_upload").find('.dz-progress').addClass('d-none');
                    });
                },
  });
```
The above code hides the progress bar, and if you have a button to manually process the queue just do

```
            $('#btn').on('click',function(e){
                e.preventDefault();
                if (coverDropzone.files.length > 0)
                {
                    $("#element").find('.dz-progress').removeClass('d-none');
                    coverDropzone.processQueue();
                }
            });
```

*dropzone version **6.0.0-beta.2**
