### ISSUE TITLE
Handle more dropzone events

### ISSUE THREAD

**Issue by MithrandirDK** [rowanwins/vue-dropzone#30]
I lack more of dropzone's events being emitted from this component.

Specifically, I would like to remove all files and reload the content listing on queue complete - but now I have to do that after each file is uploaded, resulting in as many content reloads as there are files uploaded.

**Comment by rowanwins** [comment]
Hi @MithrandirDK 

Can you please specify which of the [dropzone events](http://www.dropzonejs.com/#event-list) and [methods](http://www.dropzonejs.com/#dropzone-methods )you'd like to see made available.

Do also note that this is an open source library and contributions are welcome. As you can [see here](https://github.com/rowanwins/vue-dropzone/blob/vue2/src/index.vue#L117-L135) adding additional support for dropzone events is very easy.

**Comment by MithrandirDK** [comment]
primarily, I need the queuecomplete - especially since you have implemented the removeAllFiles method with the true parameter, meaning that I risk cancelling uploads in progress if I call it after each upload is complete.

For completeness, I'd say that the removeFile(file) Dropzone method would also be handy to have available.

I know that I could do this and submit a PR and it's not that I cannot be bothered - but the time needed to setup (fork, pull, make changes, create setup for testing changes, creating pull request) for me is (I assume) quite a lot higher than for you (who I presume already have the code and a development setup) considering it is such a few lines of code.

Were it a more elaborate change, I would definitely have gone the PR route.

**Comment by rowanwins** [comment]
Hi @MithrandirDK 

This is now done and available via npm as v2.1.4 , let me know if you run into any issues.

Cheers
Rowan

**Comment by MithrandirDK** [comment]
Thank you, it looks to be working beautifully
