### ISSUE TITLE
Error in mounted hook: "Error: Invalid dropzone element." when extending vue-dropzone

### ISSUE THREAD

**Issue by cicsolutions** [rowanwins/vue-dropzone#306]
First, I just have to say "thank you" to all involved in this component.  It really is fantastic and easy to use!

I needed to be able to pass a custom variable to the sendingEvent method so that I could customize the name of the file that is being saved in my controller.  If there is an easier/better way to do this, please let me know, but my approach was to extend your vue-dropzone component with a wrapper component of my own. I did some searching for how to add a custom property to a 3rd party component and "extending" seemed to be the way to go.

So, I created a DropZone.vue component which has the following contents:

```
<template>
    <vue-dropzone
        :ref="id"
        :id="id"
        :options="options"
        v-on:vdropzone-sending="sendingEvent">
    </vue-dropzone>
</template>

<script>
import vue2Dropzone from 'vue2-dropzone';
import 'vue2-dropzone/dist/vue2Dropzone.css';

export default {
    extends: vue2Dropzone,
    components: {
        vueDropzone: vue2Dropzone
    },
    props: {
        id: {
          type: String,
          required: true
        },
        options: {
          type: Object,
          required: true
        },
        color_name: { 
            type: String,
            default: null 
        },
    },
    methods: {
        sendingEvent(file, xhr, formData) {
            formData.append('color_name', this.color_name);
        }
    }
}
</script>
```

Then, I have a component called ColorList who's job is to render a list of colors with a dropzone instance for each color.  The ColorList component imports my custom drop-zone component so I can pass in my custom property.  The contents of the ColorList component are:

```
<template lang="html">

    <div class="color-options">

        <div v-for="(color, index) in colors" :key="color.id">

            {{ color.name }}

            <drop-zone
                :ref="'dzUpload_' + index"
                :id="'dzUpload_' + index"
                :options="dzOptions"
                :color_name="color.name">
            </drop-zone>

        </div>

    </div>

</template>

<script>
import DropZone from './DropZone.vue';

export default {
    components: {
        DropZone
    },
    props: {
        colors: { default: null },
    },
    data() {
        return {
            dzOptions: {
                url: '/uploads-save',
                ...
            }
        }
    }
}
</script>

```

This all seems to work perfectly except I'm getting an error in my console stating:
_Error in mounted hook: "Error: Invalid dropzone element."_

Despite this error, the functionality is working perfectly.  My custom property is getting through to the sendingEvent and passed to my controller to be used in the filename that is saved in the database.

Since I'm not finding much information about extending components through Google, I thought I'd ask the vue-dropzone experts if you see an error in how I've extended your component, or if there may be a cleaner/simpler solution to what I'm trying to achieve.

Thanks again for this great component!

**Comment by rowanwins** [comment]
Hey @cicsolutions 

Thanks for a great description and super-polite request! Can you possibly take a screen-grab of how your app looks when rendered, I'm just having a little trouble visualising what you've got. 

The error message is suggesting that your dropzone element hasn't yet been mounted onto the DOM. Can you try and just mount your custom vue-dropzone component without the looping? If that works you know your wrapper is fine. After that reintroduce the loop, perhaps try an array with a single colour before using the full array. Hopefully we can narrow it down to what might be causing the issue.

Cheers

**Comment by cicsolutions** [comment]
Thanks @rowanwins!  

It does seem like a "DOM not yet mounted" type of issue.  I created a test as you suggested, and without the loop, rendering my wrapper component still gives the same "Invalid dropzone element" error.  

It seems like since my wrapper component extends your component, there may be some logic in your mounted() method that doesn't like how I've extended it?

In my wrapper component there is no mounted() method, and the error states "Error in mounted hook: ..." for my wrapper component.  Since I'm extending your component, I guess it's like my mounted() method would be the same as yours, but it's having a hard time processing as it normally would because it's being called for my component ahead of yours?

I'm still learning Vue and while the idea of needing to wait for the DOM makes sense, I'm fairly clueless about how and where to slow the logic down to wait for the DOM.  

Thank you so much for brainstorming this with me!  I'm open to any and all ideas you may have, and please let me know what code or information I can share that may help.

**Comment by cicsolutions** [comment]
I've simplified my code to hopefully make it easier to review and trap the issue.

Here's my wrapper DropZone.vue component:

```
<template>
    <vue-dropzone
        :ref="id"
        :id="id"
        :options="options">
    </vue-dropzone>
</template>

<script>
import vue2Dropzone from 'vue2-dropzone';
import 'vue2-dropzone/dist/vue2Dropzone.css';

export default {
    extends: vue2Dropzone,
    components: {
        vueDropzone: vue2Dropzone
    }
}
</script>
```

And then I call my wrapper component inside another component (i.e. my ColorsList.Vue, but stripped down to just the dropzone without any loop or custom params) like this:

```
<template lang="html">

    <drop-zone
        ref="dzUpload"
        id="dzUpload"
        :options="dzOptions">
    </drop-zone>

</template>

<script>
import DropZone from './DropZone.vue';

export default {
    components: {
        DropZone
    },
    data() {
        return {
            dzOptions: {
                url: '/images-save',
                ...
            }
        }
    }
}
</script>
```

**Comment by cicsolutions** [comment]
Wooooohoooo!!!  We got it figured out!  I was basically trying to do two things in my wrapper component (i.e. wrap and extend).  

If the idea was to extend your component, I should have had your component html in my template. Then my component would function just as yours, except I could insert my own custom properties or override your code as needed.  

 It made more sense in my setup to consider my component a wrapper rather than an extender.

This way, my component could accept the color variable generated in the loop and pass it to the sendingEvent method that your component is able to receive.

In case anyone else has a similar requirement, here's the code that is working for me:

Custom Component DropZone.vue that basically wraps around the vue-dropzone component and accepts it's own custom properties as well as the properties required by vue-dropzone:

```
<template>
    <vue-dropzone
        :ref="id"
        :id="id"
        :options="options"
        v-on:vdropzone-sending="dzSendingEvent">
    </vue-dropzone>
</template>

<script>
import vue2Dropzone from 'vue2-dropzone';
import 'vue2-dropzone/dist/vue2Dropzone.css';

export default {
    components: {
        vueDropzone: vue2Dropzone
    },
    props: {
        id: {
          type: String,
          required: true
        },
        options: {
          type: Object,
          required: true
        },
        color: {
            type: String,
            default: null
        },
        ... other custom properties as needed
    },
    methods: {
        dzSendingEvent(file, xhr, formData) {
            formData.append('color', this.color);
            ... append other custom properties as needed
        }
    }
}
</script>

``` 

Then I have a ColorList.vue component that can loop through each color and pass any of the individual color data to the wrapper component.

```
<template lang="html">

    <div v-for="(color, index) in colors" :key="color.id">

        <drop-zone
            :ref="'dzUpload_' + index"
            :id="'dzUpload_' + index"
            :options="dzOptions"
            :color="color.name">
        </drop-zone>

    </div> <!-- end for loop -->

</template>

<script>
import DropZone from './DropZone.vue';

export default {
    components: {
        DropZone
    },
    data() {
        return {
            dzOptions: {
                url: '/images-save',
                ...
            }
        }
    },
}
</script>
```

Cheers @rowanwins!  I sure do appreciate you!

**Comment by rowanwins** [comment]
Nice job @cicsolutions - glad you got it sorted!
