### ISSUE TITLE
Add slot support

### ISSUE THREAD

**Issue by thunder87** [rowanwins/vue-dropzone#308]
Would be a nice addition to the package.

I can't get the drag-drop working with the :include-styling="false" because the drag-drop feature is bound to the component and anything placed inside the component is not rendered.

**Comment by rowanwins** [comment]
Hi @thunder87 

Can you share a bit more about what you envisage with this, perhaps a sample API?

Thanks,
Rowan

**Comment by thunder87** [comment]
Include-styling=“false” hides the dropzone container (as it should). But this also means that the drag-drop functionality attached to the container does not work. If you allowed a default slot, the custom styling could be placed inside the component meaning that the dropzone again will allow drag-drop functionality - at least, thats my guess.

**Comment by aarondfrancis** [comment]
+1

**Comment by aarondfrancis** [comment]
For now, I've managed to work around this by creating a little shim component:

In `dropzone-shim.vue`
```
<template>
    <div v-bind:class="{ 'vue-dropzone dropzone': includeStyling }" :id="id" ref="dropzoneElement">
        <slot></slot>
    </div>
</template>

<script>
    import vue2Dropzone from 'vue2-dropzone';
    export default vue2Dropzone;
</script>
```

Then, anywhere:
```
// Where you would use this 
// import vue2Dropzone from 'vue2-dropzone';

// Use this
import vue2Dropzone from './dropzone-shim';
```

**Comment by rowanwins** [comment]
Thanks for sharing @aarondfrancis - I'll have to have a bit of think as to how to make this work best, TBH I can't say I've done a huge amount with slots so it's taking a little bit to get my head around.

**Comment by zxcnasab** [comment]
thanks for this

**Comment by vrajroham** [comment]
Slots support has been added to this component now! This feature is added in recent release https://github.com/rowanwins/vue-dropzone/releases/tag/v3.3.0. Thanks to @alexbikazzan for this. Closing this issue for now. New issue can be opened if there's issue in feature.
