### ISSUE TITLE
How to send additional params along when the image is uploaded

### ISSUE THREAD

**Issue by miki996** [rowanwins/vue-dropzone#309]
Hi,

How can i  send additional params along when the image is uploaded? For example i want to pass the username of the current logged in user along the photo in the body of the POST request

I cannot see the option to send additional params when the photo is uploaded.

**Comment by miki996** [comment]
Actually i just got this fixed. After sending the photo the Express API i used the `v-on:vdropzone-success="success"`. I returned the insertId of the photo which was uploaded and inserted into the SQL. 

Then i fire another POST to the API to UPDATE the SQL row with the username where the photo location is already stored
`
 success(file, response) {
     //Get the id of the uploaded photo in the SQL Table
     //swal(response.insertId.toString());
     fetch('http://localhost:3000/api/photo/adddPublisher', {
       method: 'post',
       headers: {
         'Accept': '*',
         'Content-Type': 'application/json'
       },
       body: JSON.stringify({id: response.insertId, username: this.$session.get('jwt')})
     }).then(res => res.json())
       .then(data => console.log(data))
   },
`

**Comment by wa05** [comment]
Im sending the data in the headers but Im not understanding how to read that data from Laravel controller in the $request

**Comment by mateo2181** [comment]
@wa05 Did you resolve the problem with Laravel? I am getting an error with status 419.
