### ISSUE TITLE
What is the event for successful upload using chunking ?

### ISSUE THREAD

**Issue by codegeek1001** [rowanwins/vue-dropzone#314]
I am using chunked uploads and it works great but not able to get callback to work once chunk upload is fully done. Is it @vdropzone-success event ? Native dropzone documentation says there is a callback called "chunksUploaded". Is this implemented in this library ? I tried @vdropzone-chunksUploaded but that is not working.

**Comment by rowanwins** [comment]
I think `chunksUploaded` us a new event so it's currently not included in our library. If you'd like to get it included it should be pretty straight forward to put in a pull request following [the existing pattern](https://github.com/rowanwins/vue-dropzone/blob/master/src/components/vue-dropzone.vue#L245-L247).

Otherwise we'll get around to it eventually.

**Comment by rowanwins** [comment]
Ah actually sorry just read the dropzone docs (should've done that first before answering!) 

`chunksUploaded` is an option you pass in, so you should be doing something like 
````
data: return {
      dropzoneOptions: {
          url: 'https://httpbin.org/post',
          chunksUploaded: function (file, done) {
              // do someting...
              done()
          }
      }
},

}

````

let me know if that helps

**Comment by codegeek1001** [comment]
Thanks so much. I actually read through the dropzone documentation as well right after I posted the message and figured it out. But this will help anyone else with similar question. Great Library and works awesome!!

**Comment by bilogic** [comment]
Pardon me, but how do I access `this` from inside `chunksUploaded`? My chrome's console log keeps telling me undefined.

I was hoping to call the same method as `vsuccess` to have some UI updates
