### ISSUE TITLE
Bug with 3.1.0: s3ObjectLocation undefined

### ISSUE THREAD

**Issue by scottadamsmith** [rowanwins/vue-dropzone#316]
When posting a file after the 3.1.0 update, there is additional content being posted related to S3 that is "undefined", whether you are using S3 or not. This broke our API that handles the upload as we were checking explicitly for a single file being uploaded. We can work around this for now, but I was wondering if  was intended or not. I think this is the line of code in question:

https://github.com/rowanwins/vue-dropzone/blob/1edc99efeda7208d22e3da809573b7f85e51df20/src/components/vue-dropzone.vue#L268

If vm.isS3 is false, is it appropriate to be appending s3ObjectLocation to formData?

**Comment by rowanwins** [comment]
Thanks for reporting this and apologies for the regression - @vrajroham are you able to take a look at this?

**Comment by scottadamsmith** [comment]
Thanks, appreciate the fix!
