### ISSUE TITLE
addRemoveLinks adds red message [object Object]

### ISSUE THREAD

**Issue by rafailml** [rowanwins/vue-dropzone#318]
Hi and thanks for great package. 
I'm trying to use vue-dropzone with addRemoveLinks in options:
```
dropzoneOptions: {
                url: 'nothing',
                thumbnailWidth: 200,
                maxFilesize: 2,
                dictDefaultMessage: 'Drop file here or click with mouse',
                addRemoveLinks: true,
                dictRemoveFile: "Remove",
                maxFiles: 1,
            }
```

And I'm  getting this:
<img width="202" alt="screen shot 2018-04-22 at 6 34 49 pm" src="https://user-images.githubusercontent.com/15358719/39096705-366fe01a-465c-11e8-8635-88330a7a9dd8.png">

How to get rid of red message?
Also is there a way to disable url? I'm using form without action, because I'm using AXIOS.

Thank you very much

**Comment by rowanwins** [comment]
Hmmm im not sure why you get `[object object]` but I'd guess its because you have set the `url` to nothing.

The[ dropzone docs page](http://www.dropzonejs.com/) manages to do this somehow, one of the things I've noticed is that they don't set a url in their options, eg
````
dropzoneOptions: {
                thumbnailWidth: 200,
                maxFilesize: 2,
                dictDefaultMessage: 'Drop file here or click with mouse',
                addRemoveLinks: true,
                dictRemoveFile: "Remove",
                maxFiles: 1,
            }
````

So perhaps give that a go and let us know how you get on.

**Comment by rafailml** [comment]
@rowanwins
It does not work without url.
I'm getting errors in console:

> Error in mounted hook: "Error: No URL provided."

And dropzone is inactive

**Comment by vrajroham** [comment]
@rafailml URL is mandatory and @rowanwins has just provided other option. Could you test by entering the url?

**Comment by rafailml** [comment]
@vrajroham , @rowanwins 
With url it works.
