### ISSUE TITLE
How to display the thumbnails preview of the uploaded file content?

### ISSUE THREAD

**Issue by harishankards** [rowanwins/vue-dropzone#320]
Hi,

Thanks for the great work first of all.

I want to show the thumbnail preview of the uploaded content instead of showing a just blank thumbnail. How do I achieve it?

Thanks in advance

**Comment by rowanwins** [comment]
Hi @harishankards 

It depends on the type of file you upload, if its an image file (eg jpg or png) it should show a thumbnail automatically. if you're uploading a pdf then it won't show a thumbnail. Can you elaborate a bit more on your use case?

**Comment by harishankards** [comment]
Hi @rowanwins,

Thanks for the prompt reply. Yes, in my case, it will be mostly ppt files, pdf format files and sometimes images. For images, there is no problem. But, how do I show a preview of those files in the thumbnail?

**Comment by rowanwins** [comment]
Unfortunately I don't think there is a way that you without writing a fair bit more custom js. You'd need to pull in something like pdf.js to handle pdf's, then you'd need some specific way of handling ppt's etc. 

Reality is you'd probably be better off implementing something like [filepreview](https://github.com/maxlabelle/filepreview) server-side.
