### ISSUE TITLE
vue-dropzone appends s3ObjectLocation to form data when s3 is not enabled

### ISSUE THREAD

**Issue by caleb-allen** [rowanwins/vue-dropzone#321]
https://github.com/rowanwins/vue-dropzone/blob/1edc99efeda7208d22e3da809573b7f85e51df20/src/components/vue-dropzone.vue#L259-L271

**Comment by rowanwins** [comment]
Good pickup @caleb-allen , I'll hand this over to @vrajroham as he looks after the s3 stuff.

**Comment by vrajroham** [comment]
@caleb-allen Could you confirm if this issue is resolved?
