### ISSUE TITLE
How to stop vdropzone-removed-file action from misbehaving?

### ISSUE THREAD

**Issue by harishankards** [rowanwins/vue-dropzone#326]
Hi, below is my code for handling success and removing actions:
```html
  <vue-dropzone ref="myVueDropzone" @vdropzone-success="vsuccess" id="dropzone" @vdropzone-removed-file="vremoved" :options="dropzoneOptions">
  </vue-dropzone>
```
I have defined the `vremoved` actions as removing from database.  I thought and expected, `vdropzone-removed-file` means, when the file is removed using `remove-file` link after it is uploaded. 

But, in my case, after successful upload, when I change the page and switch to another component it considers itself as removed and it's triggering vremoved event. How can I prevent that?

**Comment by vrajroham** [comment]
Have a look at this comment of @rowanwins https://github.com/rowanwins/vue-dropzone/issues/273#issuecomment-353161590

**Comment by harishankards** [comment]
Thanks much buddy @vrajroham
