### ISSUE TITLE
How Do I get file source

### ISSUE THREAD

**Issue by hasib32** [rowanwins/vue-dropzone#33]
Is there any way I can get the uploaded file source? using `vdropzone-fileAdded(file)` event

**Comment by rowanwins** [comment]
Hi @hasib32 , can you confirm what you mean, do you mean the file path?

**Comment by hasib32** [comment]
I did like this:

     fileUploaded(file) {
                console.log(file);
            }
I need to get the Binary String. That way I can post that string to my backend api. Before I was using
Javscript https://developer.mozilla.org/en-US/docs/Web/API/FileReader class to get that.

**Comment by hasib32** [comment]
Basically I need the raw binary data.

**Comment by rowanwins** [comment]
So yep you can do something like

````
    <dropzone id="myVueDropzone" url="https://httpbin.org/post" v-on:vdropzone-success="success"></dropzone>

    methods: {
      'success': function (file) {
        var response = JSON.parse(file.xhr.response)
        console.log(response.files.file)
      },

````
Hopefully that get you going in the right direction

Good luck

**Comment by hasib32** [comment]
Hi @rowanwins Thanks for your reply. It's working. But if I have `:autoProcessQueue="false"` then the method doesn't get fired. I also tried with `vdropzone-fileAdded` event. It doesn't get fired either. I can't auto upload the file. I need to send some meta data with it.

**Comment by rowanwins** [comment]
Hi @hasib32 

Perhaps try hooking into the `sending` event
````
v-on:vdropzone-sending="sending"

    methods: {
      'sending': function (file, xhr, formData) {
        var response = JSON.parse(xhr.response)
        console.log(response.files.file)
      },
````

**Comment by hasib32** [comment]
Sorry no Luck.

**Comment by hasib32** [comment]
I am able to do this way:

`<dropzone id="myVueDropzone" url="https://httpbin.org/post" v-on:vdropzone-fileAdded="fileAdded" :autoProcessQueue="false"></dropzone>`

`           fileAdded(file) {
                const reader = new FileReader();

                reader.onload = function(e) {
                    // file source
                    console.log(e.target.result)
                }.bind(this)

                reader.readAsDataURL(file);
            }`

**Comment by rowanwins** [comment]
awesome, glad you got it sorted!
