### ISSUE TITLE
How to do if i'd only need the name of the elements.

### ISSUE THREAD

**Issue by Luis15Herr** [rowanwins/vue-dropzone#330]
Hi, you've done a great job with Vue-Dropzone. But i have a question. How can I do if I just need the name of the objects that are inside the dropzone? I don't need to know the size, nor do i need the upload progress, I just need the file name, and send it to the server. The documentation is a little loose, improve the a little. Greetings from Venezuela.

**Comment by rowanwins** [comment]
Hi @Luis15Herr 

I think you might be referring to a custom preview template, in which case [this demo](https://rowanwins.github.io/vue-dropzone/docs/dist/#/custom-preview) should provide some good information. You may also want to refer to the dropzone doco on custom templates [here](http://www.dropzonejs.com/#layout).

Let us know if you have any problems left

**Comment by Luis15Herr** [comment]
Hi @rowanwins 

I'm new to this vue. js, I just want to make a dropzone to show me the elements as a list, something like this:
![export](https://user-images.githubusercontent.com/38222722/40736166-3e7a479c-640b-11e8-89be-c7a0023cfdc1.png)

**Comment by Luis15Herr** [comment]
Hi @rowanwins 

I'm new to this vue. js, I just want to make a dropzone to show me the elements as a list, something like this:
![captura de pantalla_2018-05-30_13-11-36](https://user-images.githubusercontent.com/38222722/40736363-da82793e-640b-11e8-86f7-e387974006b7.jpg)
