### ISSUE TITLE
error when configuring files in queue

### ISSUE THREAD

**Issue by NanoDev777** [rowanwins/vue-dropzone#335]
Hello, I have been using the component and with the documentation I have configured almost all the points that I need, however I have two problems: 

1. if I have a queue of many images in load and one of these fails, there is some way to manually retry again the What failed ?, 
2. and my second doubt is that just with the images that failed I have the following message in red with the words (object, object) in the loading interface, I attach an image of this last. 

How to solve these 2 points.
![capture](https://user-images.githubusercontent.com/28969280/41388142-9526f75e-6f58-11e8-803b-7d775eff8dd2.png)

**Comment by NanoDev777** [comment]
@rowanwins if I can connect to the vdropzone-error event, for my first point my idea was to retry the load of this by pressing a button or something similar, is this possible ?, for the second point observe the comment you are referring to, and it is a possible solution, but is there no way to cancel that message? since I do not want to give details of the error, I simply wish that this message does not appear red

**Comment by rowanwins** [comment]
I'm not sure why simply retrying the upload would make any difference - if it failed the first time it would probably fail the second time unless you change something... so I suggest investigating why the upload is failing.

To hide the error message you could possibly use some css like 
````
.dz-error-message{
   display: none;
}
````
