### ISSUE TITLE
remove file

### ISSUE THREAD

**Issue by tiboufroulou** [rowanwins/vue-dropzone#34]
I'am able to catch the @vdropzone-success event, but I am not sure if @vdropzone-removedFile is working indeed:

<dropzone
            ref="myUniqueID"
            :id="id"
            :url="uploadUrl"
            @vdropzone-success="showSuccess"
            @vdropzone-removedFile="deleteImage"
etc.

Building gives this error
Found camelCase attribute: @vdropzone-removedFile="deleteImage". HTML is case-insensitive. Use @vdropzone-removed-file="deleteImage" instead. Vue will automatically interpret it as camelCase in JavaScript. If this is an SVG camelCase attribute, use the .camel modifier. 

and using @vdropzone-removed-file="deleteImage" doesn't work neither.

Any idea ? Any example of use ?

**Comment by rowanwins** [comment]
Thanks for the report @tiboufroulou , turns out that events that are emitted up should not contain camelcasing, I've now resolved the issue and will update the docs and npm and let you know when it's all done.

**Comment by rowanwins** [comment]
Gday @tiboufroulou 

I've just released v2.1.5 on npm which addresses the issue. Check out the docs for more info on the event names.
