### ISSUE TITLE
Image preview overlapping issue 

### ISSUE THREAD

**Issue by duythang** [rowanwins/vue-dropzone#347]
Dear author

When i use dropzone, the image preview overlaps with my navbar. Check picture

![untitled](https://user-images.githubusercontent.com/25820048/42826126-f9ae5d66-89e3-11e8-9a12-fcf42dfb6d9a.png)

How can i fix it ? Thank you so much for your help

**Comment by rowanwins** [comment]
Hi @duythang

You'll need to set the `z-index` css property on your nav bar to be higher than the dropzone image

**Comment by duythang** [comment]
@rowanwins Thank you. I fixed it
