### ISSUE TITLE
CSS not displayed properly with latest version

### ISSUE THREAD

**Issue by DEDZTBH** [rowanwins/vue-dropzone#35]
I am using the latest version (2.1.4 on npm) which allows me to add customized headers while sending the post request. However the CSS doesn't seemed to display correctly. 2.1.3 and prior versions worked properly.

**Comment by rowanwins** [comment]
Hi @DEDZTBH 

Thanks for the report, I've just pushed up v2.1.5 to npm so hopefully this resolves the issue, if not let me know.

Cheers
Rowan

**Comment by DEDZTBH** [comment]
Unfortunately the new version still looked the same way as 2.1.4 did...
The 'remove' looked like a link instead of a button like previous versions, and the done icon (I'm using font awesome) looked tiny and not centered so I wonder if these css failed.
Or as I noticed, they looked different from older versions because of change of style?

**Comment by rowanwins** [comment]
Grrr, alright try again with 2.1.6, Im pretty sure it's sorted this time sorry.

**Comment by DEDZTBH** [comment]
It worked! Thanks!
