### ISSUE TITLE
uploadMultiple set to true sends multiple requests

### ISSUE THREAD

**Issue by Velja92** [rowanwins/vue-dropzone#351]
I've set the uploadMultiple to true inside the dropzoneOptions and the dropzone is still sending multiple requests to server instead of sending only one. Any known solution? :)

**Comment by vrajroham** [comment]
@Velja92 So what's the issue? :) That is the same as intended behavior. Please check below link.

https://www.dropzonejs.com/#config-uploadMultiple

> Whether to send multiple files in one request. If this it set to true, then the fallback file input element will have the multiple attribute as well.

**Comment by rowanwins** [comment]
Hi @Velja92 

Did you get anywhere with this? Can you share a snippet of your config?

Thanks,
Rowan

**Comment by rowanwins** [comment]
Can't replicate.

Setting `uploadMultiple: true` will send two requests, the first is an `OPTIONS` request and the second is the actual POST request containing the multiple files.
