### ISSUE TITLE
How to make a post request to RestFull API with the query?

### ISSUE THREAD

**Issue by Jussiadev** [rowanwins/vue-dropzone#352]
I need to send a request to the server with query `{"file": {}}`. How can i do this?

**Comment by rowanwins** [comment]
Hi @Jussiadev

This component automatically sends the post request for you. Are you trying to send additional information with your file? Perhaps you can share a fuller snippet of your configuration and explain your use case a little more

Thanks
Rowan

**Comment by rowanwins** [comment]
Closing due to a lack of information.
