### ISSUE TITLE
webkitdirectory support

### ISSUE THREAD

**Issue by mitymarcus** [rowanwins/vue-dropzone#353]
Hello!

I am attempting to develop something similar to Google Drive or Dropbox for my company's product, and I need to be able to upload a file and retain it's structure. 

For instance, if I have a directory tree that looks like
```
project
│   README.md
│   file001.txt    
│
└───folder1
│   │   file011.txt
│   │   file012.txt
│   │
│   └───subfolder1
│       │   file111.txt
│       │   file112.txt
│       │   ...
│   
└───folder2
    │   file021.txt
    │   file022.txt
```
If you upload the entire project folder, I want it to look like
```
README.md
file001.txt
folder1/file011.txt
folder1/file012.txt
folder1/subfolder1/file111.txt
folder1/subfolder1/file112.txt
...
folder2/file022.txt
```
Normally, I see people using webkitdirectory for situations like this, and webkitdirectory provides file.webkitRelativePath, assuming they are using a browser that supports it.

Thanks in advance!

**Comment by rowanwins** [comment]
Hi @mitymarcus 

You could possibly hook into the sending event and get some information about the file (eg webkitRelativePath) and send it as a param with xhr request... See this [example](https://rowanwins.github.io/vue-dropzone/docs/dist/#/additionalParams).

Hope that helps get you on your way.

Cheers
R
