### ISSUE TITLE
Event duplicate-file not working

### ISSUE THREAD

**Issue by awacode21** [rowanwins/vue-dropzone#354]
Hi,

i am currently using dropzone and am wondering how the "**duplicate-file**" event thing should work.
Within vue-dropzone documentation it is described as the following:

**duplicate-file(file) | Fired when duplicateCheck is enabled.**

But where can i "**enable**" that duplicateCheck ? I cannot find it neither in this documentation nor in the dropzonejs documentation.

In my case "autoProcessQueue" is false, so all files will get uploaded to the server after user clicked on an upload button. But i need to check that the user did not add the same file twice to the dropzone area, to prevent that two identical thumbnails get generated.

I am currently wondering how to achieve this, and if there is any possibility in the vue-dropzone component or the dropzone itself. 

Regards, Annick

**Comment by vrajroham** [comment]
@awacode21 Thanks for reporting the issue. Few months ago we re-written the this component from scratch due to some constraints in previous configuration for enhancement. I just checked the codebase and found that, the event you mentioned regarding duplicate file was available in previous version and it is missing in v3.* Maybe. Though I'll check this in morning and get back to you in the morning. 

Thanks. :)

**Comment by jezperp** [comment]
How's this coming along? Would be nice to be able to use this feature.

Thanks.

**Comment by rowanwins** [comment]
Hi @awacode21 & @jezperp 

This feature wasn't ported to v3 because it was proving a little challenging to implement robustly. I can potentially look at it again a bit later this week, if either of you are able to take a look before then feel free to submit a pull request.

Cheers
Rowan

**Comment by vrajroham** [comment]
@awacode21 Duplicate file check feature added again to this component 🎉 .

#### Please note 
- The event name is changed from ~`duplicate-file`~ to `vdropzone-duplicate-file`.
- File is marked as duplicate if, added file matches **name, size and lastModifiedDate** with existing files and that file is not added to dropzone preview.
- To enable this feature you need to set `duplicateCheck` prop on dropzone to `true, by default it is `false`.
- Reference - [Props](https://rowanwins.github.io/vue-dropzone/docs/dist/#/props), [Demo](https://rowanwins.github.io/vue-dropzone/docs/dist/#/demo), [Events](https://rowanwins.github.io/vue-dropzone/docs/dist/#/events)

Reopen another issue if this dosen't work as expected.

Happy Coding  :tada:

**Comment by awacode21** [comment]
Thank you very much!
