### ISSUE TITLE
Options: resizeWidth problems

### ISSUE THREAD

**Issue by healthlogics** [rowanwins/vue-dropzone#355]
Hi there,

Running into a problem trying to use the resizeWidth option to resize client side before upload. I have resizeWidth: 1200 in my dropzone options but it seems to do nothing. All uploads continue to keep their original size. My other option setting are working, just can't get the client side resize to work. Anyone help me with any suggestions or where to start?

**Comment by vrajroham** [comment]
Can you share anything that you tried? Code snippet or component?

**Comment by healthlogics** [comment]
Hi @vrajroham. I did get it working by implementing a separate client side resizing script that handles the files before upload. I am wondering if this could have something to do with the fact that I am NOT using the 'URL' option as I am uploading data to firebase storage. I am getting the files via this.$refs.myVueDropzone.getAcceptedFiles() and sending the results to Firebase. Maybe this is my problem?

**Comment by duythang** [comment]
@healthlogics: I am trying to upload imgs to firestore using vue-dropzon. Can you share your brief code ? 

Thanks

**Comment by duythang** [comment]
@healthlogics can you share resizing code? Thank you.
