### ISSUE TITLE
How to get image URL after dropping image in the dropzone?

### ISSUE THREAD

**Issue by duythang** [rowanwins/vue-dropzone#357]
Dear author

In a normal img DOM ``` <img :src="imageUrl>```
We can read imgUrl via src attribute. How can i read img URL after dropping img in the dropzone ? 
I tried to use ``` @vdropzone-files-added``` event to receive added img information. However, there is not
any information about the img URL as picture: 

![image](https://user-images.githubusercontent.com/25820048/44584032-e8af9c00-a7a7-11e8-96ed-083cc353de7d.png)

Thank you

**Comment by duythang** [comment]
Thank you, i found out solution

**Comment by Timibadass** [comment]
@duythang please can you share your solution?

**Comment by ghost** [comment]
Can we not get the image location from folder/explorer? We use image from the file explore only to drop in dropzone, not manually but via some code

**Comment by Jimmymgx** [comment]
> Thank you, i found out solution

can you tell us the solution please
