### ISSUE TITLE
Getting the Dropzone instance

### ISSUE THREAD

**Issue by SayakMukhopadhyay** [rowanwins/vue-dropzone#358]
I want to tweak the progress bar to show the progress as the file is uploaded to the client and not to the server (file is not uploaded to a server at all). If I read the docs at dropzone correctly, I will need to emit the `uploadprogress` event manually for which I need a handle to the dropzone object.

Is it possible to get an instance of the dropzone object right now? If not, I would be happy to create a PR in which a method would return the instance.

**Comment by SayakMukhopadhyay** [comment]
Yup! Getting the object directly works. I overlooked it tbh but is it good to use the object like that?
`dropzone` is not defined in `data` too. I just don't want to break my program with an update to vue-dropzone which might change undocumented stuff.

**Comment by rowanwins** [comment]
Hi @SayakMukhopadhyay 

Nah it should be fine, the `dropzone` object that is available shouldn't be available via the data object as it's not a reactive thing. 

We don't really expect ppl to use it often, I don't even know where or how we'd document it TBH or what we'd say, but I'm open to ideas :)

**Comment by mistrjirka** [comment]
Hi,
this no longer works, the this.$refs.myVueDropzone.dropzone object does no longer exists. I am able to get this.$refs.myVueDropzone, but the dropzone property is undefined, do you have any suggestions?
