### ISSUE TITLE
urlsigner.js: need to allow withCredentials: true

### ISSUE THREAD

**Issue by mariusa** [rowanwins/vue-dropzone#359]
When specifying ```awss3.signingURL```, we need to be able to set XHR options such as ```withCredentials: true```
https://developer.mozilla.org/en-US/docs/Web/API/XMLHttpRequest/withCredentials

This is not set with headers.
Please add another parameter, xhrOptions, which we could set as ```{withCredentials: true}```
and set these in 
https://github.com/rowanwins/vue-dropzone/blob/29b5922b8f30af89fa5ec6a9c9be0553d5993085/src/services/urlsigner.js

Thanks

**Comment by vrajroham** [comment]
@mariusa Thanks for the insights. I got you, this is really important, I'll look into this and get back here.

**Comment by rowanwins** [comment]
Resolves thanks to @potamus and published to npm as v3.5.1
