### ISSUE TITLE
multiple upload

### ISSUE THREAD

**Issue by Bahram9** [rowanwins/vue-dropzone#36]
hi
how about multiple upload?
I've add use-custom-dropzone-options=true and in my options uploadMultiple but how can I use successmultiple event of dropzone?

**Comment by rowanwins** [comment]
Hi @Bahram9 

I've just released version 2.1.7 to npm which should support the `successmultiple` and `sendingmultiple` events. Check out the [docs ](https://github.com/rowanwins/vue-dropzone#events). Let me know if you run into any issues.

Cheers
Rowan

**Comment by Bahram9** [comment]
hi
it's good to hear that, thank you.

Cheers
Bahram
