### ISSUE TITLE
Can I add all the previews inside a div?

### ISSUE THREAD

**Issue by sepehrooo** [rowanwins/vue-dropzone#361]
Is it possible to have a container div around the preview divs (dz-preview)?

**Comment by sepehrooo** [comment]
I used previewContainer but it didn't work.
Here's the code:
`<dropzone id="myVueDropzone"
                                    ref="document" 
                                    url="{{ path('api_tutor_upload_doc') }}"
                                    :use-custom-dropzone-options="true"
                                    :dropzone-options="{
                                        language: {
                                            dictDefaultMessage: `<a class=\'btn btn-pill\'><i class=\'fa fa-file-text-o\'></i>` + trans('Upload PDF or image') + `</a>`,
                                            dictRemoveFile: trans('Remove')
                                        },
                                        acceptedFileTypes: 'application/pdf, image/*',
                                        thumbnailWidth: 50,
                                        thumbnailHeight: 50,
                                        previewsContainer: '.seppp'
                                    }"
                                    :use-font-awesome="true"
                                    :max-file-size-in-m-b="20"
                                    @vdropzone-success="showSuccess"
                                    @vdropzone-removed-file="removeFile">
                                        
                                        <div class="dropzone-previews seppp"></div>
                                    </dropzone>`

**Comment by adriandmitroca** [comment]
How did you solve this?

**Comment by rowanwins** [comment]
You need to use the `previewTemplate` option, see the [dropzone docs](https://www.dropzonejs.com/#layout).

**Comment by sepehrooo** [comment]
previewsContainer option works but I used yarn to update to the latest version and it seems yarn upgrade didn't update the package to the latest version so I edited package.json and hardcoded the latest version of dropzone in it and did a yarn install. 
Here's a working example:
```vue
<dropzone id="tutorRegisterationDropzone"
ref="document"
:use-custom-dropzone-options="true"
:options="{
   url: '{{ path('api_tutor_upload_doc') }}',
   dictRemoveFile: trans('Remove'),
   acceptedFiles: 'application/pdf, image/*',
   maxFileSize: 20,
   addRemoveLinks: true,
   previewsContainer: '.my-prevs',
   thumbnailWidth: 150,
   thumbnailHeight: 150,
}"
@vdropzone-success="TranscriptsFileSuccess"
@vdropzone-removed-file="removeFile"
:use-font-awesome="true">
<a class="btn btn-pill"><i class="fa fa-file-text-o"></i>Upload PDF or image</a>
<div class="my-prevs dropzone-previews"></div>
</dropzone>
```
