### ISSUE TITLE
Get dataURL from file (v-on:vdropzone-file-added)

### ISSUE THREAD

**Issue by jtorfs01** [rowanwins/vue-dropzone#365]
Hi, 
I'm sorry if this is a stupid question but: How can I get the dataURL from the (file) in a vdropzone-file-added(file) event, or is that not possible? 

I'm trying to create my own upload event to upload multiple images to Firebase storage and I would need the dataURL to upload. 

Thanks in advance for the response.

**Comment by jtorfs01** [comment]
Hi, thanks for the response. I wish it was that easy. :)  

I can do` console.log(file.name')`

nd that gives me the name of the file but `console.log('dataURL') `or any other value always returns an error. I don't have the project on my current computer, but I will add some of the code later today and check the exact error message I get.

**Comment by jtorfs01** [comment]
My code looks like this:


```
 fileAdded: function(file) {
      console.log("data url: " + file.dataURL);
    }
```

**Comment by jtorfs01** [comment]
Yes I do know how to do that, and I also tried that. Could the problem be that the 'name' attribute is in the 'header' . If you check the first line: 
`File(2351) {upload: Object, status: "added", previewElement: div.dz-preview.dz-file-preview, previewTemplate: div.dz-preview.dz-file-preview, name: "facebook.png", …}`

the name attribute is there, but the 'dataURL' is a level below that? 

```
File(2351) {upload: Object, status: "added", previewElement: div.dz-preview.dz-file-preview, previewTemplate: div.dz-preview.dz-file-preview, name: "facebook.png", …}
accepted:true
dataURL:"data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAPoAAAD6CAYAAACI7Fo9AAAACXBIWXMAAAsSAAALEgHS3X78AAAI4UlEQVR4Ae3dXYhU5xnA8ePumLqu0Rg/U2u2JiJNbZuSkBRSqiH246IsFRoSelMDhURCL2oLzU0pIeQ6Df2U0ot61RQClUgvhEoRkrSUhsa2pk1QozWmju46WbOzs3VXt5xlNJt1d3Vn1p3zzvP7wYDKgmee499z5sw7cxaMjY1lM9m2c9/HsyzbXn9snfGHgfl0MMuyvfnjwO7e4zP9vdOGXg/86SzLdth1UHh78l6nC37K0Lft3PedLMt+ZN9CcnYd2N37/OSNvir0bTv3/dpRHJK258Du3scmPoGOib8RObSFHfWWr7gSev10XeTQHnbUmx43fupev/D2th0MbWdDfoHu8hH9afsX2tJ42wseeuIlR3Nobxs66gthgPa1XejQ/sZDt6wV2tvWDjsY2p/QIQChQwBChwCEDgEIHQIQOgQgdAhA6BCA0CEAoUMAQocAhA4BCB0CEDoEIHQIQOgQgNAhAKFDAEKHAIQOAQgdAhA6BCB0CEDoEEDJTiZlG9cvzbq7Fjb9DI6+cz4bHBpp238LQqfw8pg39dxSu2Pd0jP33rWq1N1VKq1YtmjNjd7u/oHh8vCFi8OXf3/4aKVUrY2M5r8+dur86lNnql1ZIv9JCJ3CycO+b/PqygN3rx3ctH7ZylKpIw8qf/TM57ZO/s9k3aruGX/+u8+9mh16q/9Gb1ZDhE4h5HFvf3BD35Z7buvs7lq4PMuyyw/mgNBpmSWLF2a9W3oqj355Y8fNixcuy7Jspb1xYwidebd2xeLsyUc2lz+3efXSUqnDUXseCJ15kx/Bv7/js+XP3702f+17wy+m8QGhMy8e+dKdw9/62ifGSqUOgbeA0Lmh8otszz55f9+q5V1ef7eQ0Llh8qP4E1//5CIX2VpP6My5/LX4Mzvv67t70wqBF4TQmVNO1YtJ6...
height:250
lastModified:1534417876469
lastModifiedDate:Thu Aug 16 2018 13:11:16 GMT+0200 (Central European Summer Time) {}
__proto__:Object {constructor: , toString: , toDateString: , …}
name:"facebook.png"
previewElement:div.dz-preview.dz-image-preview {align: "", title: "", lang: "", …}
previewTemplate:div.dz-preview.dz-image-preview {align: "", title: "", lang: "", …}
size:2351
status:"queued"
type:"image/png"
upload:Object {uuid: "6cf72602-b499-453d-9863-8f90a8b69583", progress: 0, total: 2351, …}
webkitRelativePath:""
width:250
__proto__:File {name: <accessor>, lastModified: <accessor>, lastModifiedDate: <accessor>, …}
facebook.png
```

**Comment by jtorfs01** [comment]
OK, I finally figured it out. The dataURL isn't part of the file object so I don't think there is a way to access the dataURL? Or maybe it is but I have no idea how to do that. 

What I did now is, I used `vdropzone-thumbnail` in stead of `vdropzone-file-added` and that does have the dataURL as an attribute so for now I'm going to use that approach. Feel free to correct me if you think there is a better approach or if i'm missing something.

**Comment by rowanwins** [comment]
I'm not sure why you can access using the event that you did given that the data is there, but you've got it resolved so perhaps let's leave it at that :)

**Comment by chunkey711** [comment]
Hi there! I have the same problem. I need to customise uploading action. but something goes wrong
`
<vue-dropzone ref="myVueDropzone" id="dropzone" @vdropzone-file-added="saveImages" :options="dropzoneOptions">
...
        dropzoneOptions: {
          url: null,
          dictDefaultMessage: 'Перетащите сюда фотографии (или нажмите)',
          maxFilesize: 10
        },
...
      saveImages(data) {
        const file = new FormData
        file.append('file', data[0])
        file.append('id', this.flat.id)
        this.$http.post('api/v1/upload', file)
      },
`

@rowanwins

**Comment by spencercap** [comment]
great helper library, many thanks @rowanwins ! 

tho i'm also having issues intercepting the default url Post behavior and uploading an Audio file to firebase storage. when i console.log the file from the `vdropzone-file-added` event, it seems that the MP3s I'm uploading do not have this .dataURL field to use in the firebase.storage upload function. any suggestions? 

```
File {upload: {…}, status: "added", previewElement: div.dz-preview.dz-file-preview, previewTemplate: div.dz-preview.dz-file-preview, name: "SimonSays.mp3", …}
accepted: true
lastModified: 1555812209000
lastModifiedDate: Sat Apr 20 2019 19:03:29 GMT-0700 (Pacific Daylight Time) {}
name: "SimonSays.mp3"
previewElement: div.dz-preview.dz-file-preview.dz-processing.dz-success.dz-complete
previewTemplate: div.dz-preview.dz-file-preview.dz-processing.dz-success.dz-complete
processing: true
size: 2755956
status: "success"
type: "audio/mp3"
upload: {uuid: "1b60974d-13d2-4fce-b8f5-50cd648dbcc3", progress: 100, total: 2756142, bytesSent: 2756142, filename: "SimonSays.mp3", …}
webkitRelativePath: ""
xhr: XMLHttpRequest {onreadystatechange: null, readyState: 4, timeout: 30000, withCredentials: false, upload: XMLHttpRequestUpload, …}
__proto__: File
```

**Comment by eakenbor** [comment]
I am having exactly the same issue. Console.log(file.dataURL) returns "undefined". So how is one expected to get the dataURL to be saved to database?

**Comment by vadymsem** [comment]
> I am having exactly the same issue. Console.log(file.dataURL) returns "undefined". So how is one expected to get the dataURL to be saved to database?

Add a function which will called on vdropzone-file-added event which will receive vdropzone file as an argument. Then inside that function you can do the next to get dataURL:
```
const reader = new FileReader()
reader.readAsDataURL(file)

reader.onload = function(event) {
  //   event.target.result - is dataURL data
};
```

**Comment by RamananSharma** [comment]
> > I am having exactly the same issue. Console.log(file.dataURL) returns "undefined". So how is one expected to get the dataURL to be saved to database?
> 
> Add a function which will called on vdropzone-file-added event which will receive vdropzone file as an argument. Then inside that function you can do the next to get dataURL:
> 
> ```
> const reader = new FileReader()
> reader.readAsDataURL(file)
> 
> reader.onload = function(event) {
>   //   event.target.result - is dataURL data
> };
> ```

I had to wait until the file is read, and pass it along with the dropzone file object for further processing. So I used the following (used onloadend event to trigger the function after file reading is completed)
addedFile() is my custom method.

```const reader = new FileReader();
let receivedFile;
reader.readAsDataURL(file);
reader.onload = function(event) {
receivedFile = event.target.result; // event.target.result contains base64 encoded image
};
reader.onloadend = () => this.addedFile(file, receivedFile)

**Comment by laszlol** [comment]
> > > I am having exactly the same issue. Console.log(file.dataURL) returns "undefined". So how is one expected to get the dataURL to be saved to database?
> > 
> > 
> > Add a function which will called on vdropzone-file-added event which will receive vdropzone file as an argument. Then inside that function you can do the next to get dataURL:
> > ```
> > const reader = new FileReader()
> > reader.readAsDataURL(file)
> > 
> > reader.onload = function(event) {
> >   //   event.target.result - is dataURL data
> > };
> > ```
> 
> I had to wait until the file is read, and pass it along with the dropzone file object for further processing. So I used the following (used onloadend event to trigger the function after file reading is completed)
> addedFile() is my custom method.
> 
> ```
> let receivedFile;
> reader.readAsDataURL(file);
> reader.onload = function(event) {
> receivedFile = event.target.result; // event.target.result contains base64 encoded image
> };
> reader.onloadend = () => this.addedFile(file, receivedFile)
> ```

I'd like to pass the base64 format in an extra parameter but. When I use the `vdropzone-file-added(file)` event to get base64 format and set it to the `this.base64` it is still empty inside `vdropzone-sending(file, xhr, formData)`.

```
vsendingFile(file, xhr, formData) {
      console.log('send')
      formData.append('data', this.base64)
    },
    vFileAdded(file) {
      const reader = new FileReader()
      reader.onload = (event) => {
        this.base64 = event.target.result
      };
      reader.readAsDataURL(file)
    }
```
What am I doing wrong?

**Comment by RamananSharma** [comment]
> ```
> vsendingFile(file, xhr, formData) {
>       console.log('send')
>       formData.append('data', this.base64)
>     },
>     vFileAdded(file) {
>       const reader = new FileReader()
>       reader.onload = (event) => {
>         this.base64 = event.target.result
>       };
>       reader.readAsDataURL(file)
>     }
> ```
> 
> What am I doing wrong?

Because the FileReader reading is asynchronous and as soon as you dropped the file into dropzone it'll fire both file-added and sending callbacks while the reading is in progress (Unless you disabled auto queue processing). I'd suggest you read the file inside vsendingFile method using the file object you receive. Even then it's better to wrap the file reading reading into a Promise and use async await so you can block until the file is read, and append to formData then proceed.

**Comment by dbipin** [comment]
Still getting the issue. While using vdropzone-thumbnail the image i get is of very low quality

**Comment by yeyintnaung135** [comment]
use getAcceptedFiles()
for example : getAcceptedFiles()[0].dataURL   (note 0 is array key just for sample)
but u cannot use getAcceptedFiles() in multiplefilesadded or fileadded event u will use in thumbnail event or your submit form function for example with Vue js

```
thumbnail: function (file, dataUrl) {
            console.log(this.$refs.myVueDropzone.getAcceptedFiles()[0].dataURL);//your origin image data url
            console.log(dataUrl)//thumbnail data url

            //yours
}
```

or u can use in your submit function

  // when click submit button
       
 ```
submitform:function (event) {
console.log(this.$refs.myVueDropzone.getAcceptedFiles()[0].dataURL);//your origin image data url

 //yours
}
```

**Comment by hayden-664** [comment]
> OK, I finally figured it out. The dataURL isn't part of the file object so I don't think there is a way to access the dataURL? Or maybe it is but I have no idea how to do that.
> 
> What I did now is, I used `vdropzone-thumbnail` instead of `vdropzone-file-added` and that does have the dataURL as an attribute so for now I'm going to use that approach. Feel free to correct me if you think there is a better approach or if i'm missing something.

The reason you are unable to get the dataURL out of `vdropzone-file-added` is because you are asking for it immediately when the file is added, in fact the dataURL will only be available AFTER the file is uploaded.

So use `v-dropzone-success` instead.

**Comment by danrot** [comment]
For anybody wondering about this weird behavior, I figured out the reason for this.

First of all, there is no `dataURL` property on the [`File` object](https://developer.mozilla.org/en-US/docs/Web/API/File) by default. It only shows up in `console.log` output because [Dropzone adds it](https://github.com/dropzone/dropzone/blob/f50d1828ab5df79a76be00d1306cc320e39a27f4/src/dropzone.js#L920), after which it also emits a new `thumbnail` event. This is why it is available when you use `vdropzone-thumbnail`, but not on `vdropzone-file-added`. My guess with the `console.log` weirdness is that the converting of the image to a `dataURL` happens asynchronously, so if you to access it immediately it won't show up. In a `console.log` though, browsers will lazily evaluate the object, which means it can show up even if you place the `console.log` at the exact same spot.
