### ISSUE TITLE
In version 3.5.1 , "dictDefaultMessage" is not working .

### ISSUE THREAD

**Issue by PetkevichP** [rowanwins/vue-dropzone#367]
In 3.2.2, everything is OK. the new version has some bugs

**Comment by rowanwins** [comment]
I think the culprit was [this pull request](https://github.com/rowanwins/vue-dropzone/pull/338/files#diff-1841fbb4e9888d9ed804a353de1e1e91) - I think that slot probably needs to be optional via a prop or something like that...

**Comment by rowanwins** [comment]
Resolved in `v3.5.2` - thanks for the report @PetkevichP
