### ISSUE TITLE
Thumbnail from a video upload

### ISSUE THREAD

**Issue by nassmim10** [rowanwins/vue-dropzone#368]
Hi There !

Thanks for this plugin !

I would like to know if there is a way to generate a thumbnail once the user has uploaded a video ?

Basically what I'm trying to do is:
1 - the user clicks on the dropzone
2 - he selects the video he wants to upload
3- once he validates, it displays a thumbnail
4 - I can get this thumbnail attribute to store it in my database

Looking forward to your reply,
Thanks !

**Comment by rowanwins** [comment]
Hi @nassmim10 

You'd need to hook into a third party library to generate a thumbnail from your video, eg [jsthumb](https://www.npmjs.com/package/js-thumb). It's probably doable hooking into the various [events that we provide,](https://rowanwins.github.io/vue-dropzone/docs/dist/#/events) but it'll take a bit of effort on your part to work out all the moving pieces I suspect, 

Cheers

**Comment by nassmim10** [comment]
Hi @rowanwins,

Thanks for your quick reply. I will try. Meanwhile, I'm working with this solution [https://gist.github.com/zmwangx/11275000]
