### ISSUE TITLE
custom upload function

### ISSUE THREAD

**Issue by chunkey711** [rowanwins/vue-dropzone#370]
Hello, I have a problem with customise uploading function

```
<vue-dropzone 
     ref="myVueDropzone" 
     id="dropzone" 
     :options="dropzoneOptions">
...
        dropzoneOptions: {
          url: (file) => this.saveImages(file),
          dictDefaultMessage: 'Перетащите сюда фотографии (или нажмите)',
          maxFilesize: 10
        },
...
      saveImages (data) {
        const file = new FormData
        file.append('file', data[0])
        file.append('id', this.flat.id)
        this.$http.post('api/v1/upload', file)
      },
```

This construction calls 2 requests, this        ` this.$http.post('api/v1/upload', file)` and `/undefined`– with default params 
@rowanwins

**Comment by chunkey711** [comment]
How can I fix the `undefined` request?

**Comment by chunkey711** [comment]
Thanks, I've already handle it.
If somebody interested by it, i've add the `params` key into `dropzoneOptions` like this
```
          params: () => {
            return ({id: this.flat.id})
          },
```

**Comment by MartinMuzatko** [comment]
@chunkey711 what is `this.flat` in your case?

**Comment by chunkey711** [comment]
@MartinMuzatko It is just object with keys. I've needed to send files with attachment to current id, witch I could take from` flat ` object

**Comment by MartinMuzatko** [comment]
Thanks for the quick reply! I use `async` function in url, which always returns a promise.
``` js
url: async files => {
    const form = new FormData()
    form.append('files', files[0])
    await upload(form)
},
```

is there a way to notify dropzone of the finished upload, without using await? :S

**Comment by MartinMuzatko** [comment]
Right now, this is my code:

``` js
data: () => ({
    options: {
        url: files => {
            const form = new FormData()
            form.append('files', files[0])
            upload(form)
        },
        params: () => ({id: 0})
    }
}),
```
What is different to your working example? I think it is a problem of dropzone itself, but the community is unfortunately a bit dead around it.
I started a new issue three weeks ago: https://gitlab.com/meno/dropzone/issues/135

**Comment by chunkey711** [comment]
I found in docs some events, and use it like this 
```
...
        dropzoneOptions: {
          // url: (file) => this.saveImages(file),
          url: 'api/v1/upload',
          params: () => ({id: this.flat.id}),
          dictDefaultMessage: '',
          maxFilesize: 10,
          success: () => this.fetchFlats()
        },
...
```

**Comment by MartinMuzatko** [comment]
oh, so the url is turned to the original one again :/
So you don't use a custom upload function anymore?
I need to do a bit more than setting url, param name and method

**Comment by chunkey711** [comment]
Yes, i've tried to set function to url, but it calls two requests: to my path, and to `undefined`

**Comment by MartinMuzatko** [comment]
ok. too bad. thanks for your  help anyway. I think this is a problem in the core of dropzone. I can try setting extra fields then. thanks!

**Comment by chunkey711** [comment]
You are welcome! 👍

**Comment by mohammedpatla** [comment]
@chunkey711 
Just wondering if you have any idea on how to handle errors. Also your `this.fetchFlats()` do you just handle it like a regular response.data?

My goal has been to handle/errors based on the response api gives and change the dropzone(in my form) based on the response.

I have a dropzone something like this :
```
//DropZone
        dropzoneOptions: {
              url: $baseURL + 'processCase',
              thumbnailWidth: 300,
              maxFilesize: 10,
              headers: { 
                Authorization: "Bearer " + localStorage.getItem("jwt") 
                },
              params: () => ({
                occuranceID: this.infoModal.case.occuranceID,
                dateCreated: this.infoModal.case.dateCreated,
                investigatorID: this.infoModal.case.investigatorID,
                investigatorName: this.infoModal.case.investigatorName,
                notes: this.infoModal.case.notes

              }),
              //success: (data) => this.submitSuccess(data),
              maxFiles: 1,
              addRemoveLinks: true,
              uploadMultiple: false,
              autoProcessQueue: false,
          }
```
