### ISSUE TITLE
How to change default displayed text in vue-dropzone

### ISSUE THREAD

**Issue by duythang** [rowanwins/vue-dropzone#375]
Hello authors 

Can you give me a  recommendation for changing default displayed text in vue-dropzone?
For example, i want to change some texts as follows: 
- ```REMOVE FILE```
- ```File is too big```

Thank you so much

**Comment by Fusseldieb** [comment]
@duythang This is a community. We would really appreciate if you post the solution that worked for you, instead of just closing and vanishing.

Don't do it just for yourself.

**Comment by faical** [comment]
You can change it by setting 'dictRemoveFile': 

```
Script:
export default {
  data: () => ({
    dropzoneOptions: { 
      dictRemoveFile: 'YOUR TEXT HERE'
    }
  })
}

Template:
<vue-dropzone :options="dropzoneOptions"></vue-dropzone>
```
