### ISSUE TITLE
How do I integrate this vue component with my Yii2 project?

### ISSUE THREAD

**Issue by drocom** [rowanwins/vue-dropzone#385]
Hello,

I'm experiencing problems while importing this component into my **yii2** project.

Should I create a empty folder in my backend and drag all the directories and files of vue-dropzone repository?

Do I only need to add the "src" directory? I actually need to understand a way to integrate this component into a not-new project.

I'm such a mess at the moment :/ 

![captura](https://user-images.githubusercontent.com/32545645/47920191-c2962e80-deb1-11e8-99f7-3c2a4d1bc3b0.png)

**Comment by rowanwins** [comment]
The compiled files aren't published to this repo so you'll need to either grab them from npm or run the build script.

I don't know much about yii2 sorry

**Comment by drocom** [comment]
@rowanwins Sorry about my basic knowledge, what is the folder should I be searching for in?

With those files apparently I could make this work in the yii2 project?

**Comment by rowanwins** [comment]
Hi @drocom 

So if you have npm installed you can run 
````
npm install vue2-dropzone
````
and from there you should be able to find the `vue2-dropzone/dist` which contains the compiled files.

Alternatively on the [main page of this repo](https://github.com/rowanwins/vue-dropzone) find the download button, you'll then need to cd into the downloaded files, run `npm install` and `npm run build` and that'll create the dist directory.

**Comment by rowanwins** [comment]
Closing as it's not really an issue with this library.
