### ISSUE TITLE
Support to Google Cloud Storage upload

### ISSUE THREAD

**Issue by hubertokf** [rowanwins/vue-dropzone#387]
Is anybody working on a GCS upload?

**Comment by rowanwins** [comment]
Hi @hubertokf 

Short answer is no. I'd be open to the idea if it wasn't going to add too much extra code to the library.

Cheers

**Comment by rowanwins** [comment]
Hi @hubertokf 

If you put together a pull request myself or @vrajroham should be able to help you if you get stuck, the pull request doesn't have to be perfect straight away :)

Cheers
R
