### ISSUE TITLE
Preview html is broken

### ISSUE THREAD

**Issue by sebestenyb** [rowanwins/vue-dropzone#39]
Hi

It seems the html generated markup is broken in some place:
 
```<div class="dz-error-mark' + this.errorIcon + '</div>```

https://github.com/rowanwins/vue-dropzone/blob/vue2/src/index.vue#L116

![screen shot 2017-02-14 at 4 29 13 pm](https://cloud.githubusercontent.com/assets/743212/22914014/1f871c2a-f2d3-11e6-8851-632ac6c4a29a.png)
![screen shot 2017-02-14 at 4 26 27 pm](https://cloud.githubusercontent.com/assets/743212/22914015/1faa0d16-f2d3-11e6-9ed2-15ae20327c82.png)

Cheers, Sebi

**Comment by rowanwins** [comment]
Thanks for the report @sebestenyb , this was addressed by @bryanjamesmiller .

I've just published the update to npm as version 2.1.7.

Let me know if you run into any further issues.

**Comment by sebestenyb** [comment]
It's still a bit weird, I don't have any special css, but the error message covers the remove button.
Actually it's the same on the demo page: https://rowanwins.github.io/vue-dropzone/dist/index.html

And if I use the font-awesome set, the error icon is still:
```<div class="dz-error-mark"> <i class="material-icons">error</i></div>```
So it displays the word *error* instead of the icon.

Thanks!

**Comment by rowanwins** [comment]
Have you loaded the material icons?
````
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
````

**Comment by sebestenyb** [comment]
Yes, the icon issue was my cache, that's why I crossed it out :)
But had to do some css overrides for the error tooltip, so it doesn't cover the close button.
I use the font-awesome option.

Thanks, Sebi
