### ISSUE TITLE
Upload post time increase

### ISSUE THREAD

**Issue by ahmedessam1** [rowanwins/vue-dropzone#394]
When I upload a small file it uploads successfully, but when I try to upload large file the uploading stops and the progress bar stops.

> What I have tried

I have tried to edit `php.ini` file  and increase the uploading and posting size.

> What I am getting in the console

![image](https://user-images.githubusercontent.com/26671247/49382454-2022d280-f71f-11e8-9e29-9842b08eafd6.png)

> What I think

I think when the post take more large time to upload the Dropzone stop the uploading process.
It is not a back-end problem since the back-end works find and I have tried to upload a large image without using Dropzone and it worked fine.
Probably that Dropzone stop uploading after a certain amount of  time and I want to increase that time.

**Comment by rowanwins** [comment]
Hi @ahmedessam1 

Can you try increasing the timeout `option` as per the [dropzone docs](https://www.dropzonejs.com/#config-timeout)?

**Comment by rowanwins** [comment]
Closing due to lack of feedback and workable solution

**Comment by adnanmuttaleb** [comment]
I am having exactly the same problem the upload  get stuck for large files. The default `timeout` of dropzone is 30 second,  is not this more than enough, those are my configuration options:

        maxFiles: 1,
        parallelUploads: 1,
        addRemoveLinks: true,
        maxFilesize: 10000,
        forceChunking: true,
        retryChunks:true,
        chunking: true,
        chunkSize: 6000000,
