### ISSUE TITLE
$refs.name.getQueuedFiles() is empty on @vdropzone-files-added event after drag'n'drop

### ISSUE THREAD

**Issue by asologor** [rowanwins/vue-dropzone#397]
Quick example:

```
<vue-dropzone
  ref="dropzone"
  :options="{autoProcessQueue: false}"
  @vdropzone-files-added="startUploading"
></vue-dropzone>

...

methods: {
  startUploading() {
    console.log(this.$refs.dropzone.getQueuedFiles());
    this.$refs.dropzone.processQueue();
  }
}
```

It logs an empty array when I drop files into the dropzone area but works fine when I use file chooser (click on the dropzone area and select files). As a result `this.$refs.dropzone.processQueue();` does nothing after drag'n'drop.

Might be related to #391

**Comment by asologor** [comment]
Seems this workaround solves the problem:
```
setTimeout(() => {
  console.log(this.$refs.dropzone.getQueuedFiles());
  this.$refs.dropzone.processQueue();
}, 1);
```

**Comment by khoker** [comment]
Just encountered this issue as well but mine turned out to be a configuration error.  I was restricting uploads to be of certain types (e.g., application/pdf), but the drag and drop doesn't appear to enforce that.   
   
Dragging a text file, the processQueue was empty but dragging a PDF worked as expected.

**Comment by Devin0231577** [comment]
.getAcceptedFiles() is what your looking for. The queue takes place after the add event.

**Comment by rowanwins** [comment]
Thanks @Devin0231577

**Comment by asologor** [comment]
@Devin0231577 it doesn't explain why it worked different when using drag'n'drop vs usual file browser

**Comment by EharK** [comment]
For me what worked was adding an if clause for the drag'n'drop case:
![Screenshot 2022-08-23 at 17 14 30](https://user-images.githubusercontent.com/73666469/186181321-9a68a38f-7175-487b-9443-1ad5d8e9c88f.png)
