### ISSUE TITLE
haders for Imgur

### ISSUE THREAD

**Issue by iliakut** [rowanwins/vue-dropzone#398]
Hello, I need to send authorization to Imgur. 
I use configuration:
`      dropzoneOptions: {
        url: 'https://api.imgur.com/3/image',
        headers: { Authorization: 'Client-ID .......' }
`
After send an image i get a message in console: 
> Access to XMLHttpRequest at 'https://api.imgur.com/3/image' from origin 'http://localhost:8080' has been blocked by CORS policy: Request header field Cache-Control is not allowed by Access-Control-Allow-Headers in preflight response.

I think this is because I did somethind wrong with the authorization. 
With axios the it works ok.
What should I fix?

**Comment by rowanwins** [comment]
Hi @iliakut 

Hmm it looks like perhaps dropzone is adding a `cache-control` header to the request which is throwing things off. Can you see that present on the request headers, if so it should be possible to remove that header and see what happens?

**Comment by iliakut** [comment]
I've found the answer. I need to send 
`                  'Cache-Control': null,
                  'X-Requested-With': null,`
in header
and I did't attached 
`paramName`
in DropZone options.

**Comment by inndividuell** [comment]
@iliakut how did u set these headers? I only see the option to add additional headers in this component.
Or @rowanwins can you help me? I have the same issue.
