### ISSUE TITLE
How to use with <script> tags

### ISSUE THREAD

**Issue by seanodotcom** [rowanwins/vue-dropzone#4]
How do you use this with good ol' script tags?
I see a lot of webpack, app, manifest, vendor files... just looking for straight JS & CSS to include, thanks.

**Comment by rowanwins** [comment]
Hi @seanodotcom 

Give the Dropzone.js in lib folder a go, that hopefully might just be a drop in, bearing in mind that you should've loaded the vue.js script somewhere.

Cheers
R

**Comment by christoferd** [comment]
Example with just HTML JS would be nice.
This feels like spaghetti to me at first glance.

**Comment by rowanwins** [comment]
@christoferd  If you're after just plain HTML & JS it might be easiest to use dropzone directly. The example follows the Vue.js single file component approach in a fairly standard manner so it may be that you're still getting used to that which is making it look a bit weird.

**Comment by christoferd** [comment]
@rowanwins Thanks, I ended up doing that and getting it working. Eventually will come back to try get vue working with it.
I should get into using browserfy and webpack, a lot of projects using that nowadays.

PS: This is overwhelming....
    "autoprefixer-loader": "^3.2.0",
    "babel-core": "^6.0.0",
    "babel-loader": "^6.0.0",
    "babel-plugin-transform-runtime": "^6.0.0",
    "babel-preset-es2015": "^6.0.0",
    "babel-preset-stage-2": "^6.0.0",
    "cross-env": "^1.0.6",
    "css-loader": "^0.23.0",
    "file-loader": "^0.8.4",
    "json-loader": "^0.5.4",
    "style-loader": "^0.13.1",
    "url-loader": "^0.5.7",
    "vue-hot-reload-api": "^2.0.6",
    "vue-html-loader": "^1.2.3",
    "vue-loader": "^8.5.4",
    "vue-style-loader": "^1.0.0",
    "webpack": "^1.12.2",
    "webpack-dev-server": "^1.12.0"

**Comment by rowanwins** [comment]
Gday @christoferd 

Glad to hear you got it sorted. In regard to the large package.json welcome to the world of modern js build tools and their dependencies, it certainly takes a little while to get your heard around.
