### ISSUE TITLE
vdropzone-s3-upload-success returns with parsererror

### ISSUE THREAD

**Issue by bjensen** [rowanwins/vue-dropzone#407]

**Comment by scottweinert** [comment]
@bjensen I'm getting this `parserror` when doing an s3 upload.

<parsererror xmlns="http://www.w3.org/1999/xhtml" style="display: block; white-space: pre; border: 2px solid #c77; padding: 0 1em 0 1em; margin: 1em; background-color: #fdd; color: black"><h3>This page contains the following errors:</h3><div style="font-family:monospace;font-size:12px">error on line 1 at column 1: Extra content at the end of the document
</div><h3>Below is a rendering of the page up to the first error.</h3></parsererror>. Request is marked as resolved when returns as status 201

Were you able to resolve this?
