### ISSUE TITLE
Process Queue does not process all items when upload multiple is on nor does it trigger multiple upload event

### ISSUE THREAD

**Issue by fireynis** [rowanwins/vue-dropzone#41]
When I trigger the processQueue function it only does the first two, then subsequent submits process the next two and so on. Shouldn't processQueue run all files?

Also even with uploadMultiple set to true on the dropzone element, no events to do with multiple uploads are triggered.

**Comment by rowanwins** [comment]
Hi @fireynis 

It looks like there are some bugs in dropzone with processQueue, eg https://github.com/enyo/dropzone/issues/462

Im trying to workout what the best workaround for this component is.

I'll also look into the events issue.

**Comment by fireynis** [comment]
That's good to know. Thanks for doing the research. I ended up preferring one at a time and it works better for my purposes anyways.

**Comment by MariusWiik** [comment]
I am to having this issue. My workaround was calling the processQueue again method on both success and error events. Not pretty but it works

**Comment by rowanwins** [comment]
Thanks for chiming in here @MariusWiik , I saw similar suggestions on my initial google of the issue. I'll try a find time this week to look at the issue in more depth.

**Comment by vrajroham** [comment]
Same issue here! I found simple option for this issue. Set `parallelUploads` value same as `maxFiles` value. @fireynis may be dropzone  have added `parallelUploads` option later to tackle this issue.

**Comment by fireynis** [comment]
Auto process queue did not work in my context as the images where part of a form that was to posted with it. As for the `parallelUploads` suggestion, it doesn't fix the problem that exists. If there is a necessity to limit how many uploads can occur at once, it should still continue to process the queue when prior ones complete. I believe this is more of a dropzone issue than it is the vue plugins.

**Comment by jaydip13189** [comment]
I am not able to get a response after hitting "**this.$refs.myVueDropzone.processQueue()**" in my vue-dropzone.

**Comment by vrajroham** [comment]
@jaydip13189 Are you getting the specific error in console?

**Comment by jaydip13189** [comment]
@vrajroham no, I am not getting any type of error in the console and  @vrajroham  actually I am trying to listen for errors which are thrown by the REST API during File processing.

**Comment by vrajroham** [comment]
@jaydip13189 Better to open a new issue with some of your code snippet, so can assist you better.

**Comment by jaydip13189** [comment]
Ok, @vrajroham Thanks for your quick replay. I will open a new issue.
