### ISSUE TITLE
Manual add file breaks the loop / function 

### ISSUE THREAD

**Issue by leo1989work** [rowanwins/vue-dropzone#414]
`let file = {size: 5120, name: 'aaa'}
  let file2 = {size: 5120, name: 'bbb'}

                        console.log('a')

                        this.$refs.myVueDropzone.manuallyAddFile(file, '/backend/aaa')

                        console.log('b')

                        this.$refs.myVueDropzone.manuallyAddFile(file2, '/backend/bbb')

                        console.log('c')`  

This will only output 'a' and the code after manual add file is not run, using the latest version, thanks

**Comment by rowanwins** [comment]
Can you share the error message that you're getting?

**Comment by leo1989work** [comment]
opened developer console but does not have JS error

**Comment by leo1989work** [comment]
`                        let file = {size: 5120, name: 'googlelogo_color_92x30dp.png'}
                        let file2 = {size: 5120, name: 'knowledge_graph_logo.png'}

                        console.log('a')

                        this.$refs.myVueDropzone.manuallyAddFile(file, 'https://www.google.com/images/branding/googlelogo/2x/googlelogo_color_92x30dp.png')

                        console.log('b')

                        this.$refs.myVueDropzone.manuallyAddFile(file2, 'https://pay.google.com/about/static/images/social/knowledge_graph_logo.png')

                        console.log('c')`


Thought is hardcode file error, however, tested with real file it still the same behavior, thanks
