### ISSUE TITLE
.setOption() dont work

### ISSUE THREAD

**Issue by efdutra** [rowanwins/vue-dropzone#419]
Hello there.
I've installed today the Vue Dropzone (latest version)
But i need to make a POST request to a dynamically, meaning i need to change URL option AFTER i do select the ID needed.

my structure is like that:

`export default {
    name: 'Upload',
    components: {
      vueDropzone: vue2Dropzone
    },
    data() {
      return {
        dropzoneOptions: {
          url: 'https://URLINEEDTOCHANGEDYNAMICALLY',
etc .....`

and on my Vue code, i do have @vdropzone-sending="changeUrl"

and a method

`changeUrl(){
this.$refs.myVueDropzone.setOption('url', newUrl)
      },`

But Nothing happens not even an Error message..

Any ideias ??

**Comment by rowanwins** [comment]
Can you try `this.$refs.myVueDropzone.dropzone.setOption('url', newUrl)`

Cheers

**Comment by efdutra** [comment]
> Can you try `this.$refs.myVueDropzone.dropzone.setOption('url', newUrl)`
> 
> Cheers

It didn't work. I've already tried... and did it again.

Nothin works..

i put the entire page code here:
https://codeshare.io/aY3bnN

**Comment by efdutra** [comment]
@rowanwins Finally make it work. But kind off using "brute force"

thats my code:

`this.$refs.myVueDropzone.options.url = newURL
this.$refs.myVueDropzone.dropzone.options.url = newURL
this.dropzoneOptions.url = newURL`

**Comment by duikb00t** [comment]
I still have the issue, it's not fixed yet.

**Comment by efdutra** [comment]
> I still have the issue, it's not fixed yet.

Not even doing the same i did ?

**Comment by duikb00t** [comment]
I tried. I have this setup in a Laravel environment.  So I try to pass a UUID to the vue-dropzone component. For some reason it's not possible to share the URL into the component.


Laravel View:
```
<vue-dropzone url="{{ route('api.store-coupon', ['uuid' => $registration->unique_id]) }}" uuid="{{ $registration->unique_id }}" ref="myVueDropzone" id="dropzone" :options="dropzoneOptions"></vue-dropzone>
 <script>
        window.vm.$data.dropzoneOptions.url = '{{ route('api.store-coupon', ['uuid' => $registration->unique_id]) }}';
    </script>
```

app.js
```
const app = new Vue({
    el: '#app',
    components: {
        vueDropzone: vue2Dropzone
    },
    data: function () {
        return {
            dropzoneOptions: {
                url: 'http://127.0.0.1:8000/api/coupon/upload/282d7a55-3f38-45fb-b5d8-9cbbd25ffb15',
                thumbnailWidth: 150,
                maxFilesize: 10,
                duplicateCheck: true,
                acceptedFiles: 'application/pdf'
            }
        }
    }
});

window.vm = app;

```

**Comment by duikb00t** [comment]
Solved by doing:
```
window.vm.$data.dropzoneOptions.url                 = '{{ route('api.store-coupon', ['uuid' => $registration->unique_id]) }}';
window.vm.$refs.myVueDropzone.options.url           = '{{ route('api.store-coupon', ['uuid' => $registration->unique_id]) }}';
window.vm.$refs.myVueDropzone.dropzone.options.url  = '{{ route('api.store-coupon', ['uuid' => $registration->unique_id]) }}';

```

**Comment by sithuaung** [comment]
For me it works by using like 
```
this.$refs.myVueDropzone[0].setOption
```

**Comment by csgt** [comment]
and this worked for me...

 this.$refs.myVueDropzone.setOption()
