### ISSUE TITLE
Override CSS

### ISSUE THREAD

**Issue by lewiswalsh** [rowanwins/vue-dropzone#42]
How can I override the bundled CSS to use my own?

**Comment by rowanwins** [comment]
Hi @lewiswalsh 

You should be able to use the id selector you pass in to pass down some css. 

````
<template>
    <dropzone id="myVueDropzone" url="https://httpbin.org/post"></dropzone>
</template>

<style>
  #myVueDropzone > .dz-message {
    color: red;
  }
</style>
````
Does that give you enough to go on?

**Comment by lewiswalsh** [comment]
That's perfect, thank you.

**Comment by Moejoe90** [comment]
This is not a good solution in my opinion
