### ISSUE TITLE
Custom preview to work with sortable - draggable

### ISSUE THREAD

**Issue by bocanhcam** [rowanwins/vue-dropzone#420]
![screen shot 2019-02-14 at 11 44 54](https://user-images.githubusercontent.com/35592955/52759333-c445c580-304e-11e9-82ed-698bad21d9fc.png)

I want to use this package [https://github.com/SortableJS/Vue.Draggable](https://github.com/SortableJS/Vue.Draggable) to sort order my images but I don't know how.

The example [https://rowanwins.github.io/vue-dropzone/docs/dist/#/custom-preview](https://rowanwins.github.io/vue-dropzone/docs/dist/#/custom-preview) seems like not the right way to make it work.

I do not upload images right away. I just want to preview it then users can sort order images, crop... after submit to form.

If anyone knows how to do it. Please help. Thanks a lot

**Comment by rowanwins** [comment]
Hi @bocanhcam 

Unfortunately I don't think it's going to be possible to work in tandem with `vue.draggable`. The rendering of the preview elements is very basic and controlled by `dropzone.js`, vue isn't able to have any influence that far down.

Cheers

**Comment by bocanhcam** [comment]
Thank you for your reply @rowanwins 

So I think I'm going to find another solution.

**Comment by shmarts** [comment]
Did you ever find a solution to this, @bocanhcam? Looking to do something similar.

**Comment by bocanhcam** [comment]
@shmarts I did it myself. Not going to do it with dropzone anymore
