### ISSUE TITLE
How to make button in dictDefaultMessage trigger file selector

### ISSUE THREAD

**Issue by TheAustinG** [rowanwins/vue-dropzone#421]
I customized the default text that is shown before any files are added. I've added a button in the text that I would like the user to actually click on which will then trigger the file selector and they can select the file they want to upload.

Based off of the documentation, I thought I would be able to do this by setting the `clickable` option of the dropzone to the id of the button I want the user to click. However, this is not working as expected. Even when `clickable = "#btn-upload"` the whole dropzone, including the button, do nothing when clicked. Obviously I don't want the dropzone to do anything when clicked but I do want the button to open the file selector.

Here are some snippets of the code:

```HTML
<vue-dropzone 
    :id="element.Id + '-video-uploader'"
    :options="videoDropzoneOptions"
    ref="vueDropzone">
</vue-dropzone>
<div :id="'video-uploader-hidden-input-' + element.Id"></div>
```

```JavaScript
export default {
    components: {
        "vue-dropzone": vue2Dropzone
    },
    props: ["element"],
    data() {
        return {
            videoDropzoneOptions: {
                url: '/UrlToUpload',
                dictDefaultMessage: "<span style='color: #ABABAA'><i class='fal fa-play fa-3x'></i><p style='margin-top: 10px;'>Drag & Drop,</p><button id='btn-upload' class='btn btn-primary'>Upload</button><p>or <a href='#'>link to a video</a></p></span>",
                hiddenInputContainer: "#video-uploader-hidden-input-" + this.element.Id,
                clickable: false
            }
        }
    },
    mounted() {
        this.$refs.vueDropzone.dropzone.options.clickable = "#btn-upload";
    }
});
```
![image](https://user-images.githubusercontent.com/14006557/53103389-2c832400-34f3-11e9-91b5-c6d80a07cc11.png)

Am I missing something? I feel like this should work but it's not.

**Comment by TheAustinG** [comment]
Can I get any help on this issue?

**Comment by rowanwins** [comment]
Hey @TheAustinG ,

I half started writing a response the other day and got distracted sorry. Theoretically what you've done should work according to the description on the dropzone docs

> If true, the dropzone element itself will be clickable, if false nothing will be clickable. You can also pass an HTML element, a CSS selector (for multiple elements) or an array of those. In that case, all of those elements will trigger an upload when clicked.

Although I'm wondering if you're supposed to pass in selectors that are rendered elsewhere on the DOM, eg a div outside the dropzone and not one that you've passed within the `dictDefaultMessage`.

Can you try and trigger the clickable with another DOM selector?

**Comment by TheAustinG** [comment]
Hi @rowanwins,

No worries on the late reply! It seems that you are correct, if I put the element outside of the dropzone then it works as expected. Not the most ideal situation but I can definitely make it work!

Thanks again for your help!

**Comment by Kamran95** [comment]
s

**Comment by Kamran95** [comment]
> Hi @rowanwins,
> 
> No worries on the late reply! It seems that you are correct, if I put the element outside of the dropzone then it works as expected. Not the most ideal situation but I can definitely make it work!
> 
> Thanks again for your help!

can you please send me the updated code which is working as i am stuck with the same problem
thanks
