### ISSUE TITLE
Give the possibility to change object-fit on manually added file

### ISSUE THREAD

**Issue by ValentinCrochemore** [rowanwins/vue-dropzone#422]
Hey guys ! Thanks for your amazing work !

Can we make object-fit dynamic when a manually add file is added ? And access it with an atribute of option like manuallyAddedFileMethod for example.

For now it's hardcoded in [this line](https://github.com/rowanwins/vue-dropzone/blob/c95841772c9f5a1eb52999971137f69b04ad0fdc/src/components/vue-dropzone.vue#L272)

**Comment by rowanwins** [comment]
Hey @ValentinCrochemore 

Yeah that inline css should be moved to regular css so that it's easier to override.

For the timebeing can you try 
````
.data-dz-thumbnail{
   object-fit: dynamic!important;
}
````

**Comment by ValentinCrochemore** [comment]
OK thanks !

I had to do that : 

```
[data-dz-thumbnail=''] {
  object-fit: cover !important;
}
```
Because I don't have a class but it works.
