### ISSUE TITLE
Notification before delete a file

### ISSUE THREAD

**Issue by sowinski** [rowanwins/vue-dropzone#423]
Hi,

If I click on an image the file will be deleted directly.
But I want to implement an bootstrap modal with a question "Do you really want to delete the file? Yes or No"

Where is the place to implement this logic?

**Comment by rowanwins** [comment]
Hi @sowinski 

It doesn't look like dropzone has an event for `beforeDelete` (or something like that) so we'd probably need to get some changes made upstream to be able to do that...

**Comment by vrajroham** [comment]
@sowinski There is a way to show confirmation box before deleting the image. I'm less confident about the bootstrap modal, but the following approach will help you till some instinct.

Add `dictRemoveFileConfirmation` key to your `dropzoneOptions` in `data` as below,

```javascript
dropzoneOptions : {
    otherKey: valuePairs,
    addRemoveLinks: true,
    dictRemoveFileConfirmation:  "Are you sure? You want to remove this image?",
}
```

Thanks

**Comment by sowinski** [comment]
> @sowinski There is a way to show confirmation box before deleting the image. I'm less confident about the bootstrap modal, but the following approach will help you till some instinct.
> 
> Add `dictRemoveFileConfirmation` key to your `dropzoneOptions` in `data` as below,
> 
> ```js
> dropzoneOptions : {
>     otherKey: valuePairs,
>     addRemoveLinks: true,
>     dictRemoveFileConfirmation:  "Are you sure? You want to remove this image?",
> }
> ```
> 
> Thanks

Thank you, this works fine. But I need to write some javascript code to open a modal.

**Comment by juanca2626** [comment]
I need to customize that confirm that it brings by default when I use dictRemoveFileConfirmation how could I use a custom bootstrap popup for example?

**Comment by Yogerlan** [comment]
> I need to customize that confirm that it brings by default when I use dictRemoveFileConfirmation how could I use a custom bootstrap popup for example?

```javascript
Dropzone.confirm = customConfirm;

var customConfirm = function (question, accepted, rejected) {
    // The confirmation text (h5)
    $("#confirm-question").innerHTML = question;

    // The accept button (button)
    $("#confirm-accept").on("click", function () { accepted(); });

    // Show the modal
    $("#my-modal").modal({ show: true });
};
```
