### ISSUE TITLE
library compile error - rollup -c -w

### ISSUE THREAD

**Issue by trueChazza** [rowanwins/vue-dropzone#425]
![selection_004](https://user-images.githubusercontent.com/20368025/53478693-4ec10700-3adc-11e9-955d-5d2b833143f4.png)

Forked repo, cloned and installed dependencies. Running yarn dev / build produces this error.

What is this refering to? I'm intending to submit a PR, however error is preventing this.

**Comment by rowanwins** [comment]
Hi @trueChazza 

Sorry for the slow reply. I've just run an update on some of the dependencies thanks to #400 - perhaps give it another go now if you're still interested in submitting a PR.

Cheers

**Comment by trueChazza** [comment]
Thankyou @rowanwins for the great library. I will give it another go and submit PR

**Comment by rowanwins** [comment]
Hi @trueChazza , just pushed up a commit with everything now lined up so now would be a great time for a PR :)
