### ISSUE TITLE
Wrong version of dropzone dependency

### ISSUE THREAD

**Issue by 2Pacalypse-** [rowanwins/vue-dropzone#426]
Hi, there's something very confusing going on in this library and its dependency of the `dropzone` library. In the commit where the last version was released `3.5.2`, `dropzone` dependency was updated to `^5.5.1` (https://github.com/rowanwins/vue-dropzone/commit/ed8c3f847bd446f24acbb966fd63d7bc58b4e85c#diff-b9cfc7f2cdf78a7f4b91a753d10865a2R56). Which is the latest version of the `dropzone` library, so all should be good.

However, after closer inspection of what's actually published on npm for this library (https://unpkg.com/vue2-dropzone@3.5.2/dist/vue2Dropzone.js), it seems like it doesn't have the latest version of `dropzone` bundled. This can be seen by inspecting this line in the `dropzone` library:
https://gitlab.com/meno/dropzone/blob/master/src/dropzone.js#L1514

As you can see that check starts with `if (this.options.maxFilesize ...)` which is missing in the previous versions, and it's missing in the `vue2-dropzone`'s version of the `dropzone` dependency. Which is weird because this change was added in the `5.5.1` version of the `dropzone` library, which the `vue2-dropzone` library has written in the `package.json`.

Did you perhaps forget to run `npm install` after updating the `dropzone` dependency and before publishing?

**Comment by rowanwins** [comment]
HI @2Pacalypse- 

Good pickup - i suspect that was my fault. I'll just do a quick check on things and try and get a release out in the next day or so.

**Comment by bcorcoran** [comment]
@rowanwins Update on this?

**Comment by rowanwins** [comment]
Hi @2Pacalypse- & @bcorcoran 

Sorry for the delay, I've just republished as v`3.5.3` , let me know if you have any probs.

**Comment by mateo2181** [comment]
@2Pacalypse- getting same error

**Comment by filipac** [comment]
@2Pacalypse- me too

**Comment by filipac** [comment]
@rowanwins 3.5.3 is broken

**Comment by webafra** [comment]
getting same error

**Comment by 2Pacalypse-** [comment]
> getting same error
> Version : 3.5.2 & 3.5.3

`3.5.2` is not broken (in this way at least; it still has the original bug of this issue). You most likely have `^3.5.2` written in your `package.json` which makes it install `3.5.3`.

**Comment by dexterBHES** [comment]
> getting same error
> Version : 3.5.2 & 3.5.3

I've test 3.5.2 and I'm having the same error as @2Pacalypse-

**Comment by mateo2181** [comment]
v. 3.5.2 works fine. In package.json you need to set "vue2-dropzone": "3.5.2".

**Comment by rowanwins** [comment]
Hi @mateo2181 @dexterBHES @2Pacalypse- @webafra @filipac 

I've just released vue2-dropzone@3.5.4 - I think this resolves the issue (fingers crossed)

**Comment by rowanwins** [comment]
And `3.5.5-alpha.0` is now out because 3.5.4 didn't work :(

**Comment by rowanwins** [comment]
Now out as v3.5.5

**Comment by 2Pacalypse-** [comment]
Hi, sorry to do this to you, but it seems like the `dropzone.js` CSS is not bundled correctly after this latest update :D

So the `vue2Dropzone.min.css` only contains CSS that is declared in the `vue2-dropzone` library, but it doesn't contain CSS from the `dropzone.js`.
