### ISSUE TITLE
Progress bar not updating correctly

### ISSUE THREAD

**Issue by bernisnukic** [rowanwins/vue-dropzone#428]
No matter what size of a file I upload the progress bar goes to 100% in less than a second. The file continues to upload normally and a success event is fired when the file finishes uploading.

I have tried to console log vdropzone-upload-progress and the progress value always goes from 0 to 100 in less than a second.

**Comment by Floriskoch** [comment]
@bernisnukic Did you find a fix for this? I'm having the same problem.

**Comment by bernisnukic** [comment]
@Floriskoch I was developing locally so everything I uploaded finished instantly. If you are having the same problem then I recommend using the chrome dev console to limit your speed to 3g and that will somewhat simulate real world conditions.

**Comment by Floriskoch** [comment]
Thanks for the quick answer. I also added a `transition-delay` on `.dz-progress` which also helps a bit.
