### ISSUE TITLE
Unexpected token (1:1495)

### ISSUE THREAD

**Issue by TuguldurJ** [rowanwins/vue-dropzone#430]
When I upgraded to latest version, I've got an error now.
`  ERROR in ./node_modules/vue2-dropzone/dist/vue2Dropzone.js 1:1495
    Module parse failed: Unexpected token (1:1495)
    You may need an appropriate loader to handle this file type.
    > !function(a,b){typeof exports==='object'&&typeof module!=='undefined'?module.exports=b():typeof`

**Comment by rowanwins** [comment]
Hi @TuguldurJ 

Yeah unfortunately the last release didn't go well due to upgrading some dependencies, I'm currently working on a fix.

**Comment by Hiroshi-Tagami-789** [comment]
Here in Japan, we have the same problem. 
We are hoping fixing it !!

**Comment by rowanwins** [comment]
Hi @TuguldurJ & @Hiroshi-Tagami-789 

I've just released `vue2-dropzone@3.5.4` - I think this resolves the issue (fingers crossed)

**Comment by TuguldurJ** [comment]
It still some as before. Please check it again :)

**Comment by rowanwins** [comment]
Here we go again, this time as `3.5.5-alpha.0`

**Comment by Adan2JP** [comment]
Same bug is happened. maybe, something minimize fails.

**Comment by Adan2JP** [comment]
@rowanwins 
Thank you!
Your library passed for running `yarn dev` on my product.
LGTM.
but, I'm wondering. What cause this error happened ?

**Comment by Adan2JP** [comment]
@rowanwins 
However, I confirmed vue2-dropzone doesn't happen error with `yarn dev`.
Would you update version information to 3.5.5 ?

**Comment by benrolfe** [comment]
> Here we go again, this time as `3.5.5-alpha.0`

When will this fix be released to master?

**Comment by rowanwins** [comment]
Hi @benrolfe 

Have just published it as 3.5.5

**Comment by rowanwins** [comment]
Hi @Adan2JP 

Basically the problem was caused by updating dependencies in #429 . Everything appeared to work, but for some reason the minification in particular caused issues. I'm now using [`terser`](https://github.com/terser-js/terser) instead of `uglify`, during the misfires I also tried [`butternut`](https://github.com/Rich-Harris/butternut) but that also caused some issues.

**Comment by TuguldurJ** [comment]
It works now.
@rowanwins Thank you! 

btw, i've got a css issue which was fine in before. 
![Screen Shot 2019-03-13 at 19 12 45](https://user-images.githubusercontent.com/1275537/54274830-1b927380-45c4-11e9-87ee-3abf28a73832.png)

**Comment by rowanwins** [comment]
Doh @TuguldurJ  - in having to tweak the build tooling I had to adjust the approach used for CSS. Can you perhaps open a new issue specific to the css, and perhaps just double check that it's not the cache or anything like that...

**Comment by TuguldurJ** [comment]
@rowanwins ok let me check for issue.

**Comment by sanna-woo** [comment]
hi!
I can confirm the css problem (was fine before updating ...):

![image](https://user-images.githubusercontent.com/33070450/54276434-a146fc80-458d-11e9-933e-e09874e91f74.png)

**Comment by rowanwins** [comment]
Hi @sanna-woo 

Can you please open a new issue and perhaps describe your config.

Thanks
