### ISSUE TITLE
vdropzone-error triggered before vdropzone-files-added if maxfilesize exceeded

### ISSUE THREAD

**Issue by kurbar** [rowanwins/vue-dropzone#432]
If I configure the options to have `maxFilesize` and I upload a file, that exceeds that, then vdropzone-error is triggered before vdropzone-files-added.

**Expected**
vdropzone-files-added is triggered before vdropzone-error.

Not 100% if this a bug or expected behaviour but seems odd to me.

**Comment by rowanwins** [comment]
Hi @kurbar 

`vdropzone-file-added` gets called first, hopefully that should suit your need
