### ISSUE TITLE
Removing a manuallyAddedFile sets a maxFiles to 1 if option was null

### ISSUE THREAD

**Issue by kynetiv** [rowanwins/vue-dropzone#433]
I am programmatically adding files to the dropzone when they exists on the server.

I noticed that if I remove that file in the UI and I try to add another file, dropzone throws the error that maxFiles was exceeded and file is not added.

I believe this is becuase of [this line](https://github.com/rowanwins/vue-dropzone/blob/master/src/components/vue-dropzone.vue#L134)
```js
 this.dropzone.on('removedfile', function(file) {
      vm.$emit('vdropzone-removed-file', file)
      if (file.manuallyAdded) vm.dropzone.options.maxFiles++
    })
```

If I have not set a `maxFiles` option, the default is `null`. However the above code will make that `null`++, and so sets maxFiles to `1`.

Expected behavior:

The plugin should only increment maxFiles if the default option was set and explicitly not === null.

Actual behavior:

The plugin sets a maxFiles even when one doesn't exist when removing a manuallyAdded file.

I'm using  v3.5.2 of this plugin.

Thanks!

**Comment by kynetiv** [comment]
Probably related to #195

**Comment by rowanwins** [comment]
Hi @kynetiv 

Thanks for digging into the source code, the whole `manuallyAddFile` thing has always been a bit brittle. If you've got time to submit a pull request that would be great, otherwise I'll eventually get to it.

Cheers

**Comment by kynetiv** [comment]
Thanks @rowanwins.  I added #435 for the fix to my issue.
