### ISSUE TITLE
Unminified stylesheet missing in `3.4.6`

### ISSUE THREAD

**Issue by DRoet** [rowanwins/vue-dropzone#436]
Hi,

The unminified stylesheet seems to be missing in the `3.4.6` release when using:

```js
import 'vue2-dropzone/dist/vue2Dropzone.css'
```

I can't use the minified version since it messes up the styling ( the `.dropzone` class is somehow overwriting all of the `vue2-dropzone` stuff, like its not being loaded in the correct order)

thoughts?

**Comment by rowanwins** [comment]
Hi @DRoet ,

I've just republished as `3.4.7` which should resolving the ordering of the css. Thanks for the heads up.

**Comment by DRoet** [comment]
fixed, thanks!
