### ISSUE TITLE
`3.5.7` release breaks IE11 usage

### ISSUE THREAD

**Issue by DRoet** [rowanwins/vue-dropzone#437]
Hi again,

just wanted to let you know that the latest release (`3.5.7`) doesn't work in `IE11` when polyfilling. I'm using vue-cli `3.5.1` and added `import '@babel/polyfill'` to my `main.js`. vue2-dropzone version `3.5.2` does work using the same method.

Error thrown in IE11 is:  <https://docs.microsoft.com/en-us/scripting/javascript/misc/expected-colon> but I can't tell you where exactly since the console in IE11 kinda sucks and it is only in the production bundle

Cheers,

Daan

**Comment by rowanwins** [comment]
Thanks for the report @DRoet 

If I understand correctly if you add `import '@babel/polyfill'` to your application code then everything works? If that's correct then do you think it ought to be the responsibility of this library, or should the application be responsible for including `@babel/polyfill`?

Unfortunately (or fortunately!) I'm on mac so testing on IE is quite tricky for me.

**Comment by DRoet** [comment]
including the polyfill worked for version `3.5.2`, but not for the newer version `3.5.7`

**Comment by rowanwins** [comment]
Yeah so there were some slight changes to the build process between those versions, and I didn't realise they had such serious knock-on effects for things.

My preference would be to not include the polyfill as IE11 is very close to end of life, so I suggest we close this and hopefully if others run into it if they search the issues in this repo.

**Comment by shanestillwell** [comment]
Ran  into the same exact problem after upgrading. Broken on IE11.
This error from IE11
```
SCRIPT1003: Expected ':'
```

I'm using [vue-cli](https://cli.vuejs.org/config/#transpiledependencies), the fix was to add this to `vue.config.js`

```
module.exports = {
  transpileDependencies: [
    'vue2-dropzone',
  ],
}
```

This tells Babel to transpile a module in `node_modules` which is generally ignores.

**Comment by duanp0128** [comment]
> Ran into the same exact problem after upgrading. Broken on IE11.
> This error from IE11
> 
> ```
> SCRIPT1003: Expected ':'
> ```
> 
> I'm using [vue-cli](https://cli.vuejs.org/config/#transpiledependencies), the fix was to add this to `vue.config.js`
> 
> ```
> module.exports = {
>   transpileDependencies: [
>     'vue2-dropzone',
>   ],
> }
> ```
> 
> This tells Babel to transpile a module in `node_modules` which is generally ignores.

It works fine in IE11, but throw an error in Chrome:
`vue.runtime.esm.js?2b0e:619 [Vue warn]: Failed to mount component: template or render function not defined.`

**Comment by aniolekx** [comment]
I can confirm I have the same error in IE11, I do not use Vue Cli so in order to transpile it  - I have to copy it to my own vendor folder, which is pretty useless.

Is it possible that this issue will be fixed for IE11?

Is it true that these all packages in node modules should be properly transpiled? 

Thanks.

**Comment by aniolekx** [comment]
In my project I am using webpack encore, and seems that following configuration with includeNodeModules can fix issue:
`    .configureBabel(() => {}, {
        useBuiltIns: 'usage',
        corejs: 3,
        includeNodeModules: ['vue2-dropzone']
    })`

**Comment by kopax** [comment]
What if I have the same error and do not use vuejs?
