### ISSUE TITLE
Dynamic Url - build fails

### ISSUE THREAD

**Issue by RadoslavAngelov** [rowanwins/vue-dropzone#44]
Hello,

I need to pass dynamic url for the dropzone form, because my route contains an ID. This is my code  `<dropzone id="myVueDropzone" url="{{ entityId }}" v-on:vdropzone-success="showSuccess"></dropzone>` , but the build of my js failes, because of this. Is it possible to set dynamic url to the form.

**Comment by andreoliveira56** [comment]
Hi!

I had to call the method 'setOption', like this:

`<dropzone ref="myId"  ....`

`this.$refs.myId.setOption('url', url);`

**Comment by RadoslavAngelov** [comment]
Hi,

I have managed to pass the variable this way. I am passing the property with this syntax 
`<dropzone id="myVueDropzone" :url="url" :maxFileSizeInMB=5 v-on:vdropzone-success="updatePhotos"></dropzone>` . This way I am binding this to a viriable in the $data of the component, so it was my mistake.

**Comment by andreoliveira56** [comment]
Hi! My problem was different, I needed to change the url after the creation of the dropzone component.
Thank you :)

**Comment by rowanwins** [comment]
Sounds like you've got it all sorted @RadoslavAngelov - I'll close the issue but if you continue to have troubles let me know

**Comment by NoelDavies** [comment]
Any ideas why I can't change the url using setOption?

In my component I have:
` <dropzone id="product-images"
                                  ref="productImages"
                                  :url="imageUploadUrl"
                                  :thumbnailHeight="100"
                                  :thumbnailWidth="100"
                                  :autoProcessQueue="false"
                        >
                        </dropzone>`

Later, when a method is fired on my component (after mount) I have the following:
`this.resource.save({id: this.id}, {product: this.product}).then((response) => {
                        this.imageUploadUrl = Routing.generate('app.admin.product.image.add', {id: response.id});
                        this.$refs.productImages.setOption('url', this.imageUploadUrl);
                        console.log(this.$refs.productImages);`

But it won't change it.. Any ideas?

**Comment by vrajroham** [comment]
@NoelDavies Is there any error in console? Did you outputting in console? If yes, then what you got?

what was the out put of `console.log(this.$refs.productImages);` ?
