### ISSUE TITLE
TransformFile method missing

### ISSUE THREAD

**Issue by ArthurConceicao** [rowanwins/vue-dropzone#460]
I'm trying to overide the transformFile method, but it seems that this component are not hooking it to the original dropzoneMethod.

![k](https://user-images.githubusercontent.com/33375414/58953182-13ce0f80-876c-11e9-8418-5ec7b444ca18.png)

**Comment by vrajroham** [comment]
@ArthurConceicao Thanks for reporting. I'll look into it.

**Comment by camdunne** [comment]
Hi @vrajroham I'd like to take this ticket and submit a PR

**Comment by camdunne** [comment]
@ArthurConceicao it looks like you can manually override `transformFile` by using `setOption` in the options object

 `{
  setOption: ('transformFile', function(){})
}`

**Comment by rowanwins** [comment]
This should be passed in as an option
````
  data () {
    return {
      ....
      dropzoneOptions: {
        url: 'https://httpbin.org/post',
        thumbnailWidth: 200,
        addRemoveLinks: true,
        transformFile: function (file, done) {
             // do whatever to the file
             done()
        }
      }
