### ISSUE TITLE
.GIF support

### ISSUE THREAD

**Issue by FeatureSpitter** [rowanwins/vue-dropzone#463]
Dear Rowan,

I noticed that you are filtering file extensions in this line:

https://github.com/rowanwins/vue-dropzone/blob/5f80aedcd0d5dfebed19f78d7ec61ca07e5f6f18/src/components/vue-dropzone.vue#L264

But there is no .gif extension there, although it seems DropzoneJS fully supports GIFs.

Could you add this extension to this condition?

Thanks!

**Comment by FeatureSpitter** [comment]
Created a PR on this, hopeful it solves this issue: https://github.com/rowanwins/vue-dropzone/pull/464

**Comment by ligne13** [comment]
+1 !

**Comment by vrajroham** [comment]
@FeatureSpitter @ligne13 
In the latest release **gif** support has been added.

https://github.com/rowanwins/vue-dropzone/releases/tag/v3.6.0
