### ISSUE TITLE
maxNumberOfFiles & maxFileSizeInMB are ignored

### ISSUE THREAD

**Issue by Shhu** [rowanwins/vue-dropzone#47]
Hi,

I have some trouble with maxNumberOfFiles & maxFileSizeInMB, both are ignored, i dont know why...

![image](https://cloud.githubusercontent.com/assets/2306100/23520614/10333d3e-ff7c-11e6-8c67-11ecef707c79.png)

![image](https://cloud.githubusercontent.com/assets/2306100/23520572/e4e3db02-ff7b-11e6-9a1e-9848baebc924.png)

Other props (ref, url, the event success, headers, language) works but those 2 are ignored.

**Comment by rowanwins** [comment]
Gday @Shhu 
The props should be passed through like
```
:max-number-of-files='2'
````

Unfortunantly the whole camelcasing props name thing is a bit annoying.

**Comment by Shhu** [comment]
Hi,

Thanks for your answer @rowanwins !

`:max-number-of-files='2'` works but `:max-file-size-in-mb="200"` doesnt. Did i missed something ?

**Comment by rowanwins** [comment]
Hi @Shhu 

So because of the camelcasing thing you need to do `:max-file-size-in-m-b="200"` which is really stupid, I'll change this in the next release.

Cheers

**Comment by vesper8** [comment]
The names of the parameters have changed.

They are now maxFilesize and maxFiles

This below is how I'm setting the options and it is all working wonderfully

images.js component
```
import Dropzone from 'vue2-dropzone'

Vue.component('image-uploader', {
  components: {
    Dropzone
  },
  data() {
    return {
      dzOptions: {
        dictDefaultMessage: 'Drop your images here or click to choose (at least 192x192px)',
        acceptedFiles: '.jpg,.jpeg,.png',
        maxFiles: 2,
        maxFilesize: 1,
        headers: {'X-CSRF-TOKEN': Laravel.csrfToken}
      },
    };
  },
  methods: {
    'showSuccess': function (file) {
      console.log('A file was successfully uploaded')
    }
  }
});
```

inside my blade template:
```
<image-uploader>

    <dropzone id="ImageUploader" url="/image/upload" :use-custom-dropzone-options=true :dropzone-options="dzOptions" v-on:vdropzone-success="showSuccess">

    </dropzone>

</image-uploader>
```

works perfectly

**Comment by MarcelKendy** [comment]
What is the biggest possible size to maxFilesize?
