### ISSUE TITLE
manuallyAddFile webp format

### ISSUE THREAD

**Issue by sheronov** [rowanwins/vue-dropzone#475]
Please, add support ".webp" format to manuallyAddFile method.

https://github.com/rowanwins/vue-dropzone/blob/5e1468ff9998abdffcc74d0d1a5af061a83afc94/src/components/vue-dropzone.vue#L263

**Comment by vrajroham** [comment]
@sheronov Will add it soon.

**Comment by vrajroham** [comment]
@sheronov In the latest release **gif** support is added. https://github.com/rowanwins/vue-dropzone/releases/tag/v3.6.0

**Comment by vrajroham** [comment]
@sheronov **.webp** files support has also been added.
