### ISSUE TITLE
uglify fails to compile

### ISSUE THREAD

**Issue by fischimglas** [rowanwins/vue-dropzone#477]
if using dropzone, the production build (uglify) fails always.

11:06:36 - error: Optimizing of doc/vendor.js failed. L80876:41936 SyntaxError: Unexpected token punc «(», expected punc «:»
Stack trace was suppressed. Run with `LOGGY_STACKS=1` to see the trace. 
error Command failed with exit code 1.

yarn run v1.7.0

uglify config:
            mangle: true,
            compress: {
                global_defs: {
                    DEBUG: false
                }
            }
        
using:
"babel-brunch": "^6.1.1",
"babel-eslint": "^7.2.3",
"babel-plugin-transform-runtime": "^6.23.0",
"babel-preset-es2015": "^6.24.1"

**Comment by rowanwins** [comment]
Hi @fischimglas 

If possible perhaps try using [terser](https://github.com/terser-js/terser), it's a bit more modern that uglifyjs. Otherwise I think you need to pass the bundled code through babel before compiling.

Hope that helps
