### ISSUE TITLE
Hide filesize from preview box?

### ISSUE THREAD

**Issue by safeimuslim** [rowanwins/vue-dropzone#478]
it is possible to hide filesize from preview box?
![screenshot-www staging240 vm_3002-2019 07 24-14_29_17](https://user-images.githubusercontent.com/12455939/61775947-2c7dac00-ae24-11e9-8142-13f1cbeed7ca.png)

**Comment by rowanwins** [comment]
Hi @safeimuslim 

The easiest option is probably some custom css, something like
````
.vue-dropzone .dz-preview .dz-details .dz-size {
    display: none
}
````

Another option could involve passing through [a custom preview layout](https://www.dropzonejs.com/#layout) although that's a bit more complicated.

Hope that helps
