### ISSUE TITLE
Custom confirm remove image dialogue

### ISSUE THREAD

**Issue by nizzac** [rowanwins/vue-dropzone#479]
In the [dropzone docs](https://www.dropzonejs.com/#configuration) it explains how you can overwrite the default browser confirm dialogues using this bit of code...

```
Dropzone.confirm = function(question, accepted, rejected) {
  // Ask the question, and call accepted() or rejected() accordingly.
  // CAREFUL: rejected might not be defined. Do nothing in that case.
};
```

I've tried to do something similar in the mounted() method of my own vue component that uses vue2-dropzone but can't seem to get it to work,,,

```
mounted() {
    this.$refs.dropzone.dropzone.confirm = function(question, accepted, rejected) {
        console.log('custom confirm');
    }
}
```

Not sure if this is a bug, or whether it's not been implemented into this vue component yet, or whether I'm just being a dumb ass and I'm missing something.

**Comment by rowanwins** [comment]
Hi @nizzac 

From memory some of these options work best when passed through in the original options,

````
dropzoneOptions: {
        url: 'https://httpbin.org/post',
        thumbnailWidth: 200,
        confirm: function (question, accepted, rejected) {
              console.log('custom confirm');
        }
      },
````
I'm not sure they can be set retrospectively...
