### ISSUE TITLE
Can I somehow use getQueuedFiles()

### ISSUE THREAD

**Issue by fmarkos** [rowanwins/vue-dropzone#48]
I have multiple dropzone components in a page with each one having a text area next to it.
I use processQueue: false and intercept each submit button so I can add the text input to the form.
I want to be able to submit the text input even if I have no file selected for upload.
I got an idea from here: [http://stackoverflow.com/questions/33826960/dropzone-js-function-getqueuedfiles-causes-too-much-recursion](http://stackoverflow.com/questions/33826960/dropzone-js-function-getqueuedfiles-causes-too-much-recursion)

`$("#submit-all-"+myDropzone.id).click(function (e) {`
`        console.log('submitting!');`
`        e.preventDefault();`
`        e.stopPropagation();`
`        // myDropzone.$refs.dropzoneEl.processQueue(); // this works when there is an image selected`
`        // if (myDropzone.$refs.dropzoneEl.myDropzone.getQueuedFiles().length > 0) { // this doesn't work`
`        if (myDropzone.getQueuedFiles().length > 0) { // this doesn't work`
`          myDropzone.processQueue();`
`        } else {`
`          myDropzone.sending([]); //send empty`
`        }`
`        console.log('submited!');`
`      });`

In both my attempts I get:
Uncaught TypeError: myDropzone.$refs.dropzoneEl.getQueuedFiles is not a function
and
Uncaught TypeError: myDropzone.getQueuedFiles is not a function
Some help please?

**Comment by rowanwins** [comment]
Hi @fmarkos 

I have not exposed a `getQueuedFiles` method although it exists in the original dropzone methods, I'd happily accept a pull request for this otherwise I'll try to get it added some time this week.

Cheers

**Comment by rowanwins** [comment]
Available in npm v2.2.6 thanks to @vrajroham
