### ISSUE TITLE
Unable to prefill saved files in vue2 dropzone 

### ISSUE THREAD

**Issue by eakenbor** [rowanwins/vue-dropzone#481]
I am unable to initialize my vue2 dropzone with an array of files obtained from the database. I want all the previously uploaded files to be retrieved back upon reloading the page and then rendered in the vue2 dropzone. Afterwards, the uploaded files should be able to be removed or new files added. Here is part of my code:

<vue-dropzone
            ref="pictures"
            :options="dropzoneOptions"
            @vdropzone-sending="(file, xhr, formData) => sendingEvent(file, xhr, formData)"
          ></vue-dropzone>

  mounted() {
      //Get an array of files to render in vue2 dropzone
      axios
      .get(`/myFiles}`)
      .then(res => {
        this.$refs.pictures.manuallyAddFile(res.files)
      })
      .catch(error => console.log(error));
  } 

Please can someone advise me on what I am doing wrongly or is it not a possibility with the vue2 dropzone? Thanks.

**Comment by rowanwins** [comment]
Hi @eakenbor 

`manuallyAddFile` takes a single file, not an array of files, see the [example here](https://rowanwins.github.io/vue-dropzone/docs/dist/#/manual)
