### ISSUE TITLE
is addRemoveLinks reactive ?

### ISSUE THREAD

**Issue by mdieudonne** [rowanwins/vue-dropzone#485]
Hi,
Thank you for the great work.

Not an issue, but... is addRemoveLinks reactive ?

Depending on a props, I enable() or disable() myVueDropzone in my view (Edition or RO mode)
`this.$refs.myVueDropzone.enable()`

But when disabled, myVueDropzone still shows removal links and allows deletion.

Could you let me know how I can manage to enable/disable removeLinks too?

No luck trying:
`this.$refs.myVueDropzone;.setOption('addRemovedLinks', false)`

Thx a bunch,
Michael

**Comment by rowanwins** [comment]
Hi @mdieudonne 

Sorry for the slow reply, nope it's not reactive

I'd perhaps try applying some css on your disable method, something like 
````
.dz-remove {
    visibility: hidden;
}
````

Hope that helps
