### ISSUE TITLE
Ajax Request Cancelled.

### ISSUE THREAD

**Issue by rahulpatel033** [rowanwins/vue-dropzone#487]
I have Vue SPA, when I upload multiple files and change the route in Vue, the request gets canceled. Let's say I'm uploading 10 HD images. It will take time meanwhile I will redirect the user to another page. When I do redirect, that request gets canceled.

**Comment by rowanwins** [comment]
Hi @rahulpatel033 

Setting `:destroy-dropzone="false"` works
