### ISSUE TITLE
AWS S3: `sendFileToServer: false` causes `MalformedXML` error on S3 Request

### ISSUE THREAD

**Issue by sanscheese** [rowanwins/vue-dropzone#493]
I am uploading files to S3.

If I have `sendFileToServer: true` everything works fine for the upload to S3. If changing to `false`, as I don't want to send to any of my own servers, it's causing an error on the S3 upload:

```xml
<?xml version="1.0" encoding="UTF-8"?>
  <Error><Code>MalformedXML</Code>
  <Message>The XML you provided was not well-formed or did not validate against our published schema</Message>
  <RequestId>*******HASHEDCODE***********</RequestId>
  <HostId>*******HASHEDCODE***********</HostId>
</Error> 
```

**Comment by hellerbenjamin** [comment]
I'm running into the same and have been troubleshooting the last few days. I have not found a solution yet.

**Comment by hellerbenjamin** [comment]
Additionally what I'm seeing is that if `sendFileToServer: true` then request gets switched from PUT to POST even if the method is specified in the vue dropzone options. In that case I run into a 403 from AWS. This, of course, might be a configuration problem on my bucket, but I haven't been able to find the issue with it yet.

**Comment by sanscheese** [comment]
Issue for me was I had `method: 'PUT'` in the dropzoneOptions. Updated to be `method: 'POST'` and is working properly now.

@hellerbenjamin Dropzone will make a POST request to S3. So that's correct and, is likely a config issue, check:
- S3 Bucket (CORS config)
- IAM Policy for the AWS account used to generate the signed url  
- Ensure your  endpoint of  your URL signer responds with the the correct object for handling a POST request to S3 (as in the docs https://rowanwins.github.io/vue-dropzone/docs/dist/#/aws-s3-upload).

Good luck!

**Comment by hellerbenjamin** [comment]
Just to make sure I understand, the PUT method isn't available with the aws feature?
