### ISSUE TITLE
I have problem with vdropzone-removed-file

### ISSUE THREAD

**Issue by cvhainb** [rowanwins/vue-dropzone#499]
Hello,

This is my dropzone:

`<vue-dropzone id="vueDropzoneUpload" ref="vueDropzoneUpload" :options="dropzoneOptions" @vdropzone-removed-file="vdropzoneRemoveFile" @vdropzone-mounted="vdropzoneMounted"></vue-dropzone>`

When I click "Remove File" link, it will call this method:

```
vdropzoneRemoveFile(file, error, xhr) {
            //console.log(file)
            this.$store.dispatch('deleteProductImage', file.id).then(response => {
            }).catch(error => {
                let message = error.response.data.message;
                $.each(error.response.data.errors, function(i, e){
                    $.each(e, function(index, msg){
                        message += '<p class="mb-0">' + msg + '</p>';
                    })
                })
                this.$noty.error(message);
            });
        },
```
Everything works fine. Now, when I back the listing, this method vdropzoneRemoveFile will be call again and all of images were deleted although I have not clicked any "Remove File" from images. 

This is what happened: 

> - I click edit post id 1, this post has 3 files: 1.jpg, 2.jpg, 3.jpg
> - I click "Remove File" 3.jpg, everything works fine here. 
> - Then I will back the listing page, the vdropzoneRemoveFile will be call and remove 1.jpg, 2.jpg (problem here).

The listing page does not use vue dropzone.

Please advise. Thank you so much.

**Comment by devkea** [comment]
Same problem, did you solved that?

upd: i got it, **destroyDropzone** to **false**
