### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by iamwo0** [rowanwins/vue-dropzone#5]
After I install it in my project by npm , fellow the usage list   : 
import Dropzone from 'vue-dropzone/lib/Dropzone'
but I can't find the right file,
I change it to : 
import Dropzone from 'vue-dropzone/VueDropzone'
and go on,then I run my project , I get error with : 
Uncaught (in promise) ReferenceError: url is not defined(…)
but I set the url attr like this 
<dropzone id="myVueDropzone" url="https://httpbin.org/post"></dropzone>
could you please help me ?

**Comment by rlambertsen** [comment]
Show us some more code? There could be something else going on... Here is my code that works
`import Dropzone from 'vue2-dropzone'
export default{
  components: {
    Dropzone
  },
  methods: {
    'success': function (file, response) {
      console.log('A file was successfully uploaded')
      console.log(response)
    },
    'removed': function (file, error, xhr) {
      console.log(file)
    }
  },
  data: function () {
    return {
      post: {
        content: 'Article Content Here',
        title: null
      }
    }
  }
}`

**Comment by rlambertsen** [comment]
Show us some more code? There could be something else going on... Here is my code that works
HTML
```
<dropzone id="myVueDropzone" url="some-url" v-on:vdropzone-success="success" v-on:vdropzone-removedFile="removed"></dropzone>
```
JS
```
import Dropzone from 'vue2-dropzone'
export default{
  components: {
    Dropzone
  },
  methods: {
    'success': function (file, response) {
      console.log('A file was successfully uploaded')
      console.log(response)
    },
    'removed': function (file, error, xhr) {
      console.log(file)
    }
  },
  data: function () {
    return {
      post: {
        content: 'Article Content Here',
        title: null
      }
    }
  }
}
```
Take note that this is the vue@2.0 versions, but it worked the same for version vue@1. Hope that helps

**Comment by rowanwins** [comment]
Thanks for chiming in here @rlambertsen 

@iamwo0 - so I take it your using the vue 2 version of the component with Vue 2, bit of an obvious question but always worth asking :)  Following Rylan's instructions above should get you going but let us know if you continue to run into trouble.
