### ISSUE TITLE
Cannot import css from dropzone package when build

### ISSUE THREAD

**Issue by rlatkn** [rowanwins/vue-dropzone#50]
I tried to use vue2-dropzone with Nuxt.js (with SSR)
When i imported source file `src/index.vue`, and started build, i got error: 
`Cannot find module "-!../../../../../../../usr/local/lib/node_modules/nuxt/node_modules/css-loader/index.js`
![2017-03-08_16-46-15](https://cloud.githubusercontent.com/assets/16562108/23706334/d2470efe-041e-11e7-87a1-231bdffbf267.png)

I try to change import dropzone.css in `src/index.vue` from `../node_modules/dropzone/dist/dropzone.css` to `~dropzone/dist/dropzone.css` as it says [documentation for webpack less-loader](https://github.com/webpack-contrib/less-loader#imports) and it works

**Comment by rowanwins** [comment]
Resolved by pull request #51 , released to npm as v 2.2.4
