### ISSUE TITLE
Pre-loading images into dropzone

### ISSUE THREAD

**Issue by Timtech4u** [rowanwins/vue-dropzone#508]
Hi, I would like to be able to  pre-load images (previously uploaded by the dropzone itself) back into the dropzone.

Use case:
I'm implementing a CRUD functionality and I need to load users image back in if they want to update.

**Comment by AlexanderYW** [comment]
Sound like you're looking for this
https://rowanwins.github.io/vue-dropzone/docs/dist/index.html#/manual

**Comment by Timtech4u** [comment]
Yup, found it! Thanks
