### ISSUE TITLE
Reset and remove preview 

### ISSUE THREAD

**Issue by adamrifau** [rowanwins/vue-dropzone#517]
i would like to reset and remove the preview or disable the upload form after upload, so far i've tried 
this.$refs.VueDropzone.disable() 
but doesn't take any effect .

**Comment by Alexisgt01** [comment]
hi, 

Maybe to use v-if ?

**Comment by adamrifau** [comment]
i was looking for the option previewsContainer by setting it false and reactivating worked for me 
thanks
