### ISSUE TITLE
vDropzoneFilesAdded - files.accepted is undefined 

### ISSUE THREAD

**Issue by Alexisgt01** [rowanwins/vue-dropzone#518]
Hi, 

Here is my script : 

**On the dropzone component**
```
vdropzoneFilesAdded(file) {
     this.$emit('filesAdded', file);
 },
```

**On the parent**

```
<dropzone v-on:filesAdded="filesAdded" v-on:DropzoneQueueComplete="DropzoneQueueComplete" ref="dropzone" v-if="fileInterne" :url="url"></dropzone>

...
filesAdded(files) {
	files.forEach((el) => {
		console.log(el);
		if (el.accepted) {
			this.medias.push({
				old_name: el.name,
				file: el.name,
			})
		}
	})
},
```

`el.accepted` is undefined, anyone knows why?

Thank you

**Comment by rowanwins** [comment]
I believe that `accepted` is  only set to true after the file is successfully uploaded, so when the file is first added it doesn't yet have that property. 
Hope that helps
Rowan
