### ISSUE TITLE
Brave Browser doesn't seem to show the base64 src when depolyed to staging

### ISSUE THREAD

**Issue by sitefinitysteve** [rowanwins/vue-dropzone#519]
Client tested with brave browser, I can replicate... but on dev (left image) it's there, on staging though, src(unknown).  The files are clearly on the server and the file added event shows me status "added" and the proper base64 data.

![image](https://user-images.githubusercontent.com/1542376/71016884-cb50c080-20c3-11ea-84e2-5da10ddb1e8d.png)

Submission seems just fine, the files are there to process, but the client end doesn't seem to render the images (well there's no src so of course not eh).

**Comment by mandaputtra** [comment]
di you try using `manuallyAddFile`

**Comment by sitefinitysteve** [comment]
I will give it a go see what I can work out, I'll close this for you, happy holidays :)
