### ISSUE TITLE
[Question] Can we add files programmatically, without the interface?

### ISSUE THREAD

**Issue by e0lithic** [rowanwins/vue-dropzone#520]
Hi,

Is there a way where we can add files to vue-dropzone through code ( without the browser dialogue for drag and drop), so that it automatically starts uploading and triggering all success and error events.

I explored the existing methods but the **manuallyAddFile** seems to only create a mock file for display and doesn't initiate the auto upload events.

Thanks and great work!

**Comment by rowanwins** [comment]
Sorry for the slow reply @e0lithic

You can probably do something with the `processFile(file)` method exposed by dropzone.
````
this.$refs.myVueDropzone.dropzone.processFile(myRealFile)
````
Unfortunately there isn't much documented on the dropzone website about how it works but hopefully it gets you on your way.

**Comment by e0lithic** [comment]
Thanks for the pointer.
