### ISSUE TITLE
How can we change form-data param name

### ISSUE THREAD

**Issue by akvaliya** [rowanwins/vue-dropzone#522]
I have an api which uses form-data name images instead of file.

How can i add file in form data using this name?

**Comment by rowanwins** [comment]
You should probably look at the [additionalParams example](https://rowanwins.github.io/vue-dropzone/docs/dist/#/additionalParams)

Something like
````
methods: {
      sendingEvent (file, xhr, formData) {
        formData.append('images',  formData.name);
      }
    }
````
