### ISSUE TITLE
How can i change default params to make it work with Active Storage?

### ISSUE THREAD

**Issue by Bac3Phi** [rowanwins/vue-dropzone#523]
I use vue2 component with Rails 5.2
i called:
```
<vue-dropzone
    ref="myVueDropzone"
    id="dropzone"
    class="profile_drop_block"
    :options="dropzoneOptions"
    v-on:vdropzone-sending="sendingEvent"
  ><vue-dropzone>
```

Option:
```
      dropzoneOptions: {
        url: "/rails/active_storage/direct_uploads",
        thumbnailWidth: 420,
        thumbnailHeight: 420,
        maxFiles: 1,
        addRemoveLinks: true,
        headers: { "X-CSRF-TOKEN": $("meta[name=csrf-token]").attr("content") }
      }
```
when it submit, it will send param:

> Started POST "/rails/active_storage/direct_uploads" for ::1 at 2020-01-07 14:24:08 +0700
> Processing by ActiveStorage::DirectUploadsController#create as JSON
>   Parameters: {"file"=>#<ActionDispatch::Http::UploadedFile:0x00007fc021340038 @tempfile=#.........">}

but what i expected:

>   Parameters: {"blob"=>{"filename"=>"..................", 
>   "content_type"=>"image/jpeg", "byte_size"=>10762, "checksum"=>"......"}, 
>   "direct_upload"=>{"blob"=>{"filename"=>".......", 
>   "content_type"=>"image/jpeg", "byte_size"=>10762, "checksum"=>......}}}

how can i make it work with direct upload for active storage?

**Comment by rowanwins** [comment]
This sounds like a server-side problem sorry @Bac3Phi
