### ISSUE TITLE
Submit file with other input parameter

### ISSUE THREAD

**Issue by asnawisaharuddin** [rowanwins/vue-dropzone#53]
Hi, 

Does anyone know how to submit the files with other input paramaters as well? I have a form with input name, description etc...how to submit all this input together to the api?

**Comment by rowanwins** [comment]
Hi @asnawisaharuddin 

If you hook into the `sending` event you should be able to achieve what you want. You should be able to hook into whatever form data you are interested in and add it to the xhr request.

eg
````
<template>
    <div>    
      <dropzone id="myVueDropzone" url="https://httpbin.org/post" v-on:vdropzone-sending="sendingEvent"></dropzone>
  </div>
</template>

<script>
  import Dropzone from 'vue2-dropzone'

  export default {
    name: 'MainApp',
    components: {
      Dropzone
    },
    methods: {
      'sendingEvent': function (file, xhr, formData) {
         doSomethingInHere()
      }
    }
  }
</script>
````

**Comment by asnawisaharuddin** [comment]
Thanks @rowanwins  !

**Comment by iamsajidjaved** [comment]
Please watch this video: [https://youtu.be/y8ykRE1pChI](https://youtu.be/y8ykRE1pChI)
This channel has very good content related to this vue component. This issue is covered in this video
