### ISSUE TITLE
Access parameters of Events.

### ISSUE THREAD

**Issue by yabuking84** [rowanwins/vue-dropzone#535]
How do we access the parameters of events? 
Ex. vdropzone-removed-file(file, error, xhr)

In my component:
````
<vue2-dropzone  @vdropzone-removed-file="vdz_removed"/>
````
In my script (methods): 
````
vdz_removed(file, error, xhr) {
    console.log('vdz_removed file = ', file);
    console.log('vdz_removed error = ', error);
    console.log('vdz_removed xhr = ', xhr);
}
````
Is this correct? Also if I want to add a custom parameter how do  still access the default parameters? 

like: <vue2-dropzone @vdropzone-removed-file="vdz_removed(ile, error, xhr, custom_arg)"/>

**Comment by rowanwins** [comment]
Unfortunately the  `@vdropzone-removed-file` event only receives the file as an argument, error and xhr are not available - this is a limitation of the base dropzone library. You're also not able to pass through custom arguments.

Sorry I can't help more with that one
