### ISSUE TITLE
Exposing processFile method

### ISSUE THREAD

**Issue by Khrisseh1995** [rowanwins/vue-dropzone#536]
Hi there, I just want to thank you for the great package.

I was wondering if there was an explicit reason for not exposing the processFile() method that is available with dropzone.

If there is no issue with this, is this something that would be accepted if I were to do it in a pull request?

**Comment by rowanwins** [comment]
Hi @Khrisseh1995 

You should be able to access this using

````
<vue-dropzone ref="myVueDropzone"></vue-dropzone>

inWhateverMethod () {
    this.$refs.myVueDropzone.dropzone.processFile()
}
````

Hope that helps
