### ISSUE TITLE
Remove the thumbnail with Custom Styling

### ISSUE THREAD

**Issue by LukeDooms** [rowanwins/vue-dropzone#550]
I'm referring to your online demo's.
When using the Custom Styling, we cannot remove the file from the dropzone anymore.
Is this a bug? Or is their a reason why is cannot be implemented?

**Comment by rowanwins** [comment]
Hi @LukeDooms 

The suggested approach in[ dropzonejs doco](https://www.dropzonejs.com/#layout) is to use something like

````
<img src="removebutton.png" alt="Click me to remove the file." data-dz-remove />
````
`data-dz-remove` is the critical part apparently so presumably you could swap out the img element for a button or whatever and then style accordingly with css.

Hope that helps

**Comment by LukeDooms** [comment]
Thank you, works like a charm.
Any way to restore the Default Message in the Custom Styling demo?

**Comment by LukeDooms** [comment]
Found it myself!
Just put a class="dz-message" in the vue dropzone component, while setting :useCustomSlot=true
Thanks for this wonderful product.
