### ISSUE TITLE
AWS upload - why is it followed by a post to the dropzone url

### ISSUE THREAD

**Issue by jbaseas** [rowanwins/vue-dropzone#551]
I am using the AWS S3 upload and everything works just fine - what I do not get is why after every successful upload (get presigned url, send to S3, get success response), an extra post request to the dropzoneOptions URL is executed. 
The file is already uploaded in the S3 bucket so what is the need for an extra endpoint and an extra post request to it? 
Removing the url from the dropzone options seems to break everything. Is there something I am missing? Is there a way to avoid the extra post?

Thanks

**Comment by ayushishah-easternts** [comment]
@jbaseas : Hi we are facing the same concern? Can you please guide us? @mukeshghodela-easternts

**Comment by jbaseas** [comment]
Here are the dropzone options I ended up with:
`  dropzoneOptions: {
   
                method: 'POST',
                
                url: 'http://mock.upload', //no server upload will be executed, only S3

                parallelUploads: 0,

                uploadMultiple: false,

                maxFilesize: 10,

                addRemoveLinks: false,

                resizeWidth: 1600,

                resizeHeight: 1600,

                resizeMimeType: 'image/jpeg',

                timeout: 200000,

                acceptedFiles: 'image/jpeg,image/png',

                createImageThumbnails: false,

                headers: {

                    //required for aws cors to work

                    'Cache-Control': null,

                    'X-Requested-With': null

                }

            },`
and the dropzone component init
`<vue-dropzone

                                                ref="MediaDropzone"

                                                id="Media__dropzone"

                                                class="dropzone__elements"

                                                :options="dropzoneOptions"

                                                @vdropzone-files-added="vfilesAdded"

                                                @vdropzone-error="verror"

                                                @vdropzone-sending="vsending"

                                                :useCustomSlot="true"

                                                :awss3="awss3"

                                                @vdropzone-s3-upload-error="s3UploadError"

                                                @vdropzone-s3-upload-success="s3UploadSuccess"

                                                data-testId="photos_dropzone"

                                            >`
                                            
some are irrelevant to the original problem but I do not quite remember what was the exact setting that fixed this issue. I hope this helps anyway.

**Comment by mukeshprajapati-kombee** [comment]
@jbaseas Thanks :)
