### ISSUE TITLE
thumbnail of image has a white box protruding 

### ISSUE THREAD

**Issue by JamaicanFriedChicken** [rowanwins/vue-dropzone#557]
Hey I'd like to ask how can I resolve this issue of fixing the thumbnail of my images being uploaded. I noticed there is a white box protruding depending on various screen sizes such as these pictures below. 
![Screenshot from 2020-06-04 13-31-57](https://user-images.githubusercontent.com/31347338/83801157-460b9900-a66e-11ea-9021-ed294444ec06.png)

![Screenshot from 2020-06-04 14-12-22](https://user-images.githubusercontent.com/31347338/83801163-47d55c80-a66e-11ea-8d2f-178bfa58b198.png)

I have tried resizing the thumbnails but the white box keeps showing up on the bottom of the image. Any suggestions?

**Comment by rowanwins** [comment]
Can you show your configuration and any css you're using?

**Comment by JamaicanFriedChicken** [comment]
Sure thing! 

The configuration for my dropzone 

    public dropzoneOptions: object = {
       url: '/',
       method: 'POST',
       maxFileSize: 2, // MB
       thumbnailWidth: 100,
       thumbnailHeight: 50,
       addRemoveLinks: true,
       uploadMultiple: false,
    }



This is the CSS

    @media (min-width: 320px) and (max-width: 414px) {

      .vue-dropzone {
        height: 1em;
        width: 70%;
        padding: 0.5em 0.5em 5.5em 0.5em;
        margin-left: 3em;
        margin-bottom: 1.5rem;
        position: relative;
        cursor: pointer;
        outline: 5px dashed grey;
        outline-offset: -1.5rem;
        background: lightgray;
        color: dimgray;
        font-family: 'Arial', sans-serif;
        letter-spacing: 0.2px;
        transition: 0.2s linear; 
      }
    }


Whenever I adjusted the configurations for the thumbnail sizes, it didn't seem to have affected it. Would I need to increase the height of the dropzone box to avoid this?

**Comment by rowanwins** [comment]
@JamaicanFriedChicken 

There is a `min-height` property which is set to 100px which you need to override with something, eg
````
.dropzone .dz-preview {
   min-height: 10px; 
}
````

Hope that helps

**Comment by JamaicanFriedChicken** [comment]
@rowanwins i have another question Id like to ask, I am currently trying that but it doesnt seem to be working even when i put `!important`. 

I tried targetting it even with CSS but it doesn't like I was able to even adjust any value, am I missing something?
