### ISSUE TITLE
Cannot override CSS

### ISSUE THREAD

**Issue by vitroz** [rowanwins/vue-dropzone#561]
Hi guys, I am having some trouble with positioning the remove file button, from the preview box to a top right position, so it doesnt overlap with any validation message. 
I've tried what was said on this issue from 2017, #42  But I think its not currently valid

What I tried:
```
<vue-dropzone :useCustomSlot=true ref="fileDropzone" id="custom-dropzone" :options="dropzoneOptions">
```
Css
```
.vue-dropzone>.dz-preview .dz-remove{
  font-size: 300px !important;
  background-color: red !important;
}
```
Or
```
#custom-dropzone>.dz-preview .dz-remove{
  font-size: 300px !important;
  background-color: red !important;
}
```
Or 
```
.dz-remove{
  background-color: red;
}
```

I just tried to see if any CSS was applied, but had no success.

Tried the custom styling example from the docs, is that the only way to override css? I just needed to re-position this button (.dz-remove)

**Comment by umutbozdag** [comment]
Do you have scoped attribute in style?

**Comment by vitroz** [comment]
Do not @umutbozdag , but ended up resolving by going with the docs approach, which is using the custom styling
