### ISSUE TITLE
Using dropzoneOptions without a url

### ISSUE THREAD

**Issue by paridhikhaitan** [rowanwins/vue-dropzone#571]
I want to use Vue dropzone without using the url in dropzoneOptions i.e. I do not want to send the uploaded image to any external server (due to security reasons). Is there any way I can use it without using the url field in dropzoneOptions?

**Comment by portikM** [comment]
@paridhikhaitan did you figure out the way to use it without url?

**Comment by vietvh-3042** [comment]
@paridhikhaitan @portikM 
I found a workaround to set url: 'http://localhost'.
I don't know how you deal with this problem
