### ISSUE TITLE
Impossible to remove file in error case

### ISSUE THREAD

**Issue by Xeroxi91** [rowanwins/vue-dropzone#580]
Hi @rowanwins I'm using version 3.6.0
The problem mentioned in issue #438 still persists. 
It has a big impact in user usability. The user can't click the button to remove the file because is behind the error message.

<img width="182" alt="Schermata 2020-10-09 alle 13 34 41" src="https://user-images.githubusercontent.com/49407796/95578465-35ac6600-0a34-11eb-8921-5f3f52e22e21.png">

When do you plan to fix this?
Thanks

**Comment by kossa** [comment]
It works fine, me be problem with the server

**Comment by mklahorst** [comment]
@Xeroxi91 - did you every find a solution to this?

**Comment by Xeroxi91** [comment]
@mklahorst I resolved customizing the dropzone template -.-
