### ISSUE TITLE
prop language doesn't work

### ISSUE THREAD

**Issue by Eder87rh** [rowanwins/vue-dropzone#59]
I found a different way to change the component texts instead that you say in the documentation.

the languange prop never worked for me, i used instead:

:dropzone-options='{"dictDefaultMessage":"new text"}'
:use-custom-dropzone-options="true"

I post this just for another users reference, i think you could post this in the documentation and show more examples.

Have a nice day :)

**Comment by rowanwins** [comment]
Hi @Eder87rh 

The language property works fine for me doing

````
    <dropzone ref="myUniqueID" :language="langObj" id="myVueDropzone" url="https://httpbin.org/post" v-on:vdropzone-success="success"></dropzone>

<script>
  export default {
    data () {
      return {
        langObj: {dictDefaultMessage: 'something'}
      }
    },
````
Let me know if you still have issues

**Comment by Eder87rh** [comment]
I finnaly can make it work with version 2.2.4, thanks! :D
