### ISSUE TITLE
Material icons vs font awesome

### ISSUE THREAD

**Issue by rlambertsen** [rowanwins/vue-dropzone#6]
I think you should use Font Awesome instead as it is more popular. Or if you can make the icon a prop so we can pass either a Font Awesome or Material icon class name to it. Making this plugin more open and friendly. These are my two cents....

**Comment by rowanwins** [comment]
Thanks for the suggestion @rlambertsen - I take your point about what is the best option, I might include an image file in the actual repo to draw on as well as add a class param so that people can use whatever they want. 

PS Happy to accept to pull requests if you're feeling inspired :)

**Comment by rowanwins** [comment]
Gday @rlambertsen 

I've now included an option `useFontAwesome` which will allow you to use font awesome.

Cheers
Rowan
