### ISSUE TITLE
Injected Styles interferring

### ISSUE THREAD

**Issue by RaiserWeb** [rowanwins/vue-dropzone#62]
Is there a way of disabling the injected styles? 

It seems there are css declarations that don't seem to be name spaced, eg

`i{color:#ccc}.dropzone`

**Comment by rowanwins** [comment]
Hi @RaiserWeb 

Hmm I thought all the styles were being nested. If you [look at the css](https://github.com/rowanwins/vue-dropzone/blob/vue2/src/index.vue#L209-L214) for the module everything should be nested under the class `.vue-dropzone`.

If you can provide a snippet of code showing the issue that would be great.

Thanks

**Comment by RaiserWeb** [comment]
Hi @rowanwins 

Thanks for the info. I can see the nested styles in the css. It's strange as on my page, it's outputting the following, which is a non namespaced i declaration. Could it be related to less/sass issue? I am using sass on my project.
`.dropzone:hover{background-color:#f6f6f6}i{color:#ccc}`

The entire css output is
`html{background-color:#f9f9f9}.dropzone{border:2px solid #e5e5e5;font-family:Roboto,sans-serif;color:#777;-webkit-transition:background-color .2s linear;transition:background-color .2s linear}.dropzone:hover{background-color:#f6f6f6}i{color:#ccc}.dropzone .dz-preview .dz-image{border-radius:0}.dropzone .dz-preview:hover .dz-image img{-webkit-transform:none;transform:none;-webkit-filter:none}.dropzone .dz-preview .dz-details{bottom:0;top:0;color:#fff;background-color:rgba(33,150,243,.8);-webkit-transition:opacity .2s linear;transition:opacity .2s linear;text-align:left}.dropzone .dz-preview .dz-details .dz-filename span,.dropzone .dz-preview .dz-details .dz-size span{background-color:transparent}.dropzone .dz-preview .dz-details .dz-filename:not(:hover) span{border:none}.dropzone .dz-preview .dz-details .dz-filename:hover span{background-color:transparent;border:none}.dropzone .dz-preview .dz-remove{position:absolute;z-index:30;color:#fff;margin-left:15px;padding:10px;top:inherit;bottom:15px;border:2px solid #fff;text-decoration:none;text-transform:uppercase;font-size:.8rem;font-weight:800;letter-spacing:1.1px;opacity:0}.dropzone .dz-preview:hover .dz-remove{opacity:1}.dropzone .dz-preview .dz-error-mark,.dropzone .dz-preview .dz-success-mark{margin-left:-40px;margin-top:-50px}.dropzone .dz-preview .dz-error-mark i,.dropzone .dz-preview .dz-success-mark i{color:#fff;font-size:5rem}`

**Comment by rowanwins** [comment]
Glad you got it sorted.

Cheers

**Comment by RaiserWeb** [comment]
Hi @rowanwins 
Actually, when I install the package via
`npm install vue2-dropzone@^2.0.0`

The /src/index.vue file contains non-namespaced style, eg

`<style>
  @import url('../node_modules/dropzone/dist/dropzone.css');
  @import 'https://fonts.googleapis.com/css?family=Roboto';

  html{
    background-color: #F9F9F9;
  }`

Is this an npm version issue?

**Comment by rowanwins** [comment]
THere was an issue with an earlier version, what version is present in your package.json?

**Comment by RaiserWeb** [comment]
Ah, thanks.
I had     "vue2-dropzone": "^2.0.0",
But have changed to     "vue2-dropzone": "^2.2.5", and the issue is fixed

Thanks for your help, and the package.
