### ISSUE TITLE
paramName prop ignored / not set

### ISSUE THREAD

**Issue by dvatp** [rowanwins/vue-dropzone#63]
My application backend requires a different file parameter name from the default ('file'). When I attempt to pass in the paramName to the dropzone component requests to the server continue to send the file with the parameter name set to 'file'.  My custom paramName is ignored.

Pulling up vue dev-tools and browsing the component tree I can see that my dropzone component "props" section contains all the other props I'm supplying as well as the default settings I see in the vue-dropzone code that I don't supply / override.  What I don't see is any reference to the prop called "paramName".  I mean, it's not that paramName exists and it's undefined -- the prop is not shown at all.  Which is strange particularly because the default of 'file' should have set it even in the case where my input is not being accepted for some reason.

I've walked the vue-dropzone .vue file and verified that the paramName prop is present / supported and the mounted() hook correctly assigns it to the Dropzone object instantiated at that time.  So I have no idea why this is not working, while every other prop is working / defined as expected.

I installed from npm and am currently using version 2.2.4.

**Comment by rowanwins** [comment]
Hi @dvatp

Unfortunantly I haven't released that new functionality to npm yet as it was only incorporated the other day. I'll try and get it released in the next day or two, sorry for the inconvience.

**Comment by rowanwins** [comment]
Hi @dvatp 

I've just published the new version to npm as v2.2.5

I'll close the issue but let me know if you continue to have issues.
