### ISSUE TITLE
Readme demo code

### ISSUE THREAD

**Issue by kakulukia** [rowanwins/vue-dropzone#64]
when just running the demo code from the readme i get the following error:

You are using the runtime-only build of Vue where the template compiler is not available. Either pre-compile the templates into render functions, or use the compiler-included build.

what does that mean?
Im using the the App.vue inside a new app defined via

    vue init browserify-simple testapp

**Comment by rowanwins** [comment]
Hi @kakulukia 

I suspect when you initiated your project using the vue-cli you may have chosen the wrong build type
https://vuejs.org/v2/guide/installation.html#Explanation-of-Different-Builds

I suspect you chose the runtime only build which is why you're getting the error. 

Hope that helps

**Comment by kakulukia** [comment]
thx!
I didnt actively chose anything, but probably the template is not right for me. I dont have time to test that now, but I guess you are right, so im closing the ticket.
