### ISSUE TITLE
How to pass a Laravel CSRF token to the component

### ISSUE THREAD

**Issue by iamgoodbytes** [rowanwins/vue-dropzone#69]
Hi! What a great component this is, that's for sure.

I'm trying to to get it to work in a laravel project, but I can't seem to pass the CSRF-token. I've tried the following (after looking at one of the solved issues here):

I have the following component:

`<dropzone ref="dropzone" id="dropzone" name="icon" :use-custom-dropzone-options=true :headers="dzHeaders" :dropzoneOptions="dzOptions" url="/domains/seticon" v-on:vdropzone-success="showSuccess"></dropzone>`

I tried passing additional headers first:

```
data() {
            return {
                dzHeaders: {
                    'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
                }
            };
        },
```

When that didn't work, I tried passing the token like this:

```
mounted() {
            var token = $('[name=_token]').val();
            console.log("token: " + token); // prints the correct token
            this.$refs.dropzone.setOption("_token", token);
        },
```

Just to be clear:I have both the meta tag and hidden form field containing the token in my HTML.

This keeps throwing a TokenMismatchException in Laravel, so the token is not getting passed correctly. Would it be possible to point me in the right direction as to what I'm doing wrong?

Thanks a lot for taking the time to help out!

**_UPDATE:_** I found out that I should do the following. Looks like setting headers separately or setting options does not work when using "use-custom-dropzone-options". That settings seem to have a higher priority than the other methods. 

**This works:**

dzOptions: {
                    dictDefaultMessage: '<i class="material-icons">cloud_upload</i><br>Drop your default domain icon here (at least 192x192px)',
                    acceptedFiles: '.jpg,.jpeg,.png',
                    headers: {'X-CSRF-TOKEN': Laravel.csrfToken}
                }

**Comment by anselmobattisti** [comment]
Hi, im with exactly the same problem here!

`      dropzoneOptions: {
        addRemoveLinks:true,
        headers: {
          'Authorization': 'Bearer ' + window.localStorage.getItem('token'),
          'Access-Control-Allow-Origin': '*'
        },`

But this isn't working! 

Some idea?

**Comment by iamgoodbytes** [comment]
If you are using dropZoneOptions, have you set :use-custom-dropzone-options=true ?
If you can, post a more complete code sample showing your component and data

**Comment by rowanwins** [comment]
Hi @iamgoodbytes & @anselmobattisti 

@iamgoodbytes is correct that any the custom options don't work in conjunction with the other component properties at the moment. 

I'm going to see if I can get the custom options object with work with the other component properties but at the moment you need to do something like 
````
<dropzone ref="dropzone" id="dropzone" name="icon" :use-custom-dropzone-options=true :dropzoneOptions="dzOptions" url="/domains/seticon" v-on:vdropzone-success="showSuccess"></dropzone>

dzOptions: {
    dictDefaultMessage: 'cloud_upload  Drop your default domain icon here (at least 192x192px)',
    acceptedFiles: '.jpg,.jpeg,.png',
    headers: {'X-CSRF-TOKEN': Laravel.csrfToken}
}
````

Hope that helps

**Comment by weijinnx** [comment]
You can add hidden input inside dropzone component, like in documentation.
```html
<input type="hidden" name="_token" value="{{ csrf_token() }}">
```
