### ISSUE TITLE
Assigning file container with files on the server

### ISSUE THREAD

**Issue by kyoukhana** [rowanwins/vue-dropzone#8]
I couldn't find any documentation on assigning the drop zone container files.  Lets say you have a update form and your database pulls the image names form the server. Would be nice to see a example of assigning the file container the files that are already on the server.

**Comment by rowanwins** [comment]
If I understand correctly you want to seed the dropzone container with a number of images that have previously been uploaded. If this is the case I'd check out [this answer](http://stackoverflow.com/a/28658667/1979085)

**Comment by kyoukhana** [comment]
Correct but do you have a vue-js example of this?

**Comment by rowanwins** [comment]
No, unfortunately the component does not currently expose the `myDropzone.emit("addedfile", existingFiles[i]);` method, I'd happily accept a pull request though :)

I may get time to implement the functionality myself in the next few weeks.

**Comment by tiboufroulou** [comment]
This works populates the dropzone #myUniqueID with the data coming from retrieveUrl:

data(){
      return {
        shared: window.store,
        dpzone: null,
},
mounted() {
      this.dpzone = this.$refs.myUniqueID.dropzone;
      this.fetchItems();
    },

fetchItems() {
        axios['get'](this.retrieveUrl, { headers: getHeader() } )
          .then(response => {
            for (const image of response.data.data) {
              var mockFile = { name: image.filename, size: 12345, type: 'image/jpeg' };
              this.dpzone.emit("addedfile", mockFile);
              this.dpzone.emit("thumbnail", mockFile, "https://placehold.it/400x400");
              this.dpzone.emit("complete", mockFile);
            }
          })
          .catch(errors => {
            console.log('error: ' + errors);
          });
      },

**Comment by rowanwins** [comment]
This is now available in npm v2.2.6 using the `manuallyAddFile` method. Thanks to @holic-cl for his contributions on making it happen
