### ISSUE TITLE
useFontAwesome doesn't work when using use-custom-dropzone-options

### ISSUE THREAD

**Issue by iamgoodbytes** [rowanwins/vue-dropzone#80]
It seems like useFontAwesome has no effect when using use-custom-dropzone-options=true

Using custom dropzone options ignores the normal attributes and uses the options defined in :dropzoneOptions

Since there is no option useFontAwesome in dropzone itself, there seems to be no way to use the fontAwesome icons when setting use-custom-dropzone-options to true (which sometimes is necessary e.g. when setting CSRF-TOKEN)

**Comment by rowanwins** [comment]
Gday @iamgoodbytes 

That is correct. 

The work around is if you want to set specific properties not available is to use the `setOption(optionname, value)` method. You should be able to do something like 
````
    vm.$refs.myUniqueID.setOption('headers', {'X-CSRF-TOKEN': Laravel.csrfToken})
````
Let me know if that works for you

**Comment by iamgoodbytes** [comment]
Thanks for the suggestion! That might also work. 
What I came up with instead is the following: 

```
dzOptions: {
  dictDefaultMessage: '<i class="fa fa-cloud-upload" aria-hidden="true"></i><br>Some text here',
}
```

That way I can just use the font-awesome icons or any other icons, and still use the custom dzOptions. Works for me, issue can be closed if you ask me.
