### ISSUE TITLE
Publish latest version of repo to npm

### ISSUE THREAD

**Issue by vrajroham** [rowanwins/vue-dropzone#82]
Hi @rowanwins,

Can you please publish current repository to npm? Problem is repository is up to date and did some bug fixes, updated the docs as per new feature but repo is not published to npm yet. So users are getting confused about docs. 

Please publish the latest version to npm and also have a look on pull request about merging vue2 to master.

Thanks buddy :)

**Comment by rowanwins** [comment]
Gday @vrajroham 

I've just published the lastest as v2.2.7

Sorry about the delay 
Rowan
