### ISSUE TITLE
Get count of added files

### ISSUE THREAD

**Issue by neilcarpenter1** [rowanwins/vue-dropzone#83]
I've got maxNumberOfFiles set to 1.

If an image is added, i want to remove any existing image, and add the new image.

At the minute, Im hooking into the fileAdded event, firing the removeAllFiles() method, then wanting to add the new image manually with manuallyAddFile();

This creates a horrible loop, so I need a way to count the number of files added before i trigger the removeAllFiles() method. Is there something already available that I'm missing, or this there currently no way to do this?

**Comment by rowanwins** [comment]
Gday @neilcarpenter1 

You should be able to check out the number of currently added files by doing something like

````
<dropzone ref="myUniqueID" id="myVueDropzone" url="https://httpbin.org/post"></dropzone>

methods: {
    someMethod(){     
           this.$refs.myUniqueID.dropzone.files.length
    }
}
````

Hope that helps

**Comment by neilcarpenter1** [comment]
Gday to you too @rowanwins 

Yeh I came across that so that's the way I'm using now. Thanks.

Another thing is, using manuallyAddFile doesn't add the file to this.$refs.myUniqueID.dropzone.files.length
I'm having to to push()  to that array manually, which isn't a huge thing, but would be nice if it happened automatically.

What do you think?

**Comment by rowanwins** [comment]
Hmm that's a bit annoying isn't it! We'll see if we can work something out.

**Comment by vrajroham** [comment]
@neilcarpenter1 Thanks for pointing the issue. You are right it should be automatically added to `files`.
Will be fixed soon.
Cheers!  :tada:

**Comment by vrajroham** [comment]
@neilcarpenter1 , correct me if I am wrong. manuallyaddFile  is used to add mock file or say dummy file. Behind the scenes mock entries of files are done for preview. Dropzone  doesn't download and add them to preview box or files array.

**mock file is not a Dropzone File object. Hence uploading mock file JavaScript object along with File object will cause Dropzone or internal server error.**

**Comment by holic-cl** [comment]
Hi, i don't know if about this bug, but when i add manually a file to dropzone, with max-number-of-files set to 1, i can't remove it and then add a new one.

It show me this message:

> You can not upload any more files. (max: 0)

And the **dropzone.files.length** is always zero.

**Comment by vrajroham** [comment]
Hey @holic-cl, Which version you are using? I confirm that this was an issue earlier release `V2.2.7`. You can upgrade to latest release. Please let us know if issue persists.

Thanks

**Comment by holic-cl** [comment]
I was using it for unlimited files, but i had to change the limit only to one file.

Now when i try to add a file after remove the file added manually, i can't.

I have "Vue2-dropzone": "^ 2.3.1"

**Comment by vrajroham** [comment]
Hi folks,

Version 3 is now released.[ Check out the new docs](https://rowanwins.github.io/vue-dropzone/docs/dist/#/installation) for more info.

**Comment by holic-cl** [comment]
Cool, thanks.

**Comment by vrajroham** [comment]
Closing, as this issue is resolved in V3.
