### ISSUE TITLE
jQuery Dependency

### ISSUE THREAD

**Issue by schulzefelix** [rowanwins/vue-dropzone#84]
Is jQuery really needed, even if Drozone itself don't rely on it?
Its not listed in the dependenvies but referenced in the dist folder.

```
This dependency was not found:

* jquery in ./~/vue2-dropzone/dist/vue2-dropzone.js
```

**Comment by rowanwins** [comment]
Hi @schulzefelix 

Where are you finding that vue-dropzone requires jquery?

Dropzone does not [require jquery as a dependency](https://github.com/enyo/dropzone/blob/master/package.json) and neither does [vue dropzone](https://github.com/rowanwins/vue-dropzone/blob/vue2/package.json)

Cheers

**Comment by schulzefelix** [comment]
Just wanted to compile my main js file and it was giving me the above error.

It seems that JQuery is referenced in this file a few times:
[https://github.com/rowanwins/vue-dropzone/blob/vue2/dist/vue2-dropzone.js](https://github.com/rowanwins/vue-dropzone/blob/vue2/dist/vue2-dropzone.js)

Cheers Felix

**Comment by rowanwins** [comment]
Hmm it looks like Dropzone runs a check if jQuery is [present here](https://github.com/enyo/dropzone/blob/master/dist/dropzone.js#L1626-L1632). Im going to close this issue because it's not really related to this component, having said that I'll keep trying to help. 

I'm not sure why that would be interrupting your build, are you using webpack as you build tool?

**Comment by schulzefelix** [comment]
hm okay thank you, I will try to investigate further why its stopping there. And yes using Webpack via Laravel Mix.

**Comment by rowanwins** [comment]
Hmm yeah I just did a quick google and it looks like lots of people have posted similar problems with Laravel Mix so I suggest following up through that community if possible, unfortunantly I know nothing about what that does sorry.

**Comment by schulzefelix** [comment]
Just for reference - here the issue at dropzone itself: https://github.com/enyo/dropzone/issues/1495

**Comment by piterjov** [comment]
It may be closely related to webpack configuration like in my case.
I removed webpack plugin for jQuery which I did not need.
`   new webpack.ProvidePlugin({
          $: "jquery",
          jQuery: "jquery",
          "window.jQuery": "jquery"
      })`
