### ISSUE TITLE
Server side couldn't receive file？

### ISSUE THREAD

**Issue by atricfox** [rowanwins/vue-dropzone#88]
My Client:

```vue
<template>
    <div>
        <dropzone id="filesDropzone" :useFontAwesome="true" :url="url" v-on:vdropzone-success="showSuccess" :language="langZh" :vdropzone-error="showError" :showRemoveLink="true" :options="options">
        </dropzone>
    </div>
</template>
```

```javascript
<script>
import Dropzone from 'vue2-dropzone'

export default {
  name: 'MainApp',
  data: function () {
    return {
      url: '',
      langZh: {
        dictDefaultMessage: '点击或者将文件拖拉至此处上传',
        dictFallbackMessage: '你的浏览器不支持拖拉上传',
        dictCancelUploadConfirmation: '移除文件，不再上传？',
        dictResponseError: '服务器错误'
      },
      options: {
        headers: {
          'Access-Control-Allow-Headers': 'application/x-www-form-urlencoded',
          'Access-Control-Allow-Methods': 'OPTIONS,POST'
        }
      }
    }
  },
  components: {
    Dropzone
  },
  props: ['meta'],
  created: function () {
    console.log(this.meta.pid)
    this.url = this.axios.defaults.baseURL + 'folder/upload?proid=' + this.meta.proid + '&pid=' + this.meta.pid + '&access-token=' + sessionStorage.getItem('token')
  },
  methods: {
    showSuccess: function (file, response) {
      console.log(response)
    },
    showError: function (file) {
      console.log(999999)
    }
  }
}
</script>
```

My Server Side:
```php
'cors' => [
	'Origin' => ['*'],
	'Access-Control-Request-Method' => ['GET', 'POST', 'PUT', 'PATCH', 'DELETE', 'HEAD', 'OPTIONS'],
	'Access-Control-Request-Headers' => ['Authorization', 'Content-Type', 'Accept'],
],
```
I configured the cors,but the server side couldn't find any file request.Why? 
Would you help me?Thanks!

**Comment by vrajroham** [comment]
Did you tried `mounted()` replacing `created()` ?  Try to log `url` in console and tell what you get.

**Comment by atricfox** [comment]
@vrajroham Oh,url will be inited with created() ,not mounted().The url has no error, my serve side can receive other request, but file is exceptive.

**Comment by rowanwins** [comment]
Hmmm Im not sure sorry @atricfox , it sounds like something is going wrong on the server side, what kind of server are you using? Dropzone [provides some links](http://www.dropzonejs.com/#server-side-implementation) on how to handle file uploads using various server side approaches so I'd recommend checking those out.

**Comment by atricfox** [comment]
@rowanwins Thank you! I think there is not wrong in the server side, when I use original <input> of html, I will upload file successfully. The url was not changed any all. So I think the headers configure must be wrong.

**Comment by rowanwins** [comment]
Ah ok, I think looking at your code above you're probably not setting the headers at all.

Perhaps try something like 
````

<template>
    <div>
        <dropzone id="filesDropzone" :useFontAwesome="true" :url="url" v-on:vdropzone-success="showSuccess" :language="langZh" :vdropzone-error="showError" :showRemoveLink="true" :headers="options.headers">
        </dropzone>
    </div>
</template>
````

You should be able to watch the network tab in devtools to see what headers are being sent with the request and compare it to the regular `<input>`

**Comment by atricfox** [comment]
@rowanwins Thank you very much! This is exactly the answer!
 I mix the options with dropzoneOptions. I just use headers directly.

`<div>
        <dropzone id="filesDropzone" :useFontAwesome="true" :url="url" v-on:vdropzone-success="showSuccess" :language="langZh" :showRemoveLink="true" :vdropzone-error="showError" :headers="headers">
        </dropzone>
    </div>`

`data: function () {
    return {
      url: '',
      langZh: {
        dictDefaultMessage: '点击或者将文件拖拉至此处上传',
        dictFallbackMessage: '你的浏览器不支持拖拉上传',
        dictCancelUploadConfirmation: '移除文件，不再上传？',
        dictRemoveFile: '移除',
        dictResponseError: '服务器错误({{statusCode}})'
      },
      headers: {
        'Content-Type': 'application/x-www-form-urlencoded'
      }
    }
  }`

Thanks a lot!
