### ISSUE TITLE
Can not call method on dropzone ref

### ISSUE THREAD

**Issue by chiragparekh** [rowanwins/vue-dropzone#89]
HI,

I tried to call setOption method on this.$refs.dz.setOption but it gives me error "this.$refs.myDropzone.setOption is not a function". I tried also other method but it gave me same error.

P.S: dz is ref name of my dropzone element.

Right now I solved my issue by 

this.$refs.dz.dropzone.options.headers ={
 // HEADER OPTINS
};

**Comment by rowanwins** [comment]
Hi @chiragparekh 

Thanks for the report, we've experienced this before so it looks like it's something of a sporadic issue, I'll take a look at the code base to see if I can work out what's going on.

Can you post your full component code so I can see how you've set it up?

Thanks

**Comment by arifhussain353** [comment]
@rowanwins  I have same issue.I want to set image on page load to `dropzone`. Here is my code below 
In html i use with `ref` tag
```
<dropzone ref="myVueDropzoneRef" id="myVueDropzone" url="/dropzoneFileUpload/DiscoveryArticleImage" v-bind:use-custom-dropzone-options="true" v-bind:dropzone-options="dropzoneOption()" v-on:vdropzone-success="vDropzoneCallback" v-on:vdropzone-error="vDropzoneCallback" v-on:vdropzone-removed-file="vDropzoneRemoveImage('DiscoveryArticleImage')"></dropzone>

```

And on same page below in `created hook`:
```
  created(){

            let dropzone = this.$refs.myVueDropzoneRef;
            console.debug("ref===",this.$refs);
            var mockFile = { name: "icon.jpg", size: 12345 };
            dropzone.processQueue()


        }
```

I got this error when try to use `dropzone methods`
```
TypeError: Cannot read property 'manuallyAddFile' of undefined
```

**Comment by arifhussain353** [comment]
I was using `dropzone` in bootstrap model and issue solved by calling `dropzone` on boostrap  `shown.bs.modal` event.

**Comment by bobbygerez** [comment]
@arifhussain353 @rowanwins It doesn't work... Actually it should be put in the `mounted()` but still ti doesn't work.  Reference: https://stackoverflow.com/questions/40884194/vuejs-cant-access-refs-from-component

**Comment by bobbygerez** [comment]
I don't know what happens but it works now @version2.3.4.

**Comment by rowanwins** [comment]
I'm going to close this due to a major release of v3, [check out the new docs](https://rowanwins.github.io/vue-dropzone/docs/dist/#/installation). If this is still an issue let us know.

**Comment by hamza-mashhadi** [comment]
I'm experience the same issue and it's been a week, I don't understand if there's something I'm doing wrong. 
the dropzone $ref can be found in the functions that I call directly from dropzone events like 
                      @vdropzone-removed-file="vremoved"
                      @vdropzone-sending="sendingEvent"
                      @vdropzone-success="vsuccess"
But if I try to access dropzone from a custom function it gives dropzone ref as undefined.
I was trying to manually add files and it gave me error which led me to this issue.
Please let me know any possible solutions or mistakes I'm making.
I have a function through which I'm trying to manually add a file by button click 
var file = { size: 123, name: "Icon", type: "image/png" };
                var url = "https://myvizo.com/img/logo_sm.png";
                this.$refs.myVueDropzone.manuallyAddFile(file, url);
                console.log(this.$refs,this.$refs.myVueDropzone,this.$refs['myVueDropzone']);
this console log shows myVueDropzone in this.$refs , but when I try to access it , then it gives undefined through both possible ways (attached console log)
![vuedropzone](https://user-images.githubusercontent.com/46528421/72148324-4f941c00-33c2-11ea-823e-757331805f0c.PNG)
