### ISSUE TITLE
Font-Awesome Remove uploaded Image

### ISSUE THREAD

**Issue by patpaskoch** [rowanwins/vue-dropzone#90]
I set  :useFontAwesome="true"  on the component, the cloud image works, but the uploaded images remove icon is just a white frame.

greetings

**Comment by rowanwins** [comment]
Hi @patpaskoch 

Sounds like you haven't loaded don't awesome on your site, you need to include it in the head of your site like
````
   <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet">
````

Let me know how you get on

**Comment by patpaskoch** [comment]
well if the upload-cloud appears font awesome should be there and I work with weppack and import font awesome.scss from my node modules

**Comment by rowanwins** [comment]
Ah sorry @patpaskoch I misread your initial message.

I've just checked and everything works as expected. One thing to check is to make sure that you're passing thorugh the parameter name correctly it needs to be done like
````
<dropzone :use-font-awesome="true">
````
If that doesnt work for you could you please send through a screenshot?

Thanks

**Comment by patpaskoch** [comment]
Import Font Awesome 4.7.0
@import "node_modules/font-awesome/scss/font-awesome.scss";

html dropzone
```
<dropzone id="vueDropzone" 
			:language="language" 
			:use-font-awesome="true" 
			:url="'url'" 
			:show-remove-link="true"
			v-on:vdropzone-success="showSuccess"
		>
	        	<input type="hidden" name="_token" :value="csrf ">
	    </dropzone>
```

so the first and second screenshot show dropzone without prop :useFontAwesome
third and last show with :use-font-awesome

![screen shot 2017-05-15 at 08 47 05 2](https://cloud.githubusercontent.com/assets/4086365/26045659/85b9eff4-394b-11e7-92a0-2192b76bd2ca.png)

![screen shot 2017-05-15 at 08 48 32 2](https://cloud.githubusercontent.com/assets/4086365/26045683/ae1ee580-394b-11e7-949f-eb58d90b3e35.png)

![screen shot 2017-05-15 at 08 47 47 2](https://cloud.githubusercontent.com/assets/4086365/26045830/48b8c282-394c-11e7-8699-66e48d3c1987.png)

![screen shot 2017-05-15 at 08 48 06 2](https://cloud.githubusercontent.com/assets/4086365/26045849/65dfa114-394c-11e7-91a1-4bf372118c4e.png)


so if I add the prop the cloud works and also the check-mark if images got successfully uploaded apears.

**Comment by rowanwins** [comment]
Can you remove `:show-remove-link="true"` , I don't normally set this as it defaults to true anyway

**Comment by patpaskoch** [comment]
removed it, didn't changed a thing

**Comment by rowanwins** [comment]
How about your language object, it looks like you are passing through a custom object, does it contain a `dictRemoveFile` property?

**Comment by patpaskoch** [comment]
```
language: {
dictDefaultMessage: '<br>Drag and Drop files in this area or click in it.'
}
```

the html that gets displayed 
```
<a class="dz-remove" href="javascript:undefined;" data-dz-remove=""></a>
```

**Comment by patpaskoch** [comment]
also, the error icon has troubles
![vuedropzone problem](https://cloud.githubusercontent.com/assets/4086365/26053069/b375db62-3967-11e7-87ee-eb3b6babe368.png)

**Comment by rowanwins** [comment]
Hi @patpaskoch 

Any language object that you pass through does not merge on to the default object, so you have to pass through all the language settings, this isn't ideal, I'll try and get it fixed at some stage although Im open to a pull request

**Comment by patpaskoch** [comment]
Ok I get it, removed the language prop and everything works just fine.

**Comment by rowanwins** [comment]
Thanks for your fix @patpaskoch , Im going to mark this as closed and I'll drop a note here when it's published to npm
