### ISSUE TITLE
make maxNumberOfFiles reactive

### ISSUE THREAD

**Issue by shigg1120** [rowanwins/vue-dropzone#93]
Is it possible to make `maxNumberOfFiles` reactive?

I wanna limit the number of photos to be uploaded by 3, and if one of them gets deleted I want  `maxNumberOfFiles` to increase by 1.

Atm, I fire up an event when a photo is deleted in a different component, and vue-dropzone listens to the event and add 1 to maxNumberOfFiles. It seems like the number is added successfully, but dropzone component is not aware of the change, and would not let me add one more file.

Is there any workaround for this?

**Comment by rowanwins** [comment]
You should be able to use the `setOption` method

Something like 
````
this.$refs.myUniqueID.setMethod('maxFiles', currentMax + 1)
````
