### ISSUE TITLE
maxNumberOfFiles 设置了这个等于1，为何还能无限添加图片？

### ISSUE THREAD

**Issue by 531431988** [rowanwins/vue-dropzone#98]
如题 (Such as title)

**Comment by vrajroham** [comment]
@531431988 can you change title to English? Comment too.

**Comment by 531431988** [comment]
maxNumberOfFiles Set this to 1, why can you add unlimited pictures?

**Comment by rowanwins** [comment]
Make sure you set it like 
````
   :max-number-of-files=1
````

**Comment by 531431988** [comment]
Or you can upload more than one
![qq 20170524170815](https://cloud.githubusercontent.com/assets/8703951/26395834/e730f430-40a3-11e7-967e-f1517bbede72.png)
![qq 20170524171029](https://cloud.githubusercontent.com/assets/8703951/26395859/fa24cabc-40a3-11e7-8a5a-d1ddaf89ece4.png)

**Comment by 531431988** [comment]
Accurate, yes, you can also select the picture, but will not upload, can: max-number-of-files = "1" select the picture is not showing thumbnails

**Comment by vrajroham** [comment]
Your point is valid @531431988 . files more than max files count should not be shown in preview. But this feature is depend on [core dropzone library](https://github.com/enyo/dropzone).

Closing this issue as it was a question and it is answered and accepted.
